'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace EmailServiceReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IMessageService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MessageService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private TestingWSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendEmailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendEmailMamiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendEmailImageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendNotificationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.eProcurementApps.Helpers.My.MySettings.Default.eProcurementApps_Helpers_EmailServiceReference_MessageService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event TestingWSCompleted As TestingWSCompletedEventHandler
        
        '''<remarks/>
        Public Event SendSMSCompleted As SendSMSCompletedEventHandler
        
        '''<remarks/>
        Public Event SendEmailCompleted As SendEmailCompletedEventHandler
        
        '''<remarks/>
        Public Event SendEmailMamiCompleted As SendEmailMamiCompletedEventHandler
        
        '''<remarks/>
        Public Event SendEmailImageCompleted As SendEmailImageCompletedEventHandler
        
        '''<remarks/>
        Public Event SendNotificationCompleted As SendNotificationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMessageService/TestingWS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestingWS(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal condition As TestingContract, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef result As TestingResultContract) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("TestingWS", New Object() {condition, result})
            result = CType(results(1),TestingResultContract)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestingWSAsync(ByVal condition As TestingContract, ByVal result As TestingResultContract)
            Me.TestingWSAsync(condition, result, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestingWSAsync(ByVal condition As TestingContract, ByVal result As TestingResultContract, ByVal userState As Object)
            If (Me.TestingWSOperationCompleted Is Nothing) Then
                Me.TestingWSOperationCompleted = AddressOf Me.OnTestingWSOperationCompleted
            End If
            Me.InvokeAsync("TestingWS", New Object() {condition, result}, Me.TestingWSOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestingWSOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestingWSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestingWSCompleted(Me, New TestingWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMessageService/SendSMS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendSMS(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal transaction As SmsKeyContract, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef output As SmsResultContract) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("SendSMS", New Object() {transaction, output})
            output = CType(results(1),SmsResultContract)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendSMSAsync(ByVal transaction As SmsKeyContract, ByVal output As SmsResultContract)
            Me.SendSMSAsync(transaction, output, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendSMSAsync(ByVal transaction As SmsKeyContract, ByVal output As SmsResultContract, ByVal userState As Object)
            If (Me.SendSMSOperationCompleted Is Nothing) Then
                Me.SendSMSOperationCompleted = AddressOf Me.OnSendSMSOperationCompleted
            End If
            Me.InvokeAsync("SendSMS", New Object() {transaction, output}, Me.SendSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendSMSCompleted(Me, New SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMessageService/SendEmail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmail(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal transaction As EmailContract, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef output As EmailResultContract) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("SendEmail", New Object() {transaction, output})
            output = CType(results(1),EmailResultContract)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendEmailAsync(ByVal transaction As EmailContract, ByVal output As EmailResultContract)
            Me.SendEmailAsync(transaction, output, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendEmailAsync(ByVal transaction As EmailContract, ByVal output As EmailResultContract, ByVal userState As Object)
            If (Me.SendEmailOperationCompleted Is Nothing) Then
                Me.SendEmailOperationCompleted = AddressOf Me.OnSendEmailOperationCompleted
            End If
            Me.InvokeAsync("SendEmail", New Object() {transaction, output}, Me.SendEmailOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendEmailOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendEmailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendEmailCompleted(Me, New SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMessageService/SendEmailMami", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmailMami(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal transaction As EmailMamiContract, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef output As EmailResultContract) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("SendEmailMami", New Object() {transaction, output})
            output = CType(results(1),EmailResultContract)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendEmailMamiAsync(ByVal transaction As EmailMamiContract, ByVal output As EmailResultContract)
            Me.SendEmailMamiAsync(transaction, output, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendEmailMamiAsync(ByVal transaction As EmailMamiContract, ByVal output As EmailResultContract, ByVal userState As Object)
            If (Me.SendEmailMamiOperationCompleted Is Nothing) Then
                Me.SendEmailMamiOperationCompleted = AddressOf Me.OnSendEmailMamiOperationCompleted
            End If
            Me.InvokeAsync("SendEmailMami", New Object() {transaction, output}, Me.SendEmailMamiOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendEmailMamiOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendEmailMamiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendEmailMamiCompleted(Me, New SendEmailMamiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMessageService/SendEmailImage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendEmailImage(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal transaction As EmailImageContract, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef output As EmailResultContract) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("SendEmailImage", New Object() {transaction, output})
            output = CType(results(1),EmailResultContract)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendEmailImageAsync(ByVal transaction As EmailImageContract, ByVal output As EmailResultContract)
            Me.SendEmailImageAsync(transaction, output, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendEmailImageAsync(ByVal transaction As EmailImageContract, ByVal output As EmailResultContract, ByVal userState As Object)
            If (Me.SendEmailImageOperationCompleted Is Nothing) Then
                Me.SendEmailImageOperationCompleted = AddressOf Me.OnSendEmailImageOperationCompleted
            End If
            Me.InvokeAsync("SendEmailImage", New Object() {transaction, output}, Me.SendEmailImageOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendEmailImageOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendEmailImageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendEmailImageCompleted(Me, New SendEmailImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMessageService/SendNotification", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendNotification(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal transaction As NotificationContract, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef output As NotificationResultContract) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BusinessErrors
            Dim results() As Object = Me.Invoke("SendNotification", New Object() {transaction, output})
            output = CType(results(1),NotificationResultContract)
            Return CType(results(0),BusinessErrors)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendNotificationAsync(ByVal transaction As NotificationContract, ByVal output As NotificationResultContract)
            Me.SendNotificationAsync(transaction, output, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendNotificationAsync(ByVal transaction As NotificationContract, ByVal output As NotificationResultContract, ByVal userState As Object)
            If (Me.SendNotificationOperationCompleted Is Nothing) Then
                Me.SendNotificationOperationCompleted = AddressOf Me.OnSendNotificationOperationCompleted
            End If
            Me.InvokeAsync("SendNotification", New Object() {transaction, output}, Me.SendNotificationOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendNotificationOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendNotificationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendNotificationCompleted(Me, New SendNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class TestingContract
        
        Private inputField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Input() As String
            Get
                Return Me.inputField
            End Get
            Set
                Me.inputField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class NotificationResultContract
        
        Private detailTransField() As String
        
        Private respondCodeField As String
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property DetailTrans() As String()
            Get
                Return Me.detailTransField
            End Get
            Set
                Me.detailTransField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RespondCode() As String
            Get
                Return Me.respondCodeField
            End Get
            Set
                Me.respondCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class NotificationContract
        
        Private actionIDField As String
        
        Private paramField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ActionID() As String
            Get
                Return Me.actionIDField
            End Get
            Set
                Me.actionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Param() As String
            Get
                Return Me.paramField
            End Get
            Set
                Me.paramField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class GetEmailImageContract
        
        Private imageLocationField As String
        
        Private imageNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ImageLocation() As String
            Get
                Return Me.imageLocationField
            End Get
            Set
                Me.imageLocationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ImageName() As String
            Get
                Return Me.imageNameField
            End Get
            Set
                Me.imageNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class EmailImageContract
        
        Private attachmentFileField() As String
        
        Private ccRecipientField() As String
        
        Private imageListField() As GetEmailImageContract
        
        Private messageField As String
        
        Private recipientField() As String
        
        Private senderField As String
        
        Private subjectField As String
        
        Private workAreaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property AttachmentFile() As String()
            Get
                Return Me.attachmentFileField
            End Get
            Set
                Me.attachmentFileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property CcRecipient() As String()
            Get
                Return Me.ccRecipientField
            End Get
            Set
                Me.ccRecipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property ImageList() As GetEmailImageContract()
            Get
                Return Me.imageListField
            End Get
            Set
                Me.imageListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property Recipient() As String()
            Get
                Return Me.recipientField
            End Get
            Set
                Me.recipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Sender() As String
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property WorkArea() As String
            Get
                Return Me.workAreaField
            End Get
            Set
                Me.workAreaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class EmailMamiContract
        
        Private attachmentFileField() As String
        
        Private ccRecipientField() As String
        
        Private messageIDField As String
        
        Private paramField As String
        
        Private recipientField() As String
        
        Private senderField As String
        
        Private subjectField As String
        
        Private workAreaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property AttachmentFile() As String()
            Get
                Return Me.attachmentFileField
            End Get
            Set
                Me.attachmentFileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property CcRecipient() As String()
            Get
                Return Me.ccRecipientField
            End Get
            Set
                Me.ccRecipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MessageID() As String
            Get
                Return Me.messageIDField
            End Get
            Set
                Me.messageIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Param() As String
            Get
                Return Me.paramField
            End Get
            Set
                Me.paramField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property Recipient() As String()
            Get
                Return Me.recipientField
            End Get
            Set
                Me.recipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Sender() As String
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property WorkArea() As String
            Get
                Return Me.workAreaField
            End Get
            Set
                Me.workAreaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class EmailResultContract
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class EmailContract
        
        Private attachmentFileField() As String
        
        Private ccRecipientField() As String
        
        Private messageField As String
        
        Private recipientField() As String
        
        Private senderField As String
        
        Private subjectField As String
        
        Private workAreaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property AttachmentFile() As String()
            Get
                Return Me.attachmentFileField
            End Get
            Set
                Me.attachmentFileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property CcRecipient() As String()
            Get
                Return Me.ccRecipientField
            End Get
            Set
                Me.ccRecipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property Recipient() As String()
            Get
                Return Me.recipientField
            End Get
            Set
                Me.recipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Sender() As String
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property WorkArea() As String
            Get
                Return Me.workAreaField
            End Get
            Set
                Me.workAreaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class SmsResultContract
        
        Private statusField As String
        
        Private trxIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TrxId() As String
            Get
                Return Me.trxIdField
            End Get
            Set
                Me.trxIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class SmsKeyContract
        
        Private messageField As String
        
        Private recipientField() As String
        
        Private vendorField As String
        
        Private workAreaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property Recipient() As String()
            Get
                Return Me.recipientField
            End Get
            Set
                Me.recipientField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Vendor() As String
            Get
                Return Me.vendorField
            End Get
            Set
                Me.vendorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property WorkArea() As String
            Get
                Return Me.workAreaField
            End Get
            Set
                Me.workAreaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BusinessWarningVo)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")>  _
    Partial Public Class BusinessErrorVo
        
        Private errorCodeField As String
        
        Private errorFieldField As String
        
        Private errorMessagesField() As ArrayOfKeyValueOfstringstringKeyValueOfstringstring
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ErrorField() As String
            Get
                Return Me.errorFieldField
            End Get
            Set
                Me.errorFieldField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)>  _
        Public Property ErrorMessages() As ArrayOfKeyValueOfstringstringKeyValueOfstringstring()
            Get
                Return Me.errorMessagesField
            End Get
            Set
                Me.errorMessagesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Partial Public Class ArrayOfKeyValueOfstringstringKeyValueOfstringstring
        
        Private keyField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")>  _
    Partial Public Class BusinessWarningVo
        Inherits BusinessErrorVo
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Core.Model.Business")>  _
    Partial Public Class BusinessErrors
        
        Private errorListField() As BusinessErrorVo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property ErrorList() As BusinessErrorVo()
            Get
                Return Me.errorListField
            End Get
            Set
                Me.errorListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Manulife.Id.PolicyAdmin.Interface")>  _
    Partial Public Class TestingResultContract
        
        Private hasilField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Hasil() As String
            Get
                Return Me.hasilField
            End Get
            Set
                Me.hasilField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub TestingWSCompletedEventHandler(ByVal sender As Object, ByVal e As TestingWSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestingWSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public Overloads ReadOnly Property Result() As BusinessErrors
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BusinessErrors)
            End Get
        End Property

        '''<remarks/>
        'Public Overloads ReadOnly Property result() As TestingResultContract
        '    Get
        '        Me.RaiseExceptionIfNecessary
        '        Return CType(Me.results(1),TestingResultContract)
        '    End Get
        'End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub SendSMSCompletedEventHandler(ByVal sender As Object, ByVal e As SendSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BusinessErrors
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BusinessErrors)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property output() As SmsResultContract
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),SmsResultContract)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub SendEmailCompletedEventHandler(ByVal sender As Object, ByVal e As SendEmailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendEmailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BusinessErrors
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BusinessErrors)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property output() As EmailResultContract
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),EmailResultContract)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub SendEmailMamiCompletedEventHandler(ByVal sender As Object, ByVal e As SendEmailMamiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendEmailMamiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BusinessErrors
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BusinessErrors)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property output() As EmailResultContract
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),EmailResultContract)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub SendEmailImageCompletedEventHandler(ByVal sender As Object, ByVal e As SendEmailImageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendEmailImageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BusinessErrors
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BusinessErrors)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property output() As EmailResultContract
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),EmailResultContract)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")>  _
    Public Delegate Sub SendNotificationCompletedEventHandler(ByVal sender As Object, ByVal e As SendNotificationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendNotificationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BusinessErrors
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BusinessErrors)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property output() As NotificationResultContract
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),NotificationResultContract)
            End Get
        End Property
    End Class
End Namespace
