
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 12/20/2017 10:41:55
-- Generated from EDMX file: D:\Hamka\GitHub\eProcurementApps\eProcurementApps\eProcurementApps.Models\eProcModel.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [eProcurement];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_APPROVAL_GROUP]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPROVAL_DT] DROP CONSTRAINT [FK_APPROVAL_GROUP];
GO
IF OBJECT_ID(N'[dbo].[FK_APPROVAL_GROUP_WA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_WA] DROP CONSTRAINT [FK_APPROVAL_GROUP_WA];
GO
IF OBJECT_ID(N'[dbo].[FK_APPROVAL_RELDEPT_GR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_REL_DEPT] DROP CONSTRAINT [FK_APPROVAL_RELDEPT_GR];
GO
IF OBJECT_ID(N'[dbo].[FK_DIVISION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPROVAL_GR] DROP CONSTRAINT [FK_DIVISION];
GO
IF OBJECT_ID(N'[dbo].[FK_DIVISION_USER_DT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [FK_DIVISION_USER_DT];
GO
IF OBJECT_ID(N'[dbo].[FK_GM_TPROC_PO_HEADERS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_GM_HEADERS] DROP CONSTRAINT [FK_GM_TPROC_PO_HEADERS];
GO
IF OBJECT_ID(N'[dbo].[FK_LEVEL_APPROVAL_DT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPROVAL_DT] DROP CONSTRAINT [FK_LEVEL_APPROVAL_DT];
GO
IF OBJECT_ID(N'[dbo].[FK_LEVEL_APPROVAL_ROLE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] DROP CONSTRAINT [FK_LEVEL_APPROVAL_ROLE];
GO
IF OBJECT_ID(N'[dbo].[FK_MENU_ROLE_EPROC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [FK_MENU_ROLE_EPROC];
GO
IF OBJECT_ID(N'[dbo].[FK_PC_DT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PC_SP_DT] DROP CONSTRAINT [FK_PC_DT];
GO
IF OBJECT_ID(N'[dbo].[FK_PC_SP_GR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PC_SP_GR] DROP CONSTRAINT [FK_PC_SP_GR];
GO
IF OBJECT_ID(N'[dbo].[FK_PO_DETAILS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_DETAILS_ITEM] DROP CONSTRAINT [FK_PO_DETAILS];
GO
IF OBJECT_ID(N'[dbo].[FK_PO_HEADER_ID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_DETAILS] DROP CONSTRAINT [FK_PO_HEADER_ID];
GO
IF OBJECT_ID(N'[dbo].[FK_ROLE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [FK_ROLE];
GO
IF OBJECT_ID(N'[dbo].[FK_ROLE_USER_DETAIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [FK_ROLE_USER_DETAIL];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[FK_TPROC_ACKNOW_APPR]', 'F') IS NOT NULL
    ALTER TABLE [eProcModelStoreContainer].[TPROC_ACKNOW_APPR_DT] DROP CONSTRAINT [FK_TPROC_ACKNOW_APPR];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_APPR_RELDEPT_GR_2]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] DROP CONSTRAINT [FK_TPROC_APPR_RELDEPT_GR_2];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_COA_GR_FST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] DROP CONSTRAINT [FK_TPROC_COA_GR_FST];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_CURRENCY]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_CURRENCY];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_DELIVERY_ADDRESS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_DELIVERY_ADDRESS];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_FORM_SUB_TYPE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_HEADER] DROP CONSTRAINT [FK_TPROC_FORM_SUB_TYPE];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_FORM_TYPE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_HEADER] DROP CONSTRAINT [FK_TPROC_FORM_TYPE];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_FORM_TYPE_PO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_TYPE] DROP CONSTRAINT [FK_TPROC_FORM_TYPE_PO];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_FORM_TYPE_STOCK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [FK_TPROC_FORM_TYPE_STOCK];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_FST_BUDGET_CD_ADD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] DROP CONSTRAINT [FK_TPROC_FST_BUDGET_CD_ADD];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_GOOD_TYPE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [FK_TPROC_GOOD_TYPE];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_GOOD_TYPE_PR_HEADER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_HEADER] DROP CONSTRAINT [FK_TPROC_GOOD_TYPE_PR_HEADER];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_LEVEL_RELDEPT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] DROP CONSTRAINT [FK_TPROC_LEVEL_RELDEPT];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PC_APPR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPR_PC] DROP CONSTRAINT [FK_TPROC_PC_APPR];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PC_HISTORY]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] DROP CONSTRAINT [FK_TPROC_PC_HISTORY];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PC_SP_GR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PC_SP_DT] DROP CONSTRAINT [FK_TPROC_PC_SP_GR];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PC_VRF]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_VRF_PC] DROP CONSTRAINT [FK_TPROC_PC_VRF];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PO_APPR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_APPR_PO] DROP CONSTRAINT [FK_TPROC_PO_APPR];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PO_TYPE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_PO_TYPE];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PO_VRF]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_VRF_PO] DROP CONSTRAINT [FK_TPROC_PO_VRF];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PR_APPR_RD_GR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_DT] DROP CONSTRAINT [FK_TPROC_PR_APPR_RD_GR];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PR_DETAIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_APPR_WA] DROP CONSTRAINT [FK_TPROC_PR_DETAIL];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [FK_TPROC_PR_HEADER];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER_ATTACHMENT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] DROP CONSTRAINT [FK_TPROC_PR_HEADER_ATTACHMENT];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[FK_TPROC_PR_HEADER_HISTORY]', 'F') IS NOT NULL
    ALTER TABLE [eProcModelStoreContainer].[TPROC_PR_HISTORICAL] DROP CONSTRAINT [FK_TPROC_PR_HEADER_HISTORY];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER_RD_GR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] DROP CONSTRAINT [FK_TPROC_PR_HEADER_RD_GR];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUBTYPE_DT_FT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_DT] DROP CONSTRAINT [FK_TPROC_SUBTYPE_DT_FT];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUBTYPE_DT_RD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_DT] DROP CONSTRAINT [FK_TPROC_SUBTYPE_DT_RD];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUBTYPE_GR_FST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_FORM_SUB_TYPE] DROP CONSTRAINT [FK_TPROC_SUBTYPE_GR_FST];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUBTYPE_GR_FT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] DROP CONSTRAINT [FK_TPROC_SUBTYPE_GR_FT];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUPP_DOC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [FK_TPROC_SUPP_DOC];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUPPLIER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_SUPPLIER];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUPPLIER_EVAL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_SUPP_EVAL] DROP CONSTRAINT [FK_TPROC_SUPPLIER_EVAL];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_SUPPLIER_QUAL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [FK_TPROC_SUPPLIER_QUAL];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_USER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_HEADER] DROP CONSTRAINT [FK_TPROC_USER];
GO
IF OBJECT_ID(N'[dbo].[FK_TPROC_WA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [FK_TPROC_WA];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_DT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_USER] DROP CONSTRAINT [FK_USER_DT];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_EPROC_PROFILE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_USER_PROFILE] DROP CONSTRAINT [FK_USER_EPROC_PROFILE];
GO
IF OBJECT_ID(N'[dbo].[FK_WA_ALLOWED_GROUP]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_WA_ALLOWED_DT] DROP CONSTRAINT [FK_WA_ALLOWED_GROUP];
GO
IF OBJECT_ID(N'[dbo].[FK_WA_GROUP_USER_DETAIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [FK_WA_GROUP_USER_DETAIL];
GO
IF OBJECT_ID(N'[dbo].[FK_WORK_AREA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TPROC_WA_ALLOWED_DT] DROP CONSTRAINT [FK_WORK_AREA];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[MenuSidebar]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MenuSidebar];
GO
IF OBJECT_ID(N'[dbo].[TPROC_ACKNOW_APPR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_ACKNOW_APPR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPR_PC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPR_PC];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPR_PO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPR_PO];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPR_RELDEPT_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPR_RELDEPT_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPR_RELDEPT_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPR_RELDEPT_GR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPROVAL_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPROVAL_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPROVAL_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPROVAL_GR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_APPROVAL_ROLE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_APPROVAL_ROLE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_BUDGET_CODE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_BUDGET_CODE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_CHART_OF_ACCOUNT_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_CHART_OF_ACCOUNTS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_CURRENCY]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_CURRENCY];
GO
IF OBJECT_ID(N'[dbo].[TPROC_DELIVERY_ADDRESS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_DELIVERY_ADDRESS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_DIVISION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_DIVISION];
GO
IF OBJECT_ID(N'[dbo].[TPROC_DOCUMENTS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_DOCUMENTS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_FIELD_VALUES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_FIELD_VALUES];
GO
IF OBJECT_ID(N'[dbo].[TPROC_FORM_SUB_TYPE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_FORM_SUB_TYPE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_FORM_SUBTYPE_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_FORM_SUBTYPE_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_FORM_SUBTYPE_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_FORM_SUBTYPE_GR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_FORM_TYPE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_FORM_TYPE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_FST_BUDGET_CD_ADD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD];
GO
IF OBJECT_ID(N'[dbo].[TPROC_GENERATOR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_GENERATOR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_GM_HEADERS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_GM_HEADERS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_GOOD_TYPE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_GOOD_TYPE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_HOLIDAY]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_HOLIDAY];
GO
IF OBJECT_ID(N'[dbo].[TPROC_LEVEL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_LEVEL];
GO
IF OBJECT_ID(N'[dbo].[TPROC_LOG_TRANSACTIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_LOG_TRANSACTIONS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_MENU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_MENU];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PC];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PC_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PC_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PC_HISTORICAL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PC_HISTORICAL];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PC_SP_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PC_SP_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PC_SP_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PC_SP_GR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PO_DETAILS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PO_DETAILS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PO_DETAILS_ITEM]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PO_DETAILS_ITEM];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PO_HEADERS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PO_HEADERS];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PO_TYPE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PO_TYPE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PPH]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PPH];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PR_APPR_RELDEPT_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PR_APPR_RELDEPT_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PR_APPR_RELDEPT_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PR_APPR_WA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PR_APPR_WA];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PR_ATTACHMENT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PR_ATTACHMENT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PR_DETAIL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PR_DETAIL];
GO
IF OBJECT_ID(N'[dbo].[TPROC_PR_HEADER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_PR_HEADER];
GO
IF OBJECT_ID(N'[dbo].[TPROC_REL_DEPT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_REL_DEPT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_REQUEST]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_REQUEST];
GO
IF OBJECT_ID(N'[dbo].[TPROC_ROLE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_ROLE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_ROLE_MENU]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_ROLE_MENU];
GO
IF OBJECT_ID(N'[dbo].[TPROC_STOCK]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_STOCK];
GO
IF OBJECT_ID(N'[dbo].[TPROC_SUPP_DOC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_SUPP_DOC];
GO
IF OBJECT_ID(N'[dbo].[TPROC_SUPP_EVAL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_SUPP_EVAL];
GO
IF OBJECT_ID(N'[dbo].[TPROC_SUPP_QUAL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_SUPP_QUAL];
GO
IF OBJECT_ID(N'[dbo].[TPROC_SUPPLIER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_SUPPLIER];
GO
IF OBJECT_ID(N'[dbo].[TPROC_USER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_USER];
GO
IF OBJECT_ID(N'[dbo].[TPROC_USER_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_USER_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_USER_PROFILE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_USER_PROFILE];
GO
IF OBJECT_ID(N'[dbo].[TPROC_VAT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_VAT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_VRF_PC]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_VRF_PC];
GO
IF OBJECT_ID(N'[dbo].[TPROC_VRF_PO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_VRF_PO];
GO
IF OBJECT_ID(N'[dbo].[TPROC_WA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_WA];
GO
IF OBJECT_ID(N'[dbo].[TPROC_WA_ALLOWED_DT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_WA_ALLOWED_DT];
GO
IF OBJECT_ID(N'[dbo].[TPROC_WA_ALLOWED_GR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TPROC_WA_ALLOWED_GR];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_ACKNOW_APPR_DT]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_ACKNOW_APPR_DT];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_APPROVAL_ROLE_DETAIL]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_APPROVAL_ROLE_DETAIL];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_CONTROL_PARAMETERS]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_CONTROL_PARAMETERS];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_CRV]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_CRV];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_CRV_DETAILS]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_CRV_DETAILS];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_FIELD_DESCRIPTIONS]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_FIELD_DESCRIPTIONS];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_GM_DETAILS]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_GM_DETAILS];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_PARAMETERS]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_PARAMETERS];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_PR_HISTORICAL]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_PR_HISTORICAL];
GO
IF OBJECT_ID(N'[eProcModelStoreContainer].[TPROC_STOCKMOVEMENT]', 'U') IS NOT NULL
    DROP TABLE [eProcModelStoreContainer].[TPROC_STOCKMOVEMENT];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'MenuSidebars'
CREATE TABLE [dbo].[MenuSidebars] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [MenuCode] varchar(4)  NOT NULL,
    [MenuDescription] varchar(40)  NOT NULL,
    [IsInduk] smallint  NOT NULL,
    [Method] varchar(20)  NULL,
    [Controller] varchar(20)  NULL,
    [MenuInduk] int  NOT NULL,
    [Icon] varchar(20)  NULL,
    [CreatedTime] datetime  NOT NULL,
    [CreatedBy] varchar(20)  NOT NULL,
    [LastModifiedTime] datetime  NULL,
    [LastModifiedBy] varchar(20)  NULL,
    [TimeStatus] binary(8)  NOT NULL,
    [RowStatus] smallint  NOT NULL
);
GO

-- Creating table 'TPROC_ACKNOW_APPR'
CREATE TABLE [dbo].[TPROC_ACKNOW_APPR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_ID] int  NOT NULL,
    [WA_ID] int  NOT NULL,
    [WA_NUMBER] int  NOT NULL,
    [STATUS] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_APPR_PC'
CREATE TABLE [dbo].[TPROC_APPR_PC] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [NAME] varchar(50)  NOT NULL,
    [EMAIL] varchar(100)  NOT NULL,
    [AS_IS] varchar(20)  NULL,
    [STATUS] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_APPR_PO'
CREATE TABLE [dbo].[TPROC_APPR_PO] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PO_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [NAME] varchar(50)  NOT NULL,
    [EMAIL] varchar(100)  NOT NULL,
    [AS_IS] varchar(20)  NULL,
    [STATUS] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_APPR_RELDEPT_DT'
CREATE TABLE [dbo].[TPROC_APPR_RELDEPT_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [APPROVAL_RELDEPT_GR_ID] int  NOT NULL,
    [APPROVAL_NAME] varchar(50)  NOT NULL,
    [LEVEL_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [EMAIL] varchar(100)  NULL,
    [USER_NAME] varchar(50)  NULL
);
GO

-- Creating table 'TPROC_APPR_RELDEPT_GR'
CREATE TABLE [dbo].[TPROC_APPR_RELDEPT_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [REV_RD_ID] int  NULL
);
GO

-- Creating table 'TPROC_APPROVAL_DT'
CREATE TABLE [dbo].[TPROC_APPROVAL_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [APPROVAL_GROUP_ID] int  NOT NULL,
    [APPROVAL_NAME] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [FLOW_INTEGER] int  NOT NULL,
    [LEVEL_ID] int  NULL,
    [EMAIL] varchar(100)  NULL,
    [USER_NAME] varchar(50)  NULL,
    [FLOW_NUMBER] int  NOT NULL
);
GO

-- Creating table 'TPROC_APPROVAL_GR'
CREATE TABLE [dbo].[TPROC_APPROVAL_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [DEPARTMENT_NAME] varchar(50)  NULL,
    [DIVISION_ID] int  NULL,
    [REV_WA_ID] int  NULL
);
GO

-- Creating table 'TPROC_APPROVAL_ROLE'
CREATE TABLE [dbo].[TPROC_APPROVAL_ROLE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [LEVEL_ID] int  NOT NULL,
    [EMAIL] varchar(100)  NOT NULL,
    [USER_NAME] varchar(50)  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [SIGNATURE_IMAGE] varbinary(1)  NULL
);
GO

-- Creating table 'TPROC_BUDGET_CODE'
CREATE TABLE [dbo].[TPROC_BUDGET_CODE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [TABLE_BUDGET] varchar(20)  NULL,
    [TABLE_BUDGET_USAGE] varchar(20)  NULL,
    [CD_PRINTING_USAGE] varchar(20)  NULL,
    [CD_PRINTING_START] varchar(20)  NULL,
    [CD_PRINTING_END] varchar(20)  NULL,
    [CD_OFFICE_SUPPLIE_USAGE] varchar(20)  NULL,
    [CD_OFFICE_SUPPLIE_START] varchar(20)  NULL,
    [CD_OFFICE_SUPPLIE_END] varchar(20)  NULL,
    [CD_ASSET_NONASSET_USAGE] varchar(20)  NULL,
    [CD_ASSET_NONASSET_START] varchar(20)  NULL,
    [CD_ASSET_NONASSET_END] varchar(20)  NULL,
    [CD_PROMOTIONAL_ITEM_USAGE] varchar(20)  NULL,
    [CD_PROMOTIONAL_ITEM_START] varchar(20)  NULL,
    [CD_PROMOTIONAL_ITEM_END] varchar(20)  NULL,
    [IS_ACTIVE] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [CD_ISSUED_USAGE] varchar(20)  NULL,
    [TABLE_T1] varchar(20)  NULL,
    [TABLE_T2] varchar(20)  NULL,
    [TABLE_T3] varchar(20)  NULL,
    [TABLE_T5] varchar(20)  NULL,
    [CD_OFFICE_SUPPLIE_MT] varchar(20)  NULL,
    [CD_PRINTING_MT] varchar(20)  NULL
);
GO

-- Creating table 'TPROC_CHART_OF_ACCOUNT_GR'
CREATE TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CRCY_CD] varchar(2)  NOT NULL,
    [ACCT_NUM] varchar(8)  NOT NULL,
    [ACCT_DESC] varchar(100)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [REV_COA_ID] int  NULL,
    [CONVERTED_ACCT_NUM] varchar(8)  NULL
);
GO

-- Creating table 'TPROC_CHART_OF_ACCOUNTS'
CREATE TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [SUB_COA_GR_ID] int  NOT NULL
);
GO

-- Creating table 'TPROC_CURRENCY'
CREATE TABLE [dbo].[TPROC_CURRENCY] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CURRENCY_NAME] varchar(10)  NOT NULL,
    [RATE] int  NOT NULL,
    [START_DATE] datetime  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [CONVERSION_RP] int  NULL
);
GO

-- Creating table 'TPROC_DELIVERY_ADDRESS'
CREATE TABLE [dbo].[TPROC_DELIVERY_ADDRESS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DELIVERY_NAME] varchar(50)  NOT NULL,
    [DELIVERY_ADDRESS] varchar(100)  NOT NULL,
    [DEFAULT_IND] varchar(1)  NULL,
    [DELIVERY_PHONE] varchar(20)  NULL,
    [DELIVERY_FAX] varchar(20)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_DIVISION'
CREATE TABLE [dbo].[TPROC_DIVISION] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DIVISION_NAME] varchar(50)  NOT NULL,
    [DIVISION_DESCRIPTION] varchar(100)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_DOCUMENTS'
CREATE TABLE [dbo].[TPROC_DOCUMENTS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FILE_NAME] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_FIELD_VALUES'
CREATE TABLE [dbo].[TPROC_FIELD_VALUES] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [APP_CD] varchar(5)  NOT NULL,
    [FLD_NM] varchar(30)  NOT NULL,
    [FLD_VALU] varchar(20)  NOT NULL,
    [FLD_VALU_DESC] varchar(120)  NULL,
    [FLD_VALU_DESC_ENG] varchar(120)  NULL,
    [SEQ_NUM] int  NULL,
    [FLD_VALU_MNE_CD] varchar(30)  NULL,
    [STAT_CD] varchar(1)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_FORM_SUB_TYPE'
CREATE TABLE [dbo].[TPROC_FORM_SUB_TYPE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [SUB_FORMTYPE_GR_ID] int  NOT NULL
);
GO

-- Creating table 'TPROC_FORM_SUBTYPE_DT'
CREATE TABLE [dbo].[TPROC_FORM_SUBTYPE_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [REL_DEPT_ID] int  NOT NULL,
    [FORM_SUBTYPE_GR_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [FLOW_INTEGER] int  NULL
);
GO

-- Creating table 'TPROC_FORM_SUBTYPE_GR'
CREATE TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [FORM_TYPE_ID] int  NULL,
    [SUB_FORM_TYPE_NAME] varchar(50)  NULL,
    [SUB_FORM_TYPE_DESCRIPTION] varchar(100)  NULL,
    [SLA] int  NULL,
    [POPUP_ACCOUNT] int  NULL,
    [BUDGET_CODE] varchar(50)  NULL,
    [ACCOUNT_CODE_START] varchar(20)  NULL,
    [ACCOUNT_CODE_END] varchar(20)  NULL,
    [REV_FST_ID] int  NULL
);
GO

-- Creating table 'TPROC_FORM_TYPE'
CREATE TABLE [dbo].[TPROC_FORM_TYPE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FORM_TYPE_NAME] varchar(50)  NOT NULL,
    [FORM_TYPE_DESCRIPTION] varchar(100)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [IS_GOOD_TYPE] int  NOT NULL
);
GO

-- Creating table 'TPROC_GENERATOR'
CREATE TABLE [dbo].[TPROC_GENERATOR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [TABLE_CODE] varchar(5)  NOT NULL,
    [TABLE_NAME] varchar(50)  NOT NULL,
    [LAST_SEQ_NO] int  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_GM_HEADERS'
CREATE TABLE [dbo].[TPROC_GM_HEADERS] (
    [ID] int  NOT NULL,
    [GM_INTEGER] varchar(20)  NOT NULL,
    [CREATE_DATETIME] datetime  NOT NULL,
    [PO_ID] int  NULL,
    [PREPARED_BY] varchar(8)  NULL,
    [APPOROVED_BY] varchar(8)  NULL,
    [NOTES] varchar(200)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [COMPLETED_BY] varchar(8)  NULL,
    [COMPLETED_DATETIME] datetime  NULL,
    [REJECTED_BY] varchar(8)  NULL,
    [REJECTED_TIME] datetime  NULL,
    [REJECTNOTE] varchar(200)  NULL,
    [HANDLED_BY] varchar(8)  NULL,
    [HANDLED_DATETIME] datetime  NULL
);
GO

-- Creating table 'TPROC_GOOD_TYPE'
CREATE TABLE [dbo].[TPROC_GOOD_TYPE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [GOOD_TYPE_NAME] varchar(50)  NOT NULL,
    [GOOD_TYPE_DESCRIPTION] varchar(100)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_HOLIDAY'
CREATE TABLE [dbo].[TPROC_HOLIDAY] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [HOLIDAY_DATE] datetime  NOT NULL,
    [HOLIDAY_DESCRIPTION] varchar(100)  NOT NULL,
    [CURR_YEAR] int  NOT NULL,
    [CURR_MONTH] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_LEVEL'
CREATE TABLE [dbo].[TPROC_LEVEL] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [INDONESIAN_LEVEL] varchar(50)  NOT NULL,
    [RUPIAH_LIMIT] int  NOT NULL,
    [CANADIAN_DOLLARS] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_LOG_TRANSACTIONS'
CREATE TABLE [dbo].[TPROC_LOG_TRANSACTIONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FORM] varchar(50)  NOT NULL,
    [TRANSACTION_DESCRIPTION] varchar(4000)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_MENU'
CREATE TABLE [dbo].[TPROC_MENU] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [MENU_NAME] varchar(50)  NOT NULL,
    [MENU_PARENT_ID] int  NULL,
    [MENU_DESCRIPTION] varchar(100)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_PC'
CREATE TABLE [dbo].[TPROC_PC] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_NUM] varchar(20)  NULL,
    [PO_TYPE_NM] varchar(20)  NOT NULL,
    [RECOM_SUPPLIER_NM] varchar(100)  NULL,
    [RECOM_SUPPLIER_ID] int  NOT NULL,
    [RECOM_SUPPLIER_CP] varchar(50)  NOT NULL,
    [RECOM_SUPPLIER_PHONE] varchar(100)  NOT NULL,
    [RECOM_SUPPLIER_FAX] varchar(50)  NULL,
    [RECOM_SUPPLIER_ADDRESS] varchar(200)  NOT NULL,
    [DELIVERY_NM] varchar(50)  NOT NULL,
    [DELIVERY_ID] int  NOT NULL,
    [DELIVERY_DATETIME] datetime  NOT NULL,
    [DELIVERY_PHONE] varchar(20)  NOT NULL,
    [DELIVERY_FAX] varchar(20)  NULL,
    [DELIVERY_ADDRESS] varchar(200)  NOT NULL,
    [GRAND_TOTAL] int  NOT NULL,
    [NOTE_BY_USER] varchar(200)  NULL,
    [NOTE_BY_EPROC] varchar(200)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [IS_DISC_PERC] int  NULL,
    [IS_VAT_PERC] int  NULL,
    [IS_PPH_PERC] int  NULL,
    [STATUS] varchar(200)  NULL,
    [NOTES] varchar(200)  NULL,
    [CURRENCY] varchar(200)  NULL,
    [IS_ACKNOWLEDGE_USER] int  NULL,
    [FOR_STORAGE] int  NULL,
    [FILE_NAMES] varchar(200)  NULL,
    [ADD_COST] int  NULL,
    [FINAL_TOTAL] int  NULL,
    [ADD_COST_DESC] varchar(200)  NULL,
    [REJECT_REASON] varchar(200)  NULL,
    [REJECT_BY] varchar(8)  NULL,
    [REJECT_DATETIME] datetime  NULL,
    [DELIVERY_DATE] datetime  NOT NULL,
    [FILE_NAME] varchar(200)  NULL,
    [REJECT_DATE] datetime  NULL
);
GO

-- Creating table 'TPROC_PC_DT'
CREATE TABLE [dbo].[TPROC_PC_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ITEM_NAME] varchar(100)  NOT NULL,
    [UNIT_MEASUREMENT] varchar(50)  NULL,
    [QUANTITY] int  NOT NULL,
    [PRICE] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [TOTAL] int  NULL,
    [ROW_NUM] int  NULL,
    [PC_ID] int  NULL
);
GO

-- Creating table 'TPROC_PC_HISTORICAL'
CREATE TABLE [dbo].[TPROC_PC_HISTORICAL] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_ID] int  NOT NULL,
    [HISTORICAL_DT] datetime  NOT NULL,
    [HISTORICAL_STATUS] varchar(50)  NOT NULL,
    [HISTORICAL_BY] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [QUEUE] int  NULL
);
GO

-- Creating table 'TPROC_PC_SP_DT'
CREATE TABLE [dbo].[TPROC_PC_SP_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_SP_GR_ID] int  NOT NULL,
    [PRICE_PER_PIECE] int  NOT NULL,
    [PRICE_TOTAL] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [PC_DT_ID] int  NULL
);
GO

-- Creating table 'TPROC_PC_SP_GR'
CREATE TABLE [dbo].[TPROC_PC_SP_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_ID] int  NOT NULL,
    [SUPP_ID] int  NOT NULL,
    [SUPP_NM] varchar(100)  NULL,
    [URL_ATTACHMENT] varchar(50)  NULL,
    [IS_USED] int  NULL,
    [COL_NUM] int  NOT NULL,
    [GRAND_TOTAL] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [DISCOUNT] int  NULL,
    [VAT] int  NULL,
    [PPH] int  NULL,
    [DISCOUNT_TEMP] int  NULL,
    [VAT_TEMP] int  NULL,
    [PPH_TEMP] int  NULL,
    [SUB_TOTAL] int  NULL,
    [DESCRIPTION] varchar(200)  NULL
);
GO

-- Creating table 'TPROC_PO_DETAILS'
CREATE TABLE [dbo].[TPROC_PO_DETAILS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PO_DTLS_ITEM_ID] int  NOT NULL,
    [ITEM_NAME] varchar(50)  NULL,
    [USERMEASUREMENT] varchar(5)  NULL,
    [QUANTITY] int  NULL,
    [PRICE] int  NULL,
    [TOTAL] int  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [FUND_T1] varchar(10)  NULL,
    [LOB1_T2] varchar(10)  NULL,
    [PLAN_T3] varchar(10)  NULL,
    [WA_T4] varchar(10)  NULL,
    [LOB2_T5] varchar(10)  NULL,
    [PR_HEADER_NO] varchar(50)  NOT NULL,
    [ITEM_ID] int  NULL
);
GO

-- Creating table 'TPROC_PO_DETAILS_ITEM'
CREATE TABLE [dbo].[TPROC_PO_DETAILS_ITEM] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PO_HEADER_ID] int  NOT NULL,
    [ITEM_NAME] varchar(100)  NULL,
    [PR_NO] varchar(50)  NULL,
    [UNITMEASUREMENT] varchar(50)  NULL,
    [QUANTITY] int  NULL,
    [PRICE] int  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [ITEM_ID] int  NULL
);
GO

-- Creating table 'TPROC_PO_HEADERS'
CREATE TABLE [dbo].[TPROC_PO_HEADERS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PO_INTEGER] varchar(20)  NOT NULL,
    [CREATE_DATETIME] datetime  NOT NULL,
    [PO_TYPE_ID] int  NULL,
    [CURRENCY] int  NULL,
    [PO_STATUS] int  NULL,
    [PREPARED_BY] varchar(8)  NULL,
    [APPOROVED_BY] varchar(8)  NULL,
    [APPOROVED_DATETIME] datetime  NULL,
    [NOTES] varchar(200)  NULL,
    [SUPPLIER_NAME] varchar(100)  NULL,
    [SUPPLIER_ID] int  NULL,
    [CONTACT_PERSON] varchar(50)  NULL,
    [SUPPLIER_PHONE] varchar(100)  NULL,
    [SUPPLIER_FAX] varchar(50)  NULL,
    [SUPPLIER_ADDTRSS] varchar(200)  NULL,
    [DELIVERY_NAME] varchar(50)  NULL,
    [DELIVERY_ID] int  NULL,
    [DELIVERY_DATETIME] datetime  NULL,
    [DELIVERY_PHONE] varchar(20)  NULL,
    [DELIVERY_FAX] varchar(20)  NULL,
    [DELIVERY_ADDRESS] varchar(100)  NULL,
    [SUB_TOTAL] int  NULL,
    [DSCNT_AMT] int  NULL,
    [VAT] int  NULL,
    [WTH_TAX] int  NULL,
    [GRAND_TOTAL] int  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [REVIEWED_BY] varchar(8)  NULL,
    [REVIEWED_DATETIME] datetime  NULL,
    [COMPLETED_BY] varchar(8)  NULL,
    [COMPLETED_DATETIME] datetime  NULL,
    [PC_ID] int  NULL,
    [FOR_STORAGE] int  NULL,
    [IS_DISC_PERC] int  NULL,
    [IS_VAT_PERC] int  NULL,
    [IS_PPH_PERC] int  NULL,
    [DISCOUNT_TEMP] int  NULL,
    [VAT_TEMP] int  NULL,
    [PPH_TEMP] int  NULL,
    [FILE_NAME] varchar(200)  NULL,
    [VERIFIED_BY] varchar(8)  NULL,
    [VERIFIED_DATETIME] datetime  NULL,
    [ADD_COST] int  NULL,
    [FINAL_TOTAL] int  NULL,
    [ADD_COST_DESC] varchar(200)  NULL,
    [REJECT_REASON] varchar(200)  NULL,
    [REJECT_BY] varchar(8)  NULL,
    [REJECT_DATETIME] datetime  NULL,
    [PO_NUMBER] varchar(20)  NOT NULL,
    [CREATE_DATE] datetime  NOT NULL,
    [APPOROVED_DATE] datetime  NULL,
    [DELIVERY_DATE] datetime  NULL,
    [REVIEWED_DATE] datetime  NULL,
    [COMPLETED_DATE] datetime  NULL,
    [VERIFIED_DATE] datetime  NULL,
    [REJECT_DATE] datetime  NULL
);
GO

-- Creating table 'TPROC_PO_TYPE'
CREATE TABLE [dbo].[TPROC_PO_TYPE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PO_TYPE_NAME] varchar(5)  NOT NULL,
    [PO_TYPE_DESCRIPTION] varchar(100)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [FORM_TYPE_ID] int  NOT NULL
);
GO

-- Creating table 'TPROC_PPH'
CREATE TABLE [dbo].[TPROC_PPH] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PPH_NAME] int  NOT NULL,
    [START_DATETIME] datetime  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_PR_APPR_RELDEPT_DT'
CREATE TABLE [dbo].[TPROC_PR_APPR_RELDEPT_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PR_APPR_RELDEPT_GR_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [NAME] varchar(50)  NULL,
    [APPR_RELDEPT_STATUS] varchar(50)  NOT NULL,
    [EMAIL] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_PR_APPR_RELDEPT_GR'
CREATE TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PR_HEADER_ID] int  NOT NULL,
    [RELDEPT_NAME] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [RELDEPT_GR_STATUS] varchar(50)  NULL,
    [REJECT_REASON] varchar(400)  NULL
);
GO

-- Creating table 'TPROC_PR_APPR_WA'
CREATE TABLE [dbo].[TPROC_PR_APPR_WA] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PR_DETAIL_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [NAME] varchar(50)  NULL,
    [APPR_WA_STATUS] varchar(50)  NOT NULL,
    [EMAIL] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_PR_ATTACHMENT'
CREATE TABLE [dbo].[TPROC_PR_ATTACHMENT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PR_HEADER_ID] int  NOT NULL,
    [FILE_NAME] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_PR_DETAIL'
CREATE TABLE [dbo].[TPROC_PR_DETAIL] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PR_HEADER_ID] int  NOT NULL,
    [ITEM_NAME] varchar(50)  NOT NULL,
    [SPECIFICATION] varchar(100)  NULL,
    [CURRENCY] varchar(10)  NOT NULL,
    [QTY] int  NOT NULL,
    [USER_MEASUREMENT] varchar(5)  NULL,
    [WA_ID] int  NOT NULL,
    [REVISED_QTY] int  NULL,
    [PRICE] int  NOT NULL,
    [TOTAL_PRICE] int  NOT NULL,
    [REMARK] varchar(200)  NULL,
    [SUPPLIER_NAME] varchar(200)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [PR_DETAIL_STATUS] int  NOT NULL,
    [REJECT_REASON] varchar(400)  NULL,
    [ITEM_CD] varchar(50)  NULL,
    [CONVERSION_RP] int  NULL,
    [PO_INTEGER] varchar(20)  NULL,
    [SUPPLIER_ID] int  NULL,
    [EVALUATED_SUPPLIER] int  NULL,
    [ITEM_ID] int  NULL,
    [WA_INTEGER] int  NULL,
    [WA_INTEGER_ACC] int  NULL
);
GO

-- Creating table 'TPROC_PR_HEADER'
CREATE TABLE [dbo].[TPROC_PR_HEADER] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PR_NO] varchar(50)  NOT NULL,
    [USER_ID_ID] int  NOT NULL,
    [PR_DATETIME] datetime  NOT NULL,
    [FORM_TYPE_ID] int  NOT NULL,
    [SUB_TYPE_ID] int  NOT NULL,
    [GOOD_TYPE_ID] int  NOT NULL,
    [DELIVERY_DAYS] int  NOT NULL,
    [EXP_DEV_DT] datetime  NOT NULL,
    [PR_INDICATOR] varchar(20)  NOT NULL,
    [ACCOUNT_CODE] varchar(8)  NULL,
    [PR_STATUS] int  NOT NULL,
    [SUB_TOTAL] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [COMP_CD] int  NOT NULL,
    [FOR_STORAGE] int  NULL,
    [PR_DATE] datetime  NOT NULL,
    [REJECT_REASON] varchar(200)  NULL
);
GO

-- Creating table 'TPROC_REL_DEPT'
CREATE TABLE [dbo].[TPROC_REL_DEPT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [RELATED_DEPARTMENT_NAME] varchar(50)  NOT NULL,
    [APPROVAL_RELDEPT_GR_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_REQUEST'
CREATE TABLE [dbo].[TPROC_REQUEST] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [REQUEST_NO] varchar(50)  NOT NULL,
    [RELATION_FLAG] varchar(50)  NOT NULL,
    [REQUEST_BY] varchar(50)  NOT NULL,
    [REQUEST_DT] datetime  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [STATUS] int  NULL,
    [DESCRIPTION] varchar(200)  NULL,
    [CONTROL] varchar(50)  NULL,
    [ACTION] varchar(50)  NULL,
    [REQUESTOR_EMAIL] varchar(100)  NULL,
    [APPROVAL_BY] varchar(50)  NULL,
    [APPROVAL_EMAIL] varchar(100)  NULL,
    [APPROVED_TIME] datetime  NULL
);
GO

-- Creating table 'TPROC_ROLE'
CREATE TABLE [dbo].[TPROC_ROLE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ROLE_NAME] varchar(50)  NOT NULL,
    [ROLE_DESCRIPTION] varchar(100)  NOT NULL,
    [IS_ACTIVE] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [DEFAULT_SELECTED] int  NULL
);
GO

-- Creating table 'TPROC_ROLE_MENU'
CREATE TABLE [dbo].[TPROC_ROLE_MENU] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ROLE_ID] int  NOT NULL,
    [MENU_ID] int  NOT NULL,
    [IS_ACCESS] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_STOCK'
CREATE TABLE [dbo].[TPROC_STOCK] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ITEM_CODE] varchar(10)  NOT NULL,
    [ITEM_DESCRIPTION] varchar(100)  NOT NULL,
    [LOOKUP_CODE] varchar(50)  NULL,
    [UNIT_OF_STOCK] varchar(10)  NULL,
    [LATEST_COST] int  NOT NULL,
    [AVERAGE_COST] int  NOT NULL,
    [PURCHASE_ACCOUNT] varchar(8)  NOT NULL,
    [STOCK_EXPENSES] varchar(8)  NOT NULL,
    [GOOD_TYPE_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [SUPPLIER_ID] int  NULL,
    [QUANTITY] int  NULL,
    [FORM_TYPE_ID] int  NULL,
    [QUANTITY_MIN] int  NULL
);
GO

-- Creating table 'TPROC_SUPP_DOC'
CREATE TABLE [dbo].[TPROC_SUPP_DOC] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [SUPPLIER_ID] int  NOT NULL,
    [WEIGHT_FACTOR] int  NULL,
    [BRIDGER_SCAN] int  NULL,
    [NDA] int  NULL,
    [CIDCI] int  NULL,
    [LEGAL_DOC] int  NULL,
    [AGGREEMENT] int  NULL,
    [VALIDITY_CHECKING] int  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_SUPP_EVAL'
CREATE TABLE [dbo].[TPROC_SUPP_EVAL] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [SUPPLIER_ID] int  NOT NULL,
    [F_STM] int  NULL,
    [F_KM] int  NULL,
    [F_M] int  NULL,
    [F_SM] int  NULL,
    [F_KET] varchar(200)  NULL,
    [A_TA] int  NULL,
    [A_TRK] int  NULL,
    [A_RK] int  NULL,
    [A_KET] varchar(200)  NULL,
    [H_TK] int  NULL,
    [H_K] int  NULL,
    [H_SK] int  NULL,
    [H_KET] varchar(200)  NULL,
    [PO_LP] int  NULL,
    [PO_LTA] int  NULL,
    [PO_CA] int  NULL,
    [PO_KET] varchar(200)  NULL,
    [P_STTW] int  NULL,
    [P_KTTW] int  NULL,
    [P_TW] int  NULL,
    [P_KET] varchar(200)  NULL,
    [HP_STSP] int  NULL,
    [HP_KTSP] int  NULL,
    [HP_SP] int  NULL,
    [HP_KET] varchar(200)  NULL,
    [IS_RECOMMENDED] int  NULL,
    [TOTAL_SCORE] int  NULL,
    [DISIAPKAN_OLEH] varchar(200)  NULL,
    [DISETUJUI_OLEH] varchar(200)  NULL,
    [KOMENTAR_SARAN] varchar(200)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [PR_HEADER_ID] int  NULL
);
GO

-- Creating table 'TPROC_SUPP_QUAL'
CREATE TABLE [dbo].[TPROC_SUPP_QUAL] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [SUPPLIER_ID] int  NOT NULL,
    [H_STK] int  NULL,
    [H_TK] int  NULL,
    [H_K] int  NULL,
    [H_SK] int  NULL,
    [H_KET] varchar(200)  NULL,
    [A_TA] int  NULL,
    [A_TRK] int  NULL,
    [A_RK] int  NULL,
    [A_KET] varchar(200)  NULL,
    [F_STM] int  NULL,
    [F_KM] int  NULL,
    [F_M] int  NULL,
    [F_SM] int  NULL,
    [F_KET] varchar(200)  NULL,
    [P_LP] int  NULL,
    [P_LTA] int  NULL,
    [P_CA] int  NULL,
    [P_KET] varchar(200)  NULL,
    [Q_TA] int  NULL,
    [Q_CS] int  NULL,
    [Q_HHA] int  NULL,
    [Q_SLP] int  NULL,
    [Q_KET] varchar(200)  NULL,
    [TOTAL_SCORE] int  NULL,
    [DIBUAT_OLEH] varchar(200)  NULL,
    [DIPERIKSA_OLEH] varchar(200)  NULL,
    [DISETUJUI_OLEH] varchar(200)  NULL,
    [KOMENTAR_SARAN] varchar(200)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_SUPPLIER'
CREATE TABLE [dbo].[TPROC_SUPPLIER] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [SUPPLIER_NAME] varchar(100)  NOT NULL,
    [SUPPLIER_ALIAS_NAME] varchar(50)  NULL,
    [SUPPLIER_ADDRESS] varchar(200)  NULL,
    [VENDOR_CODE] varchar(50)  NOT NULL,
    [BANK_NAME] varchar(50)  NULL,
    [BANK_BRANCH] varchar(50)  NULL,
    [BANK_ACCOUNT_INTEGER] varchar(50)  NULL,
    [CONTACT_PERSON] varchar(50)  NOT NULL,
    [EMAIL_ADDRESS] varchar(50)  NULL,
    [MOBILE_INTEGER] varchar(100)  NULL,
    [OFFICE_INTEGER] varchar(50)  NULL,
    [FAX_INTEGER] varchar(50)  NULL,
    [TAX_INTEGER] varchar(50)  NULL,
    [WEBSITE] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [NPWP] varchar(50)  NULL,
    [DESCRIPTION] varchar(200)  NULL,
    [CORE_BUSINESS] varchar(200)  NULL,
    [NAMA_BARANG] varchar(100)  NULL,
    [B_UNIT_OWNER] varchar(50)  NULL,
    [CITY] varchar(100)  NULL,
    [EFFECTIVE_DATETIME] varchar(20)  NULL,
    [SCHEDULE_EVALUATION] varchar(20)  NULL,
    [BANK_ACCOUNT_NUMBER] varchar(50)  NULL,
    [MOBILE_NUMBER] varchar(100)  NULL,
    [OFFICE_NUMBER] varchar(50)  NULL,
    [FAX_NUMBER] varchar(50)  NULL,
    [TAX_NUMBER] varchar(50)  NULL,
    [EFFECTIVE_DATE] varchar(20)  NULL
);
GO

-- Creating table 'TPROC_USER'
CREATE TABLE [dbo].[TPROC_USER] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [USER_MAIL] varchar(100)  NOT NULL,
    [USER_NAME] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [USER_DT_ID] int  NOT NULL,
    [LAST_LOGIN] datetime  NULL
);
GO

-- Creating table 'TPROC_USER_DT'
CREATE TABLE [dbo].[TPROC_USER_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [WA_ALLOWED_GR_ID] int  NOT NULL,
    [ROLE_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [DIVISION_ID] int  NULL,
    [COMP_CD] int  NULL,
    [REV_USER_ID] int  NULL,
    [IS_EPROC_ADMIN] int  NULL,
    [IS_SUPER_ADMIN] int  NULL
);
GO

-- Creating table 'TPROC_USER_PROFILE'
CREATE TABLE [dbo].[TPROC_USER_PROFILE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [USER_ID_ID] int  NOT NULL,
    [PHOTO] varbinary(1)  NULL,
    [GENDER] char(1)  NULL,
    [BORN] datetime  NULL,
    [ADDRESS] varchar(100)  NULL,
    [DESCRIPTION] varchar(100)  NULL,
    [JOB] varchar(100)  NULL,
    [COMPANY] varchar(100)  NULL,
    [HOBBY] varchar(100)  NULL,
    [EMAIL] varchar(100)  NULL,
    [FACEBOOK] varchar(100)  NULL,
    [TWITTER] varchar(100)  NULL,
    [IG] varchar(100)  NULL,
    [PATH] varchar(100)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_VAT'
CREATE TABLE [dbo].[TPROC_VAT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [VAT_NAME] int  NOT NULL,
    [START_DATETIME] datetime  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [START_DATE] datetime  NOT NULL
);
GO

-- Creating table 'TPROC_VRF_PC'
CREATE TABLE [dbo].[TPROC_VRF_PC] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PC_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [NAME] varchar(50)  NOT NULL,
    [EMAIL] varchar(100)  NOT NULL,
    [AS_IS] varchar(20)  NULL,
    [STATUS] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [REMARK] varchar(200)  NULL
);
GO

-- Creating table 'TPROC_VRF_PO'
CREATE TABLE [dbo].[TPROC_VRF_PO] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PO_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [NAME] varchar(50)  NOT NULL,
    [EMAIL] varchar(100)  NOT NULL,
    [AS_IS] varchar(20)  NULL,
    [STATUS] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [REMARK] varchar(200)  NULL
);
GO

-- Creating table 'TPROC_WA'
CREATE TABLE [dbo].[TPROC_WA] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [WA_INTEGER] int  NOT NULL,
    [APPROVAL_GROUP_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [WA_NUMBER] int  NOT NULL
);
GO

-- Creating table 'TPROC_WA_ALLOWED_DT'
CREATE TABLE [dbo].[TPROC_WA_ALLOWED_DT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [WA_ALLOWED_GROUP_ID] int  NOT NULL,
    [WORK_AREA_ID] int  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_WA_ALLOWED_GR'
CREATE TABLE [dbo].[TPROC_WA_ALLOWED_GR] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_ACKNOW_APPR_DT'
CREATE TABLE [dbo].[TPROC_ACKNOW_APPR_DT] (
    [ID] int  NOT NULL,
    [ACKNOW_APPR_ID] int  NOT NULL,
    [USER_ID] varchar(50)  NOT NULL,
    [USER_NAME] varchar(50)  NOT NULL,
    [USER_EMAIL] varchar(50)  NOT NULL,
    [STATUS] varchar(50)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- Creating table 'TPROC_APPROVAL_ROLE_DETAIL'
CREATE TABLE [dbo].[TPROC_APPROVAL_ROLE_DETAIL] (
    [ID] int  NOT NULL,
    [ID_APPROVAL_ROLE] int  NOT NULL,
    [ROLE_NAME] varchar(100)  NOT NULL,
    [AS_IS] varchar(20)  NULL
);
GO

-- Creating table 'TPROC_CONTROL_PARAMETERS'
CREATE TABLE [dbo].[TPROC_CONTROL_PARAMETERS] (
    [TERR_CD] varchar(5)  NOT NULL,
    [PARM_TYP] varchar(30)  NOT NULL,
    [STATE_CD] varchar(2)  NOT NULL,
    [PARM_VALU] varchar(100)  NULL,
    [PARM_DESC] varchar(100)  NOT NULL,
    [DATA_TYP] varchar(1)  NOT NULL,
    [CREATED_BY] varchar(30)  NOT NULL
);
GO

-- Creating table 'TPROC_CRV'
CREATE TABLE [dbo].[TPROC_CRV] (
    [ID] int  NOT NULL,
    [PO_ID] int  NULL,
    [CRV_NUM] varchar(20)  NOT NULL,
    [BANK_ACCOUNT_INTEGER] varchar(50)  NOT NULL,
    [BANK_NAME] varchar(50)  NULL,
    [CREATED_TIME] datetime  NULL,
    [CREATED_BY] varchar(50)  NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NULL,
    [SUB_TOTAL] int  NULL,
    [DSCNT_AMT] int  NULL,
    [VAT] int  NULL,
    [WTH_TAX] int  NULL,
    [GRAND_TOTAL] int  NULL,
    [RECEIVED_BY] varchar(8)  NULL,
    [RECEIVED_DATETIME] datetime  NULL,
    [COMPLETED_BY] varchar(8)  NULL,
    [COMPLETED_DATETIME] datetime  NULL,
    [SUPPLIER_ID] int  NULL,
    [BANK_BRANCH] varchar(50)  NULL,
    [REFTAXNO] varchar(50)  NULL,
    [PAYMENTMETHOD] varchar(50)  NULL,
    [KLIRINGNO] varchar(50)  NULL,
    [VERIFY_BY] varchar(8)  NULL,
    [VERIFY_TIME] datetime  NULL,
    [REJECTNOTE] varchar(200)  NULL,
    [REJECTED_BY] varchar(8)  NULL,
    [REJECTED_TIME] datetime  NULL,
    [APPROVE_BY] varchar(8)  NULL,
    [APPROVE_DATETIME] datetime  NULL,
    [FILEPATH] varchar(200)  NULL
);
GO

-- Creating table 'TPROC_CRV_DETAILS'
CREATE TABLE [dbo].[TPROC_CRV_DETAILS] (
    [ID] int  NOT NULL,
    [CRV_HEADER_ID] int  NOT NULL,
    [ITEM_ID] int  NULL,
    [ITEM_NAME] varchar(100)  NULL,
    [UNITMEASUREMENT] varchar(50)  NULL,
    [QUANTITY] int  NULL,
    [PRICE] int  NULL,
    [SUBTOTAL] int  NULL,
    [FUND_T1] varchar(10)  NULL,
    [LOB1_T2] varchar(10)  NULL,
    [PLAN_T3] varchar(10)  NULL,
    [WA_T4] varchar(10)  NULL,
    [LOB2_T5] varchar(10)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [CURRENCY] int  NULL,
    [ACCOUNT_CODE] varchar(8)  NULL
);
GO

-- Creating table 'TPROC_FIELD_DESCRIPTIONS'
CREATE TABLE [dbo].[TPROC_FIELD_DESCRIPTIONS] (
    [APP_CD] varchar(5)  NOT NULL,
    [FLD_NM] varchar(30)  NOT NULL,
    [FLD_NM_DESC] varchar(100)  NOT NULL,
    [DATA_TYP] varchar(1)  NOT NULL,
    [DFLT_VALU] varchar(30)  NULL,
    [USER_MODIFY_IND] varchar(1)  NULL
);
GO

-- Creating table 'TPROC_GM_DETAILS'
CREATE TABLE [dbo].[TPROC_GM_DETAILS] (
    [ID] int  NOT NULL,
    [ITEM_ID] int  NULL,
    [ITEM_NAME] varchar(100)  NULL,
    [UNITMEASUREMENT] varchar(50)  NULL,
    [QUANTITY] int  NULL,
    [PRICE] int  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [GM_ID] int  NOT NULL
);
GO

-- Creating table 'TPROC_PARAMETERS'
CREATE TABLE [dbo].[TPROC_PARAMETERS] (
    [PARAMETER_CODE] varchar(50)  NOT NULL,
    [PARAMETER_NAME] varchar(100)  NOT NULL,
    [PARAMETER_DESCRIPTION] varchar(200)  NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [PARAMETER_VALUE] varchar(100)  NULL
);
GO

-- Creating table 'TPROC_PR_HISTORICAL'
CREATE TABLE [dbo].[TPROC_PR_HISTORICAL] (
    [ID] int  NOT NULL,
    [PR_HEADER_ID] int  NOT NULL,
    [HISTORICAL_DT] datetime  NOT NULL,
    [HISTORICAL_STATUS] varchar(20)  NOT NULL,
    [HISTORICAL_BY] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL,
    [QUEUE] int  NULL
);
GO

-- Creating table 'TPROC_STOCKMOVEMENT'
CREATE TABLE [dbo].[TPROC_STOCKMOVEMENT] (
    [ID] int  NOT NULL,
    [ITEM_ID] int  NULL,
    [REFNO] varchar(20)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [STOCK_CURRENT] int  NULL,
    [STOCK_IN] int  NULL,
    [STOCK_OUT] int  NULL,
    [STOCK_LAST] int  NULL,
    [LATEST_COST] int  NOT NULL,
    [AVERAGE_COST] int  NOT NULL,
    [ID_TEMP] int  NULL
);
GO

-- Creating table 'TPROC_FST_BUDGET_CD_ADD'
CREATE TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FORM_SUBTYPE_GR_ID] int  NOT NULL,
    [BUDGET_CODE] varchar(50)  NOT NULL,
    [ACCOUNT_CODE_START] varchar(100)  NOT NULL,
    [ACCOUNT_CODE_END] varchar(50)  NOT NULL,
    [CREATED_TIME] datetime  NOT NULL,
    [CREATED_BY] varchar(50)  NOT NULL,
    [LAST_MODIFIED_TIME] datetime  NULL,
    [LAST_MODIFIED_BY] varchar(50)  NULL,
    [ROW_STATUS] int  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID] in table 'MenuSidebars'
ALTER TABLE [dbo].[MenuSidebars]
ADD CONSTRAINT [PK_MenuSidebars]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_ACKNOW_APPR'
ALTER TABLE [dbo].[TPROC_ACKNOW_APPR]
ADD CONSTRAINT [PK_TPROC_ACKNOW_APPR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPR_PC'
ALTER TABLE [dbo].[TPROC_APPR_PC]
ADD CONSTRAINT [PK_TPROC_APPR_PC]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPR_PO'
ALTER TABLE [dbo].[TPROC_APPR_PO]
ADD CONSTRAINT [PK_TPROC_APPR_PO]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPR_RELDEPT_DT'
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT]
ADD CONSTRAINT [PK_TPROC_APPR_RELDEPT_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPR_RELDEPT_GR'
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_GR]
ADD CONSTRAINT [PK_TPROC_APPR_RELDEPT_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPROVAL_DT'
ALTER TABLE [dbo].[TPROC_APPROVAL_DT]
ADD CONSTRAINT [PK_TPROC_APPROVAL_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPROVAL_GR'
ALTER TABLE [dbo].[TPROC_APPROVAL_GR]
ADD CONSTRAINT [PK_TPROC_APPROVAL_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_APPROVAL_ROLE'
ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE]
ADD CONSTRAINT [PK_TPROC_APPROVAL_ROLE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_BUDGET_CODE'
ALTER TABLE [dbo].[TPROC_BUDGET_CODE]
ADD CONSTRAINT [PK_TPROC_BUDGET_CODE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_CHART_OF_ACCOUNT_GR'
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR]
ADD CONSTRAINT [PK_TPROC_CHART_OF_ACCOUNT_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_CHART_OF_ACCOUNTS'
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS]
ADD CONSTRAINT [PK_TPROC_CHART_OF_ACCOUNTS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_CURRENCY'
ALTER TABLE [dbo].[TPROC_CURRENCY]
ADD CONSTRAINT [PK_TPROC_CURRENCY]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_DELIVERY_ADDRESS'
ALTER TABLE [dbo].[TPROC_DELIVERY_ADDRESS]
ADD CONSTRAINT [PK_TPROC_DELIVERY_ADDRESS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_DIVISION'
ALTER TABLE [dbo].[TPROC_DIVISION]
ADD CONSTRAINT [PK_TPROC_DIVISION]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_DOCUMENTS'
ALTER TABLE [dbo].[TPROC_DOCUMENTS]
ADD CONSTRAINT [PK_TPROC_DOCUMENTS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_FIELD_VALUES'
ALTER TABLE [dbo].[TPROC_FIELD_VALUES]
ADD CONSTRAINT [PK_TPROC_FIELD_VALUES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_FORM_SUB_TYPE'
ALTER TABLE [dbo].[TPROC_FORM_SUB_TYPE]
ADD CONSTRAINT [PK_TPROC_FORM_SUB_TYPE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_FORM_SUBTYPE_DT'
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_DT]
ADD CONSTRAINT [PK_TPROC_FORM_SUBTYPE_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_FORM_SUBTYPE_GR'
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR]
ADD CONSTRAINT [PK_TPROC_FORM_SUBTYPE_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_FORM_TYPE'
ALTER TABLE [dbo].[TPROC_FORM_TYPE]
ADD CONSTRAINT [PK_TPROC_FORM_TYPE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_GENERATOR'
ALTER TABLE [dbo].[TPROC_GENERATOR]
ADD CONSTRAINT [PK_TPROC_GENERATOR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_GM_HEADERS'
ALTER TABLE [dbo].[TPROC_GM_HEADERS]
ADD CONSTRAINT [PK_TPROC_GM_HEADERS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_GOOD_TYPE'
ALTER TABLE [dbo].[TPROC_GOOD_TYPE]
ADD CONSTRAINT [PK_TPROC_GOOD_TYPE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_HOLIDAY'
ALTER TABLE [dbo].[TPROC_HOLIDAY]
ADD CONSTRAINT [PK_TPROC_HOLIDAY]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_LEVEL'
ALTER TABLE [dbo].[TPROC_LEVEL]
ADD CONSTRAINT [PK_TPROC_LEVEL]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_LOG_TRANSACTIONS'
ALTER TABLE [dbo].[TPROC_LOG_TRANSACTIONS]
ADD CONSTRAINT [PK_TPROC_LOG_TRANSACTIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_MENU'
ALTER TABLE [dbo].[TPROC_MENU]
ADD CONSTRAINT [PK_TPROC_MENU]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PC'
ALTER TABLE [dbo].[TPROC_PC]
ADD CONSTRAINT [PK_TPROC_PC]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PC_DT'
ALTER TABLE [dbo].[TPROC_PC_DT]
ADD CONSTRAINT [PK_TPROC_PC_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PC_HISTORICAL'
ALTER TABLE [dbo].[TPROC_PC_HISTORICAL]
ADD CONSTRAINT [PK_TPROC_PC_HISTORICAL]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PC_SP_DT'
ALTER TABLE [dbo].[TPROC_PC_SP_DT]
ADD CONSTRAINT [PK_TPROC_PC_SP_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PC_SP_GR'
ALTER TABLE [dbo].[TPROC_PC_SP_GR]
ADD CONSTRAINT [PK_TPROC_PC_SP_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PO_DETAILS'
ALTER TABLE [dbo].[TPROC_PO_DETAILS]
ADD CONSTRAINT [PK_TPROC_PO_DETAILS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PO_DETAILS_ITEM'
ALTER TABLE [dbo].[TPROC_PO_DETAILS_ITEM]
ADD CONSTRAINT [PK_TPROC_PO_DETAILS_ITEM]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PO_HEADERS'
ALTER TABLE [dbo].[TPROC_PO_HEADERS]
ADD CONSTRAINT [PK_TPROC_PO_HEADERS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PO_TYPE'
ALTER TABLE [dbo].[TPROC_PO_TYPE]
ADD CONSTRAINT [PK_TPROC_PO_TYPE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PPH'
ALTER TABLE [dbo].[TPROC_PPH]
ADD CONSTRAINT [PK_TPROC_PPH]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PR_APPR_RELDEPT_DT'
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_DT]
ADD CONSTRAINT [PK_TPROC_PR_APPR_RELDEPT_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PR_APPR_RELDEPT_GR'
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR]
ADD CONSTRAINT [PK_TPROC_PR_APPR_RELDEPT_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PR_APPR_WA'
ALTER TABLE [dbo].[TPROC_PR_APPR_WA]
ADD CONSTRAINT [PK_TPROC_PR_APPR_WA]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PR_ATTACHMENT'
ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT]
ADD CONSTRAINT [PK_TPROC_PR_ATTACHMENT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PR_DETAIL'
ALTER TABLE [dbo].[TPROC_PR_DETAIL]
ADD CONSTRAINT [PK_TPROC_PR_DETAIL]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_PR_HEADER'
ALTER TABLE [dbo].[TPROC_PR_HEADER]
ADD CONSTRAINT [PK_TPROC_PR_HEADER]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_REL_DEPT'
ALTER TABLE [dbo].[TPROC_REL_DEPT]
ADD CONSTRAINT [PK_TPROC_REL_DEPT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_REQUEST'
ALTER TABLE [dbo].[TPROC_REQUEST]
ADD CONSTRAINT [PK_TPROC_REQUEST]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_ROLE'
ALTER TABLE [dbo].[TPROC_ROLE]
ADD CONSTRAINT [PK_TPROC_ROLE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_ROLE_MENU'
ALTER TABLE [dbo].[TPROC_ROLE_MENU]
ADD CONSTRAINT [PK_TPROC_ROLE_MENU]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_STOCK'
ALTER TABLE [dbo].[TPROC_STOCK]
ADD CONSTRAINT [PK_TPROC_STOCK]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_SUPP_DOC'
ALTER TABLE [dbo].[TPROC_SUPP_DOC]
ADD CONSTRAINT [PK_TPROC_SUPP_DOC]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_SUPP_EVAL'
ALTER TABLE [dbo].[TPROC_SUPP_EVAL]
ADD CONSTRAINT [PK_TPROC_SUPP_EVAL]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_SUPP_QUAL'
ALTER TABLE [dbo].[TPROC_SUPP_QUAL]
ADD CONSTRAINT [PK_TPROC_SUPP_QUAL]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_SUPPLIER'
ALTER TABLE [dbo].[TPROC_SUPPLIER]
ADD CONSTRAINT [PK_TPROC_SUPPLIER]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_USER'
ALTER TABLE [dbo].[TPROC_USER]
ADD CONSTRAINT [PK_TPROC_USER]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_USER_DT'
ALTER TABLE [dbo].[TPROC_USER_DT]
ADD CONSTRAINT [PK_TPROC_USER_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_USER_PROFILE'
ALTER TABLE [dbo].[TPROC_USER_PROFILE]
ADD CONSTRAINT [PK_TPROC_USER_PROFILE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_VAT'
ALTER TABLE [dbo].[TPROC_VAT]
ADD CONSTRAINT [PK_TPROC_VAT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_VRF_PC'
ALTER TABLE [dbo].[TPROC_VRF_PC]
ADD CONSTRAINT [PK_TPROC_VRF_PC]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_VRF_PO'
ALTER TABLE [dbo].[TPROC_VRF_PO]
ADD CONSTRAINT [PK_TPROC_VRF_PO]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_WA'
ALTER TABLE [dbo].[TPROC_WA]
ADD CONSTRAINT [PK_TPROC_WA]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_WA_ALLOWED_DT'
ALTER TABLE [dbo].[TPROC_WA_ALLOWED_DT]
ADD CONSTRAINT [PK_TPROC_WA_ALLOWED_DT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_WA_ALLOWED_GR'
ALTER TABLE [dbo].[TPROC_WA_ALLOWED_GR]
ADD CONSTRAINT [PK_TPROC_WA_ALLOWED_GR]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID], [ACKNOW_APPR_ID], [USER_ID], [USER_NAME], [USER_EMAIL], [CREATED_TIME], [CREATED_BY], [ROW_STATUS] in table 'TPROC_ACKNOW_APPR_DT'
ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT]
ADD CONSTRAINT [PK_TPROC_ACKNOW_APPR_DT]
    PRIMARY KEY CLUSTERED ([ID], [ACKNOW_APPR_ID], [USER_ID], [USER_NAME], [USER_EMAIL], [CREATED_TIME], [CREATED_BY], [ROW_STATUS] ASC);
GO

-- Creating primary key on [ID], [ID_APPROVAL_ROLE], [ROLE_NAME] in table 'TPROC_APPROVAL_ROLE_DETAIL'
ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE_DETAIL]
ADD CONSTRAINT [PK_TPROC_APPROVAL_ROLE_DETAIL]
    PRIMARY KEY CLUSTERED ([ID], [ID_APPROVAL_ROLE], [ROLE_NAME] ASC);
GO

-- Creating primary key on [TERR_CD], [PARM_TYP], [STATE_CD], [PARM_DESC], [DATA_TYP], [CREATED_BY] in table 'TPROC_CONTROL_PARAMETERS'
ALTER TABLE [dbo].[TPROC_CONTROL_PARAMETERS]
ADD CONSTRAINT [PK_TPROC_CONTROL_PARAMETERS]
    PRIMARY KEY CLUSTERED ([TERR_CD], [PARM_TYP], [STATE_CD], [PARM_DESC], [DATA_TYP], [CREATED_BY] ASC);
GO

-- Creating primary key on [ID], [CRV_NUM], [BANK_ACCOUNT_INTEGER] in table 'TPROC_CRV'
ALTER TABLE [dbo].[TPROC_CRV]
ADD CONSTRAINT [PK_TPROC_CRV]
    PRIMARY KEY CLUSTERED ([ID], [CRV_NUM], [BANK_ACCOUNT_INTEGER] ASC);
GO

-- Creating primary key on [ID], [CRV_HEADER_ID], [CREATED_TIME], [CREATED_BY], [ROW_STATUS] in table 'TPROC_CRV_DETAILS'
ALTER TABLE [dbo].[TPROC_CRV_DETAILS]
ADD CONSTRAINT [PK_TPROC_CRV_DETAILS]
    PRIMARY KEY CLUSTERED ([ID], [CRV_HEADER_ID], [CREATED_TIME], [CREATED_BY], [ROW_STATUS] ASC);
GO

-- Creating primary key on [APP_CD], [FLD_NM], [FLD_NM_DESC], [DATA_TYP] in table 'TPROC_FIELD_DESCRIPTIONS'
ALTER TABLE [dbo].[TPROC_FIELD_DESCRIPTIONS]
ADD CONSTRAINT [PK_TPROC_FIELD_DESCRIPTIONS]
    PRIMARY KEY CLUSTERED ([APP_CD], [FLD_NM], [FLD_NM_DESC], [DATA_TYP] ASC);
GO

-- Creating primary key on [ID], [CREATED_TIME], [CREATED_BY], [ROW_STATUS], [GM_ID] in table 'TPROC_GM_DETAILS'
ALTER TABLE [dbo].[TPROC_GM_DETAILS]
ADD CONSTRAINT [PK_TPROC_GM_DETAILS]
    PRIMARY KEY CLUSTERED ([ID], [CREATED_TIME], [CREATED_BY], [ROW_STATUS], [GM_ID] ASC);
GO

-- Creating primary key on [PARAMETER_CODE], [PARAMETER_NAME], [CREATED_TIME], [CREATED_BY] in table 'TPROC_PARAMETERS'
ALTER TABLE [dbo].[TPROC_PARAMETERS]
ADD CONSTRAINT [PK_TPROC_PARAMETERS]
    PRIMARY KEY CLUSTERED ([PARAMETER_CODE], [PARAMETER_NAME], [CREATED_TIME], [CREATED_BY] ASC);
GO

-- Creating primary key on [ID], [PR_HEADER_ID], [HISTORICAL_DT], [HISTORICAL_STATUS], [HISTORICAL_BY], [CREATED_TIME], [CREATED_BY], [ROW_STATUS] in table 'TPROC_PR_HISTORICAL'
ALTER TABLE [dbo].[TPROC_PR_HISTORICAL]
ADD CONSTRAINT [PK_TPROC_PR_HISTORICAL]
    PRIMARY KEY CLUSTERED ([ID], [PR_HEADER_ID], [HISTORICAL_DT], [HISTORICAL_STATUS], [HISTORICAL_BY], [CREATED_TIME], [CREATED_BY], [ROW_STATUS] ASC);
GO

-- Creating primary key on [ID], [REFNO], [CREATED_TIME], [CREATED_BY], [LATEST_COST], [AVERAGE_COST] in table 'TPROC_STOCKMOVEMENT'
ALTER TABLE [dbo].[TPROC_STOCKMOVEMENT]
ADD CONSTRAINT [PK_TPROC_STOCKMOVEMENT]
    PRIMARY KEY CLUSTERED ([ID], [REFNO], [CREATED_TIME], [CREATED_BY], [LATEST_COST], [AVERAGE_COST] ASC);
GO

-- Creating primary key on [ID] in table 'TPROC_FST_BUDGET_CD_ADD'
ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD]
ADD CONSTRAINT [PK_TPROC_FST_BUDGET_CD_ADD]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ACKNOW_APPR_ID] in table 'TPROC_ACKNOW_APPR_DT'
ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT]
ADD CONSTRAINT [FK_TPROC_ACKNOW_APPR]
    FOREIGN KEY ([ACKNOW_APPR_ID])
    REFERENCES [dbo].[TPROC_ACKNOW_APPR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_ACKNOW_APPR'
CREATE INDEX [IX_FK_TPROC_ACKNOW_APPR]
ON [dbo].[TPROC_ACKNOW_APPR_DT]
    ([ACKNOW_APPR_ID]);
GO

-- Creating foreign key on [PC_ID] in table 'TPROC_APPR_PC'
ALTER TABLE [dbo].[TPROC_APPR_PC]
ADD CONSTRAINT [FK_TPROC_PC_APPR]
    FOREIGN KEY ([PC_ID])
    REFERENCES [dbo].[TPROC_PC]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PC_APPR'
CREATE INDEX [IX_FK_TPROC_PC_APPR]
ON [dbo].[TPROC_APPR_PC]
    ([PC_ID]);
GO

-- Creating foreign key on [PO_ID] in table 'TPROC_APPR_PO'
ALTER TABLE [dbo].[TPROC_APPR_PO]
ADD CONSTRAINT [FK_TPROC_PO_APPR]
    FOREIGN KEY ([PO_ID])
    REFERENCES [dbo].[TPROC_PO_HEADERS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PO_APPR'
CREATE INDEX [IX_FK_TPROC_PO_APPR]
ON [dbo].[TPROC_APPR_PO]
    ([PO_ID]);
GO

-- Creating foreign key on [APPROVAL_RELDEPT_GR_ID] in table 'TPROC_APPR_RELDEPT_DT'
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT]
ADD CONSTRAINT [FK_TPROC_APPR_RELDEPT_GR_2]
    FOREIGN KEY ([APPROVAL_RELDEPT_GR_ID])
    REFERENCES [dbo].[TPROC_APPR_RELDEPT_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_APPR_RELDEPT_GR_2'
CREATE INDEX [IX_FK_TPROC_APPR_RELDEPT_GR_2]
ON [dbo].[TPROC_APPR_RELDEPT_DT]
    ([APPROVAL_RELDEPT_GR_ID]);
GO

-- Creating foreign key on [LEVEL_ID] in table 'TPROC_APPR_RELDEPT_DT'
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT]
ADD CONSTRAINT [FK_TPROC_LEVEL_RELDEPT]
    FOREIGN KEY ([LEVEL_ID])
    REFERENCES [dbo].[TPROC_LEVEL]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_LEVEL_RELDEPT'
CREATE INDEX [IX_FK_TPROC_LEVEL_RELDEPT]
ON [dbo].[TPROC_APPR_RELDEPT_DT]
    ([LEVEL_ID]);
GO

-- Creating foreign key on [APPROVAL_RELDEPT_GR_ID] in table 'TPROC_REL_DEPT'
ALTER TABLE [dbo].[TPROC_REL_DEPT]
ADD CONSTRAINT [FK_APPROVAL_RELDEPT_GR]
    FOREIGN KEY ([APPROVAL_RELDEPT_GR_ID])
    REFERENCES [dbo].[TPROC_APPR_RELDEPT_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_APPROVAL_RELDEPT_GR'
CREATE INDEX [IX_FK_APPROVAL_RELDEPT_GR]
ON [dbo].[TPROC_REL_DEPT]
    ([APPROVAL_RELDEPT_GR_ID]);
GO

-- Creating foreign key on [APPROVAL_GROUP_ID] in table 'TPROC_APPROVAL_DT'
ALTER TABLE [dbo].[TPROC_APPROVAL_DT]
ADD CONSTRAINT [FK_APPROVAL_GROUP]
    FOREIGN KEY ([APPROVAL_GROUP_ID])
    REFERENCES [dbo].[TPROC_APPROVAL_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_APPROVAL_GROUP'
CREATE INDEX [IX_FK_APPROVAL_GROUP]
ON [dbo].[TPROC_APPROVAL_DT]
    ([APPROVAL_GROUP_ID]);
GO

-- Creating foreign key on [LEVEL_ID] in table 'TPROC_APPROVAL_DT'
ALTER TABLE [dbo].[TPROC_APPROVAL_DT]
ADD CONSTRAINT [FK_LEVEL_APPROVAL_DT]
    FOREIGN KEY ([LEVEL_ID])
    REFERENCES [dbo].[TPROC_LEVEL]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LEVEL_APPROVAL_DT'
CREATE INDEX [IX_FK_LEVEL_APPROVAL_DT]
ON [dbo].[TPROC_APPROVAL_DT]
    ([LEVEL_ID]);
GO

-- Creating foreign key on [APPROVAL_GROUP_ID] in table 'TPROC_WA'
ALTER TABLE [dbo].[TPROC_WA]
ADD CONSTRAINT [FK_APPROVAL_GROUP_WA]
    FOREIGN KEY ([APPROVAL_GROUP_ID])
    REFERENCES [dbo].[TPROC_APPROVAL_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_APPROVAL_GROUP_WA'
CREATE INDEX [IX_FK_APPROVAL_GROUP_WA]
ON [dbo].[TPROC_WA]
    ([APPROVAL_GROUP_ID]);
GO

-- Creating foreign key on [DIVISION_ID] in table 'TPROC_APPROVAL_GR'
ALTER TABLE [dbo].[TPROC_APPROVAL_GR]
ADD CONSTRAINT [FK_DIVISION]
    FOREIGN KEY ([DIVISION_ID])
    REFERENCES [dbo].[TPROC_DIVISION]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DIVISION'
CREATE INDEX [IX_FK_DIVISION]
ON [dbo].[TPROC_APPROVAL_GR]
    ([DIVISION_ID]);
GO

-- Creating foreign key on [LEVEL_ID] in table 'TPROC_APPROVAL_ROLE'
ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE]
ADD CONSTRAINT [FK_LEVEL_APPROVAL_ROLE]
    FOREIGN KEY ([LEVEL_ID])
    REFERENCES [dbo].[TPROC_LEVEL]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LEVEL_APPROVAL_ROLE'
CREATE INDEX [IX_FK_LEVEL_APPROVAL_ROLE]
ON [dbo].[TPROC_APPROVAL_ROLE]
    ([LEVEL_ID]);
GO

-- Creating foreign key on [SUB_COA_GR_ID] in table 'TPROC_CHART_OF_ACCOUNTS'
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS]
ADD CONSTRAINT [FK_TPROC_COA_GR_FST]
    FOREIGN KEY ([SUB_COA_GR_ID])
    REFERENCES [dbo].[TPROC_CHART_OF_ACCOUNT_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_COA_GR_FST'
CREATE INDEX [IX_FK_TPROC_COA_GR_FST]
ON [dbo].[TPROC_CHART_OF_ACCOUNTS]
    ([SUB_COA_GR_ID]);
GO

-- Creating foreign key on [CURRENCY] in table 'TPROC_PO_HEADERS'
ALTER TABLE [dbo].[TPROC_PO_HEADERS]
ADD CONSTRAINT [FK_TPROC_CURRENCY]
    FOREIGN KEY ([CURRENCY])
    REFERENCES [dbo].[TPROC_CURRENCY]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_CURRENCY'
CREATE INDEX [IX_FK_TPROC_CURRENCY]
ON [dbo].[TPROC_PO_HEADERS]
    ([CURRENCY]);
GO

-- Creating foreign key on [DELIVERY_ID] in table 'TPROC_PO_HEADERS'
ALTER TABLE [dbo].[TPROC_PO_HEADERS]
ADD CONSTRAINT [FK_TPROC_DELIVERY_ADDRESS]
    FOREIGN KEY ([DELIVERY_ID])
    REFERENCES [dbo].[TPROC_DELIVERY_ADDRESS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_DELIVERY_ADDRESS'
CREATE INDEX [IX_FK_TPROC_DELIVERY_ADDRESS]
ON [dbo].[TPROC_PO_HEADERS]
    ([DELIVERY_ID]);
GO

-- Creating foreign key on [DIVISION_ID] in table 'TPROC_USER_DT'
ALTER TABLE [dbo].[TPROC_USER_DT]
ADD CONSTRAINT [FK_DIVISION_USER_DT]
    FOREIGN KEY ([DIVISION_ID])
    REFERENCES [dbo].[TPROC_DIVISION]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DIVISION_USER_DT'
CREATE INDEX [IX_FK_DIVISION_USER_DT]
ON [dbo].[TPROC_USER_DT]
    ([DIVISION_ID]);
GO

-- Creating foreign key on [SUB_TYPE_ID] in table 'TPROC_PR_HEADER'
ALTER TABLE [dbo].[TPROC_PR_HEADER]
ADD CONSTRAINT [FK_TPROC_FORM_SUB_TYPE]
    FOREIGN KEY ([SUB_TYPE_ID])
    REFERENCES [dbo].[TPROC_FORM_SUB_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_FORM_SUB_TYPE'
CREATE INDEX [IX_FK_TPROC_FORM_SUB_TYPE]
ON [dbo].[TPROC_PR_HEADER]
    ([SUB_TYPE_ID]);
GO

-- Creating foreign key on [SUB_FORMTYPE_GR_ID] in table 'TPROC_FORM_SUB_TYPE'
ALTER TABLE [dbo].[TPROC_FORM_SUB_TYPE]
ADD CONSTRAINT [FK_TPROC_SUBTYPE_GR_FST]
    FOREIGN KEY ([SUB_FORMTYPE_GR_ID])
    REFERENCES [dbo].[TPROC_FORM_SUBTYPE_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUBTYPE_GR_FST'
CREATE INDEX [IX_FK_TPROC_SUBTYPE_GR_FST]
ON [dbo].[TPROC_FORM_SUB_TYPE]
    ([SUB_FORMTYPE_GR_ID]);
GO

-- Creating foreign key on [FORM_SUBTYPE_GR_ID] in table 'TPROC_FORM_SUBTYPE_DT'
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_DT]
ADD CONSTRAINT [FK_TPROC_SUBTYPE_DT_FT]
    FOREIGN KEY ([FORM_SUBTYPE_GR_ID])
    REFERENCES [dbo].[TPROC_FORM_SUBTYPE_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUBTYPE_DT_FT'
CREATE INDEX [IX_FK_TPROC_SUBTYPE_DT_FT]
ON [dbo].[TPROC_FORM_SUBTYPE_DT]
    ([FORM_SUBTYPE_GR_ID]);
GO

-- Creating foreign key on [REL_DEPT_ID] in table 'TPROC_FORM_SUBTYPE_DT'
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_DT]
ADD CONSTRAINT [FK_TPROC_SUBTYPE_DT_RD]
    FOREIGN KEY ([REL_DEPT_ID])
    REFERENCES [dbo].[TPROC_REL_DEPT]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUBTYPE_DT_RD'
CREATE INDEX [IX_FK_TPROC_SUBTYPE_DT_RD]
ON [dbo].[TPROC_FORM_SUBTYPE_DT]
    ([REL_DEPT_ID]);
GO

-- Creating foreign key on [FORM_TYPE_ID] in table 'TPROC_FORM_SUBTYPE_GR'
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR]
ADD CONSTRAINT [FK_TPROC_SUBTYPE_GR_FT]
    FOREIGN KEY ([FORM_TYPE_ID])
    REFERENCES [dbo].[TPROC_FORM_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUBTYPE_GR_FT'
CREATE INDEX [IX_FK_TPROC_SUBTYPE_GR_FT]
ON [dbo].[TPROC_FORM_SUBTYPE_GR]
    ([FORM_TYPE_ID]);
GO

-- Creating foreign key on [FORM_TYPE_ID] in table 'TPROC_PR_HEADER'
ALTER TABLE [dbo].[TPROC_PR_HEADER]
ADD CONSTRAINT [FK_TPROC_FORM_TYPE]
    FOREIGN KEY ([FORM_TYPE_ID])
    REFERENCES [dbo].[TPROC_FORM_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_FORM_TYPE'
CREATE INDEX [IX_FK_TPROC_FORM_TYPE]
ON [dbo].[TPROC_PR_HEADER]
    ([FORM_TYPE_ID]);
GO

-- Creating foreign key on [FORM_TYPE_ID] in table 'TPROC_PO_TYPE'
ALTER TABLE [dbo].[TPROC_PO_TYPE]
ADD CONSTRAINT [FK_TPROC_FORM_TYPE_PO]
    FOREIGN KEY ([FORM_TYPE_ID])
    REFERENCES [dbo].[TPROC_FORM_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_FORM_TYPE_PO'
CREATE INDEX [IX_FK_TPROC_FORM_TYPE_PO]
ON [dbo].[TPROC_PO_TYPE]
    ([FORM_TYPE_ID]);
GO

-- Creating foreign key on [FORM_TYPE_ID] in table 'TPROC_STOCK'
ALTER TABLE [dbo].[TPROC_STOCK]
ADD CONSTRAINT [FK_TPROC_FORM_TYPE_STOCK]
    FOREIGN KEY ([FORM_TYPE_ID])
    REFERENCES [dbo].[TPROC_FORM_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_FORM_TYPE_STOCK'
CREATE INDEX [IX_FK_TPROC_FORM_TYPE_STOCK]
ON [dbo].[TPROC_STOCK]
    ([FORM_TYPE_ID]);
GO

-- Creating foreign key on [PO_ID] in table 'TPROC_GM_HEADERS'
ALTER TABLE [dbo].[TPROC_GM_HEADERS]
ADD CONSTRAINT [FK_GM_TPROC_PO_HEADERS]
    FOREIGN KEY ([PO_ID])
    REFERENCES [dbo].[TPROC_PO_HEADERS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GM_TPROC_PO_HEADERS'
CREATE INDEX [IX_FK_GM_TPROC_PO_HEADERS]
ON [dbo].[TPROC_GM_HEADERS]
    ([PO_ID]);
GO

-- Creating foreign key on [GOOD_TYPE_ID] in table 'TPROC_STOCK'
ALTER TABLE [dbo].[TPROC_STOCK]
ADD CONSTRAINT [FK_TPROC_GOOD_TYPE]
    FOREIGN KEY ([GOOD_TYPE_ID])
    REFERENCES [dbo].[TPROC_GOOD_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_GOOD_TYPE'
CREATE INDEX [IX_FK_TPROC_GOOD_TYPE]
ON [dbo].[TPROC_STOCK]
    ([GOOD_TYPE_ID]);
GO

-- Creating foreign key on [GOOD_TYPE_ID] in table 'TPROC_PR_HEADER'
ALTER TABLE [dbo].[TPROC_PR_HEADER]
ADD CONSTRAINT [FK_TPROC_GOOD_TYPE_PR_HEADER]
    FOREIGN KEY ([GOOD_TYPE_ID])
    REFERENCES [dbo].[TPROC_GOOD_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_GOOD_TYPE_PR_HEADER'
CREATE INDEX [IX_FK_TPROC_GOOD_TYPE_PR_HEADER]
ON [dbo].[TPROC_PR_HEADER]
    ([GOOD_TYPE_ID]);
GO

-- Creating foreign key on [MENU_ID] in table 'TPROC_ROLE_MENU'
ALTER TABLE [dbo].[TPROC_ROLE_MENU]
ADD CONSTRAINT [FK_MENU_ROLE_EPROC]
    FOREIGN KEY ([MENU_ID])
    REFERENCES [dbo].[TPROC_MENU]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MENU_ROLE_EPROC'
CREATE INDEX [IX_FK_MENU_ROLE_EPROC]
ON [dbo].[TPROC_ROLE_MENU]
    ([MENU_ID]);
GO

-- Creating foreign key on [PC_ID] in table 'TPROC_PC_SP_GR'
ALTER TABLE [dbo].[TPROC_PC_SP_GR]
ADD CONSTRAINT [FK_PC_SP_GR]
    FOREIGN KEY ([PC_ID])
    REFERENCES [dbo].[TPROC_PC]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PC_SP_GR'
CREATE INDEX [IX_FK_PC_SP_GR]
ON [dbo].[TPROC_PC_SP_GR]
    ([PC_ID]);
GO

-- Creating foreign key on [PC_ID] in table 'TPROC_PC_HISTORICAL'
ALTER TABLE [dbo].[TPROC_PC_HISTORICAL]
ADD CONSTRAINT [FK_TPROC_PC_HISTORY]
    FOREIGN KEY ([PC_ID])
    REFERENCES [dbo].[TPROC_PC]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PC_HISTORY'
CREATE INDEX [IX_FK_TPROC_PC_HISTORY]
ON [dbo].[TPROC_PC_HISTORICAL]
    ([PC_ID]);
GO

-- Creating foreign key on [PC_ID] in table 'TPROC_VRF_PC'
ALTER TABLE [dbo].[TPROC_VRF_PC]
ADD CONSTRAINT [FK_TPROC_PC_VRF]
    FOREIGN KEY ([PC_ID])
    REFERENCES [dbo].[TPROC_PC]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PC_VRF'
CREATE INDEX [IX_FK_TPROC_PC_VRF]
ON [dbo].[TPROC_VRF_PC]
    ([PC_ID]);
GO

-- Creating foreign key on [PC_DT_ID] in table 'TPROC_PC_SP_DT'
ALTER TABLE [dbo].[TPROC_PC_SP_DT]
ADD CONSTRAINT [FK_PC_DT]
    FOREIGN KEY ([PC_DT_ID])
    REFERENCES [dbo].[TPROC_PC_DT]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PC_DT'
CREATE INDEX [IX_FK_PC_DT]
ON [dbo].[TPROC_PC_SP_DT]
    ([PC_DT_ID]);
GO

-- Creating foreign key on [PC_SP_GR_ID] in table 'TPROC_PC_SP_DT'
ALTER TABLE [dbo].[TPROC_PC_SP_DT]
ADD CONSTRAINT [FK_TPROC_PC_SP_GR]
    FOREIGN KEY ([PC_SP_GR_ID])
    REFERENCES [dbo].[TPROC_PC_SP_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PC_SP_GR'
CREATE INDEX [IX_FK_TPROC_PC_SP_GR]
ON [dbo].[TPROC_PC_SP_DT]
    ([PC_SP_GR_ID]);
GO

-- Creating foreign key on [PO_DTLS_ITEM_ID] in table 'TPROC_PO_DETAILS'
ALTER TABLE [dbo].[TPROC_PO_DETAILS]
ADD CONSTRAINT [FK_PO_HEADER_ID]
    FOREIGN KEY ([PO_DTLS_ITEM_ID])
    REFERENCES [dbo].[TPROC_PO_DETAILS_ITEM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PO_HEADER_ID'
CREATE INDEX [IX_FK_PO_HEADER_ID]
ON [dbo].[TPROC_PO_DETAILS]
    ([PO_DTLS_ITEM_ID]);
GO

-- Creating foreign key on [PO_HEADER_ID] in table 'TPROC_PO_DETAILS_ITEM'
ALTER TABLE [dbo].[TPROC_PO_DETAILS_ITEM]
ADD CONSTRAINT [FK_PO_DETAILS]
    FOREIGN KEY ([PO_HEADER_ID])
    REFERENCES [dbo].[TPROC_PO_HEADERS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PO_DETAILS'
CREATE INDEX [IX_FK_PO_DETAILS]
ON [dbo].[TPROC_PO_DETAILS_ITEM]
    ([PO_HEADER_ID]);
GO

-- Creating foreign key on [PO_TYPE_ID] in table 'TPROC_PO_HEADERS'
ALTER TABLE [dbo].[TPROC_PO_HEADERS]
ADD CONSTRAINT [FK_TPROC_PO_TYPE]
    FOREIGN KEY ([PO_TYPE_ID])
    REFERENCES [dbo].[TPROC_PO_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PO_TYPE'
CREATE INDEX [IX_FK_TPROC_PO_TYPE]
ON [dbo].[TPROC_PO_HEADERS]
    ([PO_TYPE_ID]);
GO

-- Creating foreign key on [PO_ID] in table 'TPROC_VRF_PO'
ALTER TABLE [dbo].[TPROC_VRF_PO]
ADD CONSTRAINT [FK_TPROC_PO_VRF]
    FOREIGN KEY ([PO_ID])
    REFERENCES [dbo].[TPROC_PO_HEADERS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PO_VRF'
CREATE INDEX [IX_FK_TPROC_PO_VRF]
ON [dbo].[TPROC_VRF_PO]
    ([PO_ID]);
GO

-- Creating foreign key on [SUPPLIER_ID] in table 'TPROC_PO_HEADERS'
ALTER TABLE [dbo].[TPROC_PO_HEADERS]
ADD CONSTRAINT [FK_TPROC_SUPPLIER]
    FOREIGN KEY ([SUPPLIER_ID])
    REFERENCES [dbo].[TPROC_SUPPLIER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUPPLIER'
CREATE INDEX [IX_FK_TPROC_SUPPLIER]
ON [dbo].[TPROC_PO_HEADERS]
    ([SUPPLIER_ID]);
GO

-- Creating foreign key on [PR_APPR_RELDEPT_GR_ID] in table 'TPROC_PR_APPR_RELDEPT_DT'
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_DT]
ADD CONSTRAINT [FK_TPROC_PR_APPR_RD_GR]
    FOREIGN KEY ([PR_APPR_RELDEPT_GR_ID])
    REFERENCES [dbo].[TPROC_PR_APPR_RELDEPT_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PR_APPR_RD_GR'
CREATE INDEX [IX_FK_TPROC_PR_APPR_RD_GR]
ON [dbo].[TPROC_PR_APPR_RELDEPT_DT]
    ([PR_APPR_RELDEPT_GR_ID]);
GO

-- Creating foreign key on [PR_HEADER_ID] in table 'TPROC_PR_APPR_RELDEPT_GR'
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR]
ADD CONSTRAINT [FK_TPROC_PR_HEADER_RD_GR]
    FOREIGN KEY ([PR_HEADER_ID])
    REFERENCES [dbo].[TPROC_PR_HEADER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PR_HEADER_RD_GR'
CREATE INDEX [IX_FK_TPROC_PR_HEADER_RD_GR]
ON [dbo].[TPROC_PR_APPR_RELDEPT_GR]
    ([PR_HEADER_ID]);
GO

-- Creating foreign key on [PR_DETAIL_ID] in table 'TPROC_PR_APPR_WA'
ALTER TABLE [dbo].[TPROC_PR_APPR_WA]
ADD CONSTRAINT [FK_TPROC_PR_DETAIL]
    FOREIGN KEY ([PR_DETAIL_ID])
    REFERENCES [dbo].[TPROC_PR_DETAIL]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PR_DETAIL'
CREATE INDEX [IX_FK_TPROC_PR_DETAIL]
ON [dbo].[TPROC_PR_APPR_WA]
    ([PR_DETAIL_ID]);
GO

-- Creating foreign key on [PR_HEADER_ID] in table 'TPROC_PR_ATTACHMENT'
ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT]
ADD CONSTRAINT [FK_TPROC_PR_HEADER_ATTACHMENT]
    FOREIGN KEY ([PR_HEADER_ID])
    REFERENCES [dbo].[TPROC_PR_HEADER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PR_HEADER_ATTACHMENT'
CREATE INDEX [IX_FK_TPROC_PR_HEADER_ATTACHMENT]
ON [dbo].[TPROC_PR_ATTACHMENT]
    ([PR_HEADER_ID]);
GO

-- Creating foreign key on [PR_HEADER_ID] in table 'TPROC_PR_DETAIL'
ALTER TABLE [dbo].[TPROC_PR_DETAIL]
ADD CONSTRAINT [FK_TPROC_PR_HEADER]
    FOREIGN KEY ([PR_HEADER_ID])
    REFERENCES [dbo].[TPROC_PR_HEADER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PR_HEADER'
CREATE INDEX [IX_FK_TPROC_PR_HEADER]
ON [dbo].[TPROC_PR_DETAIL]
    ([PR_HEADER_ID]);
GO

-- Creating foreign key on [WA_ID] in table 'TPROC_PR_DETAIL'
ALTER TABLE [dbo].[TPROC_PR_DETAIL]
ADD CONSTRAINT [FK_TPROC_WA]
    FOREIGN KEY ([WA_ID])
    REFERENCES [dbo].[TPROC_WA]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_WA'
CREATE INDEX [IX_FK_TPROC_WA]
ON [dbo].[TPROC_PR_DETAIL]
    ([WA_ID]);
GO

-- Creating foreign key on [PR_HEADER_ID] in table 'TPROC_PR_HISTORICAL'
ALTER TABLE [dbo].[TPROC_PR_HISTORICAL]
ADD CONSTRAINT [FK_TPROC_PR_HEADER_HISTORY]
    FOREIGN KEY ([PR_HEADER_ID])
    REFERENCES [dbo].[TPROC_PR_HEADER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_PR_HEADER_HISTORY'
CREATE INDEX [IX_FK_TPROC_PR_HEADER_HISTORY]
ON [dbo].[TPROC_PR_HISTORICAL]
    ([PR_HEADER_ID]);
GO

-- Creating foreign key on [USER_ID_ID] in table 'TPROC_PR_HEADER'
ALTER TABLE [dbo].[TPROC_PR_HEADER]
ADD CONSTRAINT [FK_TPROC_USER]
    FOREIGN KEY ([USER_ID_ID])
    REFERENCES [dbo].[TPROC_USER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_USER'
CREATE INDEX [IX_FK_TPROC_USER]
ON [dbo].[TPROC_PR_HEADER]
    ([USER_ID_ID]);
GO

-- Creating foreign key on [ROLE_ID] in table 'TPROC_ROLE_MENU'
ALTER TABLE [dbo].[TPROC_ROLE_MENU]
ADD CONSTRAINT [FK_ROLE]
    FOREIGN KEY ([ROLE_ID])
    REFERENCES [dbo].[TPROC_ROLE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ROLE'
CREATE INDEX [IX_FK_ROLE]
ON [dbo].[TPROC_ROLE_MENU]
    ([ROLE_ID]);
GO

-- Creating foreign key on [ROLE_ID] in table 'TPROC_USER_DT'
ALTER TABLE [dbo].[TPROC_USER_DT]
ADD CONSTRAINT [FK_ROLE_USER_DETAIL]
    FOREIGN KEY ([ROLE_ID])
    REFERENCES [dbo].[TPROC_ROLE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ROLE_USER_DETAIL'
CREATE INDEX [IX_FK_ROLE_USER_DETAIL]
ON [dbo].[TPROC_USER_DT]
    ([ROLE_ID]);
GO

-- Creating foreign key on [SUPPLIER_ID] in table 'TPROC_SUPP_DOC'
ALTER TABLE [dbo].[TPROC_SUPP_DOC]
ADD CONSTRAINT [FK_TPROC_SUPP_DOC]
    FOREIGN KEY ([SUPPLIER_ID])
    REFERENCES [dbo].[TPROC_SUPPLIER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUPP_DOC'
CREATE INDEX [IX_FK_TPROC_SUPP_DOC]
ON [dbo].[TPROC_SUPP_DOC]
    ([SUPPLIER_ID]);
GO

-- Creating foreign key on [SUPPLIER_ID] in table 'TPROC_SUPP_EVAL'
ALTER TABLE [dbo].[TPROC_SUPP_EVAL]
ADD CONSTRAINT [FK_TPROC_SUPPLIER_EVAL]
    FOREIGN KEY ([SUPPLIER_ID])
    REFERENCES [dbo].[TPROC_SUPPLIER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUPPLIER_EVAL'
CREATE INDEX [IX_FK_TPROC_SUPPLIER_EVAL]
ON [dbo].[TPROC_SUPP_EVAL]
    ([SUPPLIER_ID]);
GO

-- Creating foreign key on [SUPPLIER_ID] in table 'TPROC_SUPP_QUAL'
ALTER TABLE [dbo].[TPROC_SUPP_QUAL]
ADD CONSTRAINT [FK_TPROC_SUPPLIER_QUAL]
    FOREIGN KEY ([SUPPLIER_ID])
    REFERENCES [dbo].[TPROC_SUPPLIER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_SUPPLIER_QUAL'
CREATE INDEX [IX_FK_TPROC_SUPPLIER_QUAL]
ON [dbo].[TPROC_SUPP_QUAL]
    ([SUPPLIER_ID]);
GO

-- Creating foreign key on [USER_DT_ID] in table 'TPROC_USER'
ALTER TABLE [dbo].[TPROC_USER]
ADD CONSTRAINT [FK_USER_DT]
    FOREIGN KEY ([USER_DT_ID])
    REFERENCES [dbo].[TPROC_USER_DT]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_DT'
CREATE INDEX [IX_FK_USER_DT]
ON [dbo].[TPROC_USER]
    ([USER_DT_ID]);
GO

-- Creating foreign key on [USER_ID_ID] in table 'TPROC_USER_PROFILE'
ALTER TABLE [dbo].[TPROC_USER_PROFILE]
ADD CONSTRAINT [FK_USER_EPROC_PROFILE]
    FOREIGN KEY ([USER_ID_ID])
    REFERENCES [dbo].[TPROC_USER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_EPROC_PROFILE'
CREATE INDEX [IX_FK_USER_EPROC_PROFILE]
ON [dbo].[TPROC_USER_PROFILE]
    ([USER_ID_ID]);
GO

-- Creating foreign key on [WA_ALLOWED_GR_ID] in table 'TPROC_USER_DT'
ALTER TABLE [dbo].[TPROC_USER_DT]
ADD CONSTRAINT [FK_WA_GROUP_USER_DETAIL]
    FOREIGN KEY ([WA_ALLOWED_GR_ID])
    REFERENCES [dbo].[TPROC_WA_ALLOWED_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_WA_GROUP_USER_DETAIL'
CREATE INDEX [IX_FK_WA_GROUP_USER_DETAIL]
ON [dbo].[TPROC_USER_DT]
    ([WA_ALLOWED_GR_ID]);
GO

-- Creating foreign key on [WORK_AREA_ID] in table 'TPROC_WA_ALLOWED_DT'
ALTER TABLE [dbo].[TPROC_WA_ALLOWED_DT]
ADD CONSTRAINT [FK_WORK_AREA]
    FOREIGN KEY ([WORK_AREA_ID])
    REFERENCES [dbo].[TPROC_WA]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_WORK_AREA'
CREATE INDEX [IX_FK_WORK_AREA]
ON [dbo].[TPROC_WA_ALLOWED_DT]
    ([WORK_AREA_ID]);
GO

-- Creating foreign key on [WA_ALLOWED_GROUP_ID] in table 'TPROC_WA_ALLOWED_DT'
ALTER TABLE [dbo].[TPROC_WA_ALLOWED_DT]
ADD CONSTRAINT [FK_WA_ALLOWED_GROUP]
    FOREIGN KEY ([WA_ALLOWED_GROUP_ID])
    REFERENCES [dbo].[TPROC_WA_ALLOWED_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_WA_ALLOWED_GROUP'
CREATE INDEX [IX_FK_WA_ALLOWED_GROUP]
ON [dbo].[TPROC_WA_ALLOWED_DT]
    ([WA_ALLOWED_GROUP_ID]);
GO

-- Creating foreign key on [FORM_SUBTYPE_GR_ID] in table 'TPROC_FST_BUDGET_CD_ADD'
ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD]
ADD CONSTRAINT [FK_TPROC_FST_BUDGET_CD_ADD]
    FOREIGN KEY ([FORM_SUBTYPE_GR_ID])
    REFERENCES [dbo].[TPROC_FORM_SUBTYPE_GR]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TPROC_FST_BUDGET_CD_ADD'
CREATE INDEX [IX_FK_TPROC_FST_BUDGET_CD_ADD]
ON [dbo].[TPROC_FST_BUDGET_CD_ADD]
    ([FORM_SUBTYPE_GR_ID]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------