'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MenuSidebar
    Public Property ID As Integer
    Public Property MenuCode As String
    Public Property MenuDescription As String
    Public Property IsInduk As Short
    Public Property Method As String
    Public Property Controller As String
    Public Property MenuInduk As Integer
    Public Property Icon As String
    Public Property CreatedTime As Date
    Public Property CreatedBy As String
    Public Property LastModifiedTime As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property TimeStatus As Byte()
    Public Property RowStatus As Short

End Class
