'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_BUDGET_CODE
    Public Property ID As Integer
    Public Property TABLE_BUDGET As String
    Public Property TABLE_BUDGET_USAGE As String
    Public Property CD_PRINTING_USAGE As String
    Public Property CD_PRINTING_START As String
    Public Property CD_PRINTING_END As String
    Public Property CD_OFFICE_SUPPLIE_USAGE As String
    Public Property CD_OFFICE_SUPPLIE_START As String
    Public Property CD_OFFICE_SUPPLIE_END As String
    Public Property CD_ASSET_NONASSET_USAGE As String
    Public Property CD_ASSET_NONASSET_START As String
    Public Property CD_ASSET_NONASSET_END As String
    Public Property CD_PROMOTIONAL_ITEM_USAGE As String
    Public Property CD_PROMOTIONAL_ITEM_START As String
    Public Property CD_PROMOTIONAL_ITEM_END As String
    Public Property IS_ACTIVE As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property CD_ISSUED_USAGE As String
    Public Property TABLE_T1 As String
    Public Property TABLE_T2 As String
    Public Property TABLE_T3 As String
    Public Property TABLE_T5 As String
    Public Property CD_OFFICE_SUPPLIE_MT As String
    Public Property CD_PRINTING_MT As String

End Class
