'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_WA_ALLOWED_DT
    Public Property ID As Integer
    Public Property WA_ALLOWED_GROUP_ID As Integer
    Public Property WORK_AREA_ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_WA As TPROC_WA
    Public Overridable Property TPROC_WA_ALLOWED_GR As TPROC_WA_ALLOWED_GR

End Class
