'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_STOCKMOVEMENT
    Public Property ID As Integer
    Public Property ITEM_ID As Nullable(Of Integer)
    Public Property REFNO As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property STOCK_CURRENT As Nullable(Of Integer)
    Public Property STOCK_IN As Nullable(Of Integer)
    Public Property STOCK_OUT As Nullable(Of Integer)
    Public Property STOCK_LAST As Nullable(Of Integer)
    Public Property LATEST_COST As Integer
    Public Property AVERAGE_COST As Integer
    Public Property ID_TEMP As Nullable(Of Integer)

End Class
