'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_REQUEST
    Public Property ID As Integer
    Public Property REQUEST_NO As String
    Public Property RELATION_FLAG As String
    Public Property REQUEST_BY As String
    Public Property REQUEST_DT As Date
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property STATUS As Nullable(Of Integer)
    Public Property DESCRIPTION As String
    Public Property CONTROL As String
    Public Property ACTION As String
    Public Property REQUESTOR_EMAIL As String
    Public Property APPROVAL_BY As String
    Public Property APPROVAL_EMAIL As String
    Public Property APPROVED_TIME As Nullable(Of Date)

End Class
