'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_CHART_OF_ACCOUNT_GR
    Public Property ID As Integer
    Public Property CRCY_CD As String
    Public Property ACCT_NUM As String
    Public Property ACCT_DESC As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property REV_COA_ID As Nullable(Of Integer)
    Public Property CONVERTED_ACCT_NUM As String

    Public Overridable Property TPROC_CHART_OF_ACCOUNTS As ICollection(Of TPROC_CHART_OF_ACCOUNTS) = New HashSet(Of TPROC_CHART_OF_ACCOUNTS)

End Class
