'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_FIELD_DESCRIPTIONS
    Public Property APP_CD As String
    Public Property FLD_NM As String
    Public Property FLD_NM_DESC As String
    Public Property DATA_TYP As String
    Public Property DFLT_VALU As String
    Public Property USER_MODIFY_IND As String
    Public Property ID As Integer

End Class
