'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_CRV
    Public Property ID As Integer
    Public Property PO_ID As Nullable(Of Integer)
    Public Property CRV_NUM As String
    Public Property BANK_ACCOUNT_INTEGER As String
    Public Property BANK_NAME As String
    Public Property CREATED_TIME As Nullable(Of Date)
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Nullable(Of Integer)
    Public Property SUB_TOTAL As Nullable(Of Integer)
    Public Property DSCNT_AMT As Nullable(Of Integer)
    Public Property VAT As Nullable(Of Integer)
    Public Property WTH_TAX As Nullable(Of Integer)
    Public Property GRAND_TOTAL As Nullable(Of Integer)
    Public Property RECEIVED_BY As String
    Public Property RECEIVED_DATETIME As Nullable(Of Date)
    Public Property COMPLETED_BY As String
    Public Property COMPLETED_DATETIME As Nullable(Of Date)
    Public Property SUPPLIER_ID As Nullable(Of Integer)
    Public Property BANK_BRANCH As String
    Public Property REFTAXNO As String
    Public Property PAYMENTMETHOD As String
    Public Property KLIRINGNO As String
    Public Property VERIFY_BY As String
    Public Property VERIFY_TIME As Nullable(Of Date)
    Public Property REJECTNOTE As String
    Public Property REJECTED_BY As String
    Public Property REJECTED_TIME As Nullable(Of Date)
    Public Property APPROVE_BY As String
    Public Property APPROVE_DATETIME As Nullable(Of Date)
    Public Property FILEPATH As String

End Class
