'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_FORM_SUBTYPE_GR
    Public Property ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property FORM_TYPE_ID As Nullable(Of Integer)
    Public Property SUB_FORM_TYPE_NAME As String
    Public Property SUB_FORM_TYPE_DESCRIPTION As String
    Public Property SLA As Nullable(Of Integer)
    Public Property POPUP_ACCOUNT As Nullable(Of Integer)
    Public Property BUDGET_CODE As String
    Public Property ACCOUNT_CODE_START As String
    Public Property ACCOUNT_CODE_END As String
    Public Property REV_FST_ID As Nullable(Of Integer)

    Public Overridable Property TPROC_FORM_SUB_TYPE As ICollection(Of TPROC_FORM_SUB_TYPE) = New HashSet(Of TPROC_FORM_SUB_TYPE)
    Public Overridable Property TPROC_FORM_SUBTYPE_DT As ICollection(Of TPROC_FORM_SUBTYPE_DT) = New HashSet(Of TPROC_FORM_SUBTYPE_DT)
    Public Overridable Property TPROC_FST_BUDGET_CD_ADD As ICollection(Of TPROC_FST_BUDGET_CD_ADD) = New HashSet(Of TPROC_FST_BUDGET_CD_ADD)
    Public Overridable Property TPROC_FORM_TYPE As TPROC_FORM_TYPE

End Class
