'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_ACKNOW_APPR
    Public Property ID As Integer
    Public Property PC_ID As Integer
    Public Property WA_ID As Integer
    Public Property WA_NUMBER As Integer
    Public Property STATUS As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_ACKNOW_APPR_DT As ICollection(Of TPROC_ACKNOW_APPR_DT) = New HashSet(Of TPROC_ACKNOW_APPR_DT)

End Class
