'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_PR_APPR_RELDEPT_DT
    Public Property ID As Integer
    Public Property PR_APPR_RELDEPT_GR_ID As Integer
    Public Property USER_ID As String
    Public Property NAME As String
    Public Property APPR_RELDEPT_STATUS As String
    Public Property EMAIL As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_PR_APPR_RELDEPT_GR As TPROC_PR_APPR_RELDEPT_GR

End Class
