'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_PO_HEADERS
    Public Property ID As Integer
    Public Property PO_NUMBER As String
    Public Property CREATE_DATE As Date
    Public Property PO_TYPE_ID As Nullable(Of Integer)
    Public Property CURRENCY As Nullable(Of Integer)
    Public Property PO_STATUS As Nullable(Of Integer)
    Public Property PREPARED_BY As String
    Public Property APPOROVED_BY As String
    Public Property APPOROVED_DATE As Nullable(Of Date)
    Public Property NOTES As String
    Public Property SUPPLIER_NAME As String
    Public Property SUPPLIER_ID As Nullable(Of Integer)
    Public Property CONTACT_PERSON As String
    Public Property SUPPLIER_PHONE As String
    Public Property SUPPLIER_FAX As String
    Public Property SUPPLIER_ADDTRSS As String
    Public Property DELIVERY_NAME As String
    Public Property DELIVERY_ID As Nullable(Of Integer)
    Public Property DELIVERY_DATE As Nullable(Of Date)
    Public Property DELIVERY_PHONE As String
    Public Property DELIVERY_FAX As String
    Public Property DELIVERY_ADDRESS As String
    Public Property SUB_TOTAL As Nullable(Of Integer)
    Public Property DSCNT_AMT As Nullable(Of Integer)
    Public Property VAT As Nullable(Of Integer)
    Public Property WTH_TAX As Nullable(Of Integer)
    Public Property GRAND_TOTAL As Nullable(Of Integer)
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property REVIEWED_BY As String
    Public Property REVIEWED_DATE As Nullable(Of Date)
    Public Property COMPLETED_BY As String
    Public Property COMPLETED_DATE As Nullable(Of Date)
    Public Property PC_ID As Nullable(Of Integer)
    Public Property FOR_STORAGE As Nullable(Of Integer)
    Public Property IS_DISC_PERC As Nullable(Of Integer)
    Public Property IS_VAT_PERC As Nullable(Of Integer)
    Public Property IS_PPH_PERC As Nullable(Of Integer)
    Public Property DISCOUNT_TEMP As Nullable(Of Integer)
    Public Property VAT_TEMP As Nullable(Of Integer)
    Public Property PPH_TEMP As Nullable(Of Integer)
    Public Property FILE_NAME As String
    Public Property VERIFIED_BY As String
    Public Property VERIFIED_DATE As Nullable(Of Date)
    Public Property ADD_COST As Nullable(Of Integer)
    Public Property FINAL_TOTAL As Nullable(Of Integer)
    Public Property ADD_COST_DESC As String
    Public Property REJECT_REASON As String
    Public Property REJECT_BY As String
    Public Property REJECT_DATE As Nullable(Of Date)

    Public Overridable Property TPROC_APPR_PO As ICollection(Of TPROC_APPR_PO) = New HashSet(Of TPROC_APPR_PO)
    Public Overridable Property TPROC_CURRENCY As TPROC_CURRENCY
    Public Overridable Property TPROC_DELIVERY_ADDRESS As TPROC_DELIVERY_ADDRESS
    Public Overridable Property TPROC_GM_HEADERS As ICollection(Of TPROC_GM_HEADERS) = New HashSet(Of TPROC_GM_HEADERS)
    Public Overridable Property TPROC_PO_DETAILS_ITEM As ICollection(Of TPROC_PO_DETAILS_ITEM) = New HashSet(Of TPROC_PO_DETAILS_ITEM)
    Public Overridable Property TPROC_PO_TYPE As TPROC_PO_TYPE
    Public Overridable Property TPROC_VRF_PO As ICollection(Of TPROC_VRF_PO) = New HashSet(Of TPROC_VRF_PO)
    Public Overridable Property TPROC_SUPPLIER As TPROC_SUPPLIER

End Class
