'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_PC
    Public Property ID As Integer
    Public Property PC_NUM As String
    Public Property PO_TYPE_NM As String
    Public Property RECOM_SUPPLIER_NM As String
    Public Property RECOM_SUPPLIER_ID As Integer
    Public Property RECOM_SUPPLIER_CP As String
    Public Property RECOM_SUPPLIER_PHONE As String
    Public Property RECOM_SUPPLIER_FAX As String
    Public Property RECOM_SUPPLIER_ADDRESS As String
    Public Property DELIVERY_NM As String
    Public Property DELIVERY_ID As Integer
    Public Property DELIVERY_DATE As Date
    Public Property DELIVERY_PHONE As String
    Public Property DELIVERY_FAX As String
    Public Property DELIVERY_ADDRESS As String
    Public Property GRAND_TOTAL As Integer
    Public Property NOTE_BY_USER As String
    Public Property NOTE_BY_EPROC As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property IS_DISC_PERC As Nullable(Of Integer)
    Public Property IS_VAT_PERC As Nullable(Of Integer)
    Public Property IS_PPH_PERC As Nullable(Of Integer)
    Public Property STATUS As String
    Public Property NOTES As String
    Public Property CURRENCY As String
    Public Property IS_ACKNOWLEDGE_USER As Nullable(Of Integer)
    Public Property FOR_STORAGE As Nullable(Of Integer)
    Public Property FILE_NAME As String
    Public Property ADD_COST As Nullable(Of Integer)
    Public Property FINAL_TOTAL As Nullable(Of Integer)
    Public Property ADD_COST_DESC As String
    Public Property REJECT_REASON As String
    Public Property REJECT_BY As String
    Public Property REJECT_DATE As Nullable(Of Date)

    Public Overridable Property TPROC_APPR_PC As ICollection(Of TPROC_APPR_PC) = New HashSet(Of TPROC_APPR_PC)
    Public Overridable Property TPROC_PC_SP_GR As ICollection(Of TPROC_PC_SP_GR) = New HashSet(Of TPROC_PC_SP_GR)
    Public Overridable Property TPROC_PC_HISTORICAL As ICollection(Of TPROC_PC_HISTORICAL) = New HashSet(Of TPROC_PC_HISTORICAL)
    Public Overridable Property TPROC_VRF_PC As ICollection(Of TPROC_VRF_PC) = New HashSet(Of TPROC_VRF_PC)

End Class
