'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_FIELD_VALUES
    Public Property ID As Integer
    Public Property APP_CD As String
    Public Property FLD_NM As String
    Public Property FLD_VALU As String
    Public Property FLD_VALU_DESC As String
    Public Property FLD_VALU_DESC_ENG As String
    Public Property SEQ_NUM As Nullable(Of Integer)
    Public Property FLD_VALU_MNE_CD As String
    Public Property STAT_CD As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

End Class
