'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_FORM_SUBTYPE_DT
    Public Property ID As Integer
    Public Property REL_DEPT_ID As Integer
    Public Property FORM_SUBTYPE_GR_ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property FLOW_NUMBER As Nullable(Of Integer)

    Public Overridable Property TPROC_FORM_SUBTYPE_GR As TPROC_FORM_SUBTYPE_GR
    Public Overridable Property TPROC_REL_DEPT As TPROC_REL_DEPT

End Class
