'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_USER_PROFILE
    Public Property ID As Integer
    Public Property USER_ID_ID As Integer
    Public Property PHOTO As Byte()
    Public Property GENDER As String
    Public Property BORN As Nullable(Of Date)
    Public Property ADDRESS As String
    Public Property DESCRIPTION As String
    Public Property JOB As String
    Public Property COMPANY As String
    Public Property HOBBY As String
    Public Property EMAIL As String
    Public Property FACEBOOK As String
    Public Property TWITTER As String
    Public Property IG As String
    Public Property PATH As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_USER As TPROC_USER

End Class
