'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_SUPP_QUAL
    Public Property ID As Integer
    Public Property SUPPLIER_ID As Integer
    Public Property H_STK As Nullable(Of Integer)
    Public Property H_TK As Nullable(Of Integer)
    Public Property H_K As Nullable(Of Integer)
    Public Property H_SK As Nullable(Of Integer)
    Public Property H_KET As String
    Public Property A_TA As Nullable(Of Integer)
    Public Property A_TRK As Nullable(Of Integer)
    Public Property A_RK As Nullable(Of Integer)
    Public Property A_KET As String
    Public Property F_STM As Nullable(Of Integer)
    Public Property F_KM As Nullable(Of Integer)
    Public Property F_M As Nullable(Of Integer)
    Public Property F_SM As Nullable(Of Integer)
    Public Property F_KET As String
    Public Property P_LP As Nullable(Of Integer)
    Public Property P_LTA As Nullable(Of Integer)
    Public Property P_CA As Nullable(Of Integer)
    Public Property P_KET As String
    Public Property Q_TA As Nullable(Of Integer)
    Public Property Q_CS As Nullable(Of Integer)
    Public Property Q_HHA As Nullable(Of Integer)
    Public Property Q_SLP As Nullable(Of Integer)
    Public Property Q_KET As String
    Public Property TOTAL_SCORE As Nullable(Of Integer)
    Public Property DIBUAT_OLEH As String
    Public Property DIPERIKSA_OLEH As String
    Public Property DISETUJUI_OLEH As String
    Public Property KOMENTAR_SARAN As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_SUPPLIER As TPROC_SUPPLIER

End Class
