'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_STOCK
    Public Property ID As Integer
    Public Property ITEM_CODE As String
    Public Property ITEM_DESCRIPTION As String
    Public Property LOOKUP_CODE As String
    Public Property UNIT_OF_STOCK As String
    Public Property LATEST_COST As Integer
    Public Property AVERAGE_COST As Integer
    Public Property PURCHASE_ACCOUNT As String
    Public Property STOCK_EXPENSES As String
    Public Property GOOD_TYPE_ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property SUPPLIER_ID As Nullable(Of Integer)
    Public Property QUANTITY As Nullable(Of Integer)
    Public Property FORM_TYPE_ID As Nullable(Of Integer)
    Public Property QUANTITY_MIN As Nullable(Of Integer)

    Public Overridable Property TPROC_FORM_TYPE As TPROC_FORM_TYPE
    Public Overridable Property TPROC_GOOD_TYPE As TPROC_GOOD_TYPE

End Class
