'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_WA
    Public Property ID As Integer
    Public Property WA_NUMBER As Integer
    Public Property APPROVAL_GROUP_ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_APPROVAL_GR As TPROC_APPROVAL_GR
    Public Overridable Property TPROC_PR_DETAIL As ICollection(Of TPROC_PR_DETAIL) = New HashSet(Of TPROC_PR_DETAIL)
    Public Overridable Property TPROC_WA_ALLOWED_DT As ICollection(Of TPROC_WA_ALLOWED_DT) = New HashSet(Of TPROC_WA_ALLOWED_DT)

End Class
