'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_APPROVAL_GR
    Public Property ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property DEPARTMENT_NAME As String
    Public Property DIVISION_ID As Nullable(Of Integer)
    Public Property REV_WA_ID As Nullable(Of Integer)

    Public Overridable Property TPROC_APPROVAL_DT As ICollection(Of TPROC_APPROVAL_DT) = New HashSet(Of TPROC_APPROVAL_DT)
    Public Overridable Property TPROC_WA As ICollection(Of TPROC_WA) = New HashSet(Of TPROC_WA)
    Public Overridable Property TPROC_DIVISION As TPROC_DIVISION

End Class
