'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_MENU
    Public Property ID As Integer
    Public Property MENU_NAME As String
    Public Property MENU_PARENT_ID As Nullable(Of Integer)
    Public Property MENU_DESCRIPTION As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer

    Public Overridable Property TPROC_ROLE_MENU As ICollection(Of TPROC_ROLE_MENU) = New HashSet(Of TPROC_ROLE_MENU)

End Class
