'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_ROLE
    Public Property ID As Integer
    Public Property ROLE_NAME As String
    Public Property ROLE_DESCRIPTION As String
    Public Property IS_ACTIVE As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property DEFAULT_SELECTED As Nullable(Of Integer)

    Public Overridable Property TPROC_ROLE_MENU As ICollection(Of TPROC_ROLE_MENU) = New HashSet(Of TPROC_ROLE_MENU)
    Public Overridable Property TPROC_USER_DT As ICollection(Of TPROC_USER_DT) = New HashSet(Of TPROC_USER_DT)

End Class
