'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_CURRENCY
    Public Property ID As Integer
    Public Property CURRENCY_NAME As String
    Public Property RATE As Integer
    Public Property START_DATE As Date
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property CONVERSION_RP As Nullable(Of Integer)

    Public Overridable Property TPROC_PO_HEADERS As ICollection(Of TPROC_PO_HEADERS) = New HashSet(Of TPROC_PO_HEADERS)

End Class
