'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_GM_HEADERS
    Public Property ID As Integer
    Public Property GM_INTEGER As String
    Public Property CREATE_DATETIME As Date
    Public Property PO_ID As Nullable(Of Integer)
    Public Property PREPARED_BY As String
    Public Property APPOROVED_BY As String
    Public Property NOTES As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property COMPLETED_BY As String
    Public Property COMPLETED_DATETIME As Nullable(Of Date)
    Public Property REJECTED_BY As String
    Public Property REJECTED_TIME As Nullable(Of Date)
    Public Property REJECTNOTE As String
    Public Property HANDLED_BY As String
    Public Property HANDLED_DATETIME As Nullable(Of Date)

    Public Overridable Property TPROC_PO_HEADERS As TPROC_PO_HEADERS

End Class
