'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_APPR_RELDEPT_GR
    Public Property ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property REV_RD_ID As Nullable(Of Integer)

    Public Overridable Property TPROC_APPR_RELDEPT_DT As ICollection(Of TPROC_APPR_RELDEPT_DT) = New HashSet(Of TPROC_APPR_RELDEPT_DT)
    Public Overridable Property TPROC_REL_DEPT As ICollection(Of TPROC_REL_DEPT) = New HashSet(Of TPROC_REL_DEPT)

End Class
