'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_PC_SP_DT
    Public Property ID As Integer
    Public Property PC_SP_GR_ID As Integer
    Public Property PRICE_PER_PIECE As Integer
    Public Property PRICE_TOTAL As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property PC_DT_ID As Nullable(Of Integer)

    Public Overridable Property TPROC_PC_DT As TPROC_PC_DT
    Public Overridable Property TPROC_PC_SP_GR As TPROC_PC_SP_GR

End Class
