'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_PR_DETAIL
    Public Property ID As Integer
    Public Property PR_HEADER_ID As Integer
    Public Property ITEM_NAME As String
    Public Property SPECIFICATION As String
    Public Property CURRENCY As String
    Public Property QTY As Integer
    Public Property USER_MEASUREMENT As String
    Public Property WA_ID As Integer
    Public Property REVISED_QTY As Nullable(Of Integer)
    Public Property PRICE As Integer
    Public Property TOTAL_PRICE As Integer
    Public Property REMARK As String
    Public Property SUPPLIER_NAME As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property PR_DETAIL_STATUS As Integer
    Public Property REJECT_REASON As String
    Public Property ITEM_CD As String
    Public Property CONVERSION_RP As Nullable(Of Integer)
    Public Property PO_NUMBER As String
    Public Property SUPPLIER_ID As Nullable(Of Integer)
    Public Property EVALUATED_SUPPLIER As Nullable(Of Integer)
    Public Property ITEM_ID As Nullable(Of Integer)
    Public Property WA_NUMBER As Nullable(Of Integer)
    Public Property WA_NUMBER_ACC As Nullable(Of Integer)

    Public Overridable Property TPROC_PR_APPR_WA As ICollection(Of TPROC_PR_APPR_WA) = New HashSet(Of TPROC_PR_APPR_WA)
    Public Overridable Property TPROC_PR_HEADER As TPROC_PR_HEADER
    Public Overridable Property TPROC_WA As TPROC_WA

End Class
