'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_VRF_PC
    Public Property ID As Integer
    Public Property PC_ID As Integer
    Public Property USER_ID As String
    Public Property NAME As String
    Public Property EMAIL As String
    Public Property AS_IS As String
    Public Property STATUS As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property REMARK As String

    Public Overridable Property TPROC_PC As TPROC_PC

End Class
