'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_CONTROL_PARAMETERS
    Public Property TERR_CD As String
    Public Property PARM_TYP As String
    Public Property STATE_CD As String
    Public Property PARM_VALU As String
    Public Property PARM_DESC As String
    Public Property DATA_TYP As String
    Public Property CREATED_BY As String
    Public Property ID As Integer

End Class
