'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_USER_DT
    Public Property ID As Integer
    Public Property WA_ALLOWED_GR_ID As Integer
    Public Property ROLE_ID As Integer
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property DIVISION_ID As Nullable(Of Integer)
    Public Property COMP_CD As Nullable(Of Integer)
    Public Property REV_USER_ID As Nullable(Of Integer)
    Public Property IS_EPROC_ADMIN As Nullable(Of Integer)
    Public Property IS_SUPER_ADMIN As Nullable(Of Integer)

    Public Overridable Property TPROC_DIVISION As TPROC_DIVISION
    Public Overridable Property TPROC_ROLE As TPROC_ROLE
    Public Overridable Property TPROC_USER As ICollection(Of TPROC_USER) = New HashSet(Of TPROC_USER)
    Public Overridable Property TPROC_WA_ALLOWED_GR As TPROC_WA_ALLOWED_GR

End Class
