'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_PO_DETAILS
    Public Property ID As Integer
    Public Property PO_DTLS_ITEM_ID As Integer
    Public Property ITEM_NAME As String
    Public Property USERMEASUREMENT As String
    Public Property QUANTITY As Nullable(Of Integer)
    Public Property PRICE As Nullable(Of Integer)
    Public Property TOTAL As Nullable(Of Integer)
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property FUND_T1 As String
    Public Property LOB1_T2 As String
    Public Property PLAN_T3 As String
    Public Property WA_T4 As String
    Public Property LOB2_T5 As String
    Public Property PR_HEADER_NO As String
    Public Property ITEM_ID As Nullable(Of Integer)

    Public Overridable Property TPROC_PO_DETAILS_ITEM As TPROC_PO_DETAILS_ITEM

End Class
