'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_USER
    Public Property ID As Integer
    Public Property USER_ID As String
    Public Property USER_MAIL As String
    Public Property USER_NAME As String
    Public Property CREATED_TIME As Date
    Public Property CREATED_BY As String
    Public Property LAST_MODIFIED_TIME As Nullable(Of Date)
    Public Property LAST_MODIFIED_BY As String
    Public Property ROW_STATUS As Integer
    Public Property USER_DT_ID As Integer
    Public Property LAST_LOGIN As Nullable(Of Date)
    Public Property PASSWORD As String

    Public Overridable Property TPROC_PR_HEADER As ICollection(Of TPROC_PR_HEADER) = New HashSet(Of TPROC_PR_HEADER)
    Public Overridable Property TPROC_USER_DT As TPROC_USER_DT
    Public Overridable Property TPROC_USER_PROFILE As ICollection(Of TPROC_USER_PROFILE) = New HashSet(Of TPROC_USER_PROFILE)

End Class
