'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPROC_APPROVAL_ROLE_DETAIL
    Public Property ID As Integer
    Public Property ID_APPROVAL_ROLE As Integer
    Public Property ROLE_NAME As String
    Public Property AS_IS As String

End Class
