insert into TPROC_GOOD_TYPE (GOOD_TYPE_NAME, GOOD_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Stock', 'Stock', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GOOD_TYPE (GOOD_TYPE_NAME, GOOD_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Non Stock', 'Non Stock',SYSDATETIME(), 'System', null, null, 0);


--select * from TPROC_GOOD_TYPE
--delete TPROC_GOOD_TYPE