insert into TPROC_BUDGET_CODE (TABLE_BUDGET, TABLE_BUDGET_USAGE, CD_PRINTING_USAGE, CD_PRINTING_START, CD_PRINTING_END, CD_OFFICE_SUPPLIE_USAGE, CD_OFFICE_SUPPLIE_START, CD_OFFICE_SUPPLIE_END, CD_ASSET_NONASSET_USAGE, CD_ASSET_NONASSET_START, CD_ASSET_NONASSET_END, CD_PROMOTIONAL_ITEM_USAGE, CD_PROMOTIONAL_ITEM_START, CD_PROMOTIONAL_ITEM_END, IS_ACTIVE, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, CD_ISSUED_USAGE, TABLE_T1, TABLE_T2, TABLE_T3, TABLE_T5, CD_OFFICE_SUPPLIE_MT, CD_PRINTING_MT)
values ('SAKFLDGMG5', 'SALFLDGMG5', '583400', '583000', '583999', '584200', '584000', '5849999', null, null, null, null, null, null, 1, SYSDATETIME(), 'System', null, null, 0, 'I', '00421', '0000', '00000', '099', '-ADJS', '-ADJP');


--select * fro tproc_budget_code
--delete TPROC_BUDGET_CODE