insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('Asset', 'Asset', SYSDATETIME(), 'system', null, null, 0, 0);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('Office Supplies', 'Office Supplies',SYSDATETIME(), 'system', null, null, 0, 1);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('Printing', 'Printing', SYSDATETIME(), 'system', null, null, 0, 1);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('Non Asset', 'Non Asset', SYSDATETIME(), 'system', null, null, 0, 0);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('Promotional Item', 'Promotional Item', SYSDATETIME(), 'system', null, null, 0, 0);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('EVENT & SALES CONFERENCE', 'BIDDING EVENT & SALES CON', SYSDATETIME(), 'system', null, null, 0, 0);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('MARKETING ALLOWANCE', 'Khusus budget for MA for all PB', SYSDATETIME(), 'system', null, null, 0, 0);
insert into TPROC_FORM_TYPE (FORM_TYPE_NAME, FORM_TYPE_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS, IS_GOOD_TYPE)
values ('IT', 'IT OPERATION', SYSDATETIME(), 'system', null, null, 0, 0);



--select * from tproc_form_type;
--delete tproc_form_type;