insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('UC', 'TPROC_REQUEST', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR ( TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('PR', 'TPROC_PR_HEADER', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('RL', 'TPROC_ROLE', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('PO', 'TPROC_PO_HEADERS', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('POD', 'TPROC_PO_DETAILS', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('PODI', 'TPROC_PO_DETAILS_ITEM', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('VN', 'TPROC_SUPPLIER', 0, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_GENERATOR (TABLE_CODE, TABLE_NAME, LAST_SEQ_NO, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('PC', 'TPROC_PC', 0, SYSDATETIME(), 'System', null, null, 0);


--select * from tproc_generator;
--delete tproc_generator;