insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Human Resource', 'Human Resource', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Legal Compliance', 'Legal Compliance', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Distribution', 'Under Chief Distribution Officer', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Transformation', 'Chief Transformation Officer', SYSDATETIME(), 'System', null, null, 0)
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Experience Design', 'Under Chief Experice Design', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Finance', 'Undar Chief Finance Officer', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Marketing', 'Chief Marketing Officer', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Employee  Benefit', 'Chief of Employee Benefit', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Risk', 'Chief Risk Officer', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Operating', 'Chief Operating  Officer', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Strategy', 'Chief Strategy Officer', SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_DIVISION (DIVISION_NAME, DIVISION_DESCRIPTION, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Cost Accounting', 'Cost Accounting Department', SYSDATETIME(), 'System', null, null, 0);
