insert into TPROC_HOLIDAY (HOLIDAY_DATE, HOLIDAY_DESCRIPTION, CURR_YEAR, CURR_MONTH, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('01/01/2018', 'Leave Mass - New Year', 2017, 1, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_HOLIDAY (HOLIDAY_DATE, HOLIDAY_DESCRIPTION, CURR_YEAR, CURR_MONTH, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('01/02/2018', 'Happy New Year', 2017, 1, SYSDATETIME(), 'System', null, null, 0);



--select * from TPROC_HOLIDAY
--delete TPROC_HOLIDAY