insert into TPROC_LEVEL (INDONESIAN_LEVEL, RUPIAH_LIMIT, CANADIAN_DOLLARS, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Manager', 16000000, 2000, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_LEVEL (INDONESIAN_LEVEL, RUPIAH_LIMIT, CANADIAN_DOLLARS, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('Asisten Manager', 4000000, 800, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_LEVEL (INDONESIAN_LEVEL, RUPIAH_LIMIT, CANADIAN_DOLLARS, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('AVP', 40000000, 5000, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_LEVEL (INDONESIAN_LEVEL, RUPIAH_LIMIT, CANADIAN_DOLLARS, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('VP', 120000000, 15000, SYSDATETIME(), 'System', null, null, 0);
insert into TPROC_LEVEL (INDONESIAN_LEVEL, RUPIAH_LIMIT, CANADIAN_DOLLARS, CREATED_TIME, CREATED_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, ROW_STATUS)
values ('SVP', 400000000, 50000, SYSDATETIME(), 'System', null, null, 0);


--select * from tproc_level;
--delete tproc_level;