USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PR_DETAIL]'))
ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [FK_TPROC_PR_HEADER]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_WA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PR_DETAIL]'))
ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [FK_TPROC_WA]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___CREAT__1B29035F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [DF__TPROC_PR___CREAT__1B29035F]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___ROW_S__1C1D2798]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [DF__TPROC_PR___ROW_S__1C1D2798]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___EVALU__1D114BD1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_DETAIL] DROP CONSTRAINT [DF__TPROC_PR___EVALU__1D114BD1]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_DETAIL]    Script Date: 01/03/2018 12:44:24 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PR_DETAIL]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PR_DETAIL]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_DETAIL]    Script Date: 01/03/2018 12:44:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PR_DETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PR_HEADER_ID] [int] NOT NULL,
	[ITEM_NAME] [varchar](50) NOT NULL,
	[SPECIFICATION] [varchar](100) NULL,
	[CURRENCY] [varchar](10) NOT NULL,
	[QTY] [int] NOT NULL,
	[USER_MEASUREMENT] [varchar](5) NULL,
	[WA_ID] [int] NOT NULL,
	[REVISED_QTY] [int] NULL,
	[PRICE] [int] NOT NULL,
	[TOTAL_PRICE] [int] NOT NULL,
	[REMARK] [varchar](200) NULL,
	[SUPPLIER_NAME] [varchar](200) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[PR_DETAIL_STATUS] [int] NOT NULL,
	[REJECT_REASON] [varchar](400) NULL,
	[ITEM_CD] [varchar](50) NULL,
	[CONVERSION_RP] [int] NULL,
	[PO_NUMBER] [varchar](20) NULL,
	[SUPPLIER_ID] [int] NULL,
	[EVALUATED_SUPPLIER] [int] NULL,
	[ITEM_ID] [int] NULL,
	[WA_NUMBER] [int] NULL,
	[WA_NUMBER_ACC] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PR_HEADER] FOREIGN KEY([PR_HEADER_ID])
REFERENCES [dbo].[TPROC_PR_HEADER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL] CHECK CONSTRAINT [FK_TPROC_PR_HEADER]
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_WA] FOREIGN KEY([WA_ID])
REFERENCES [dbo].[TPROC_WA] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL] CHECK CONSTRAINT [FK_TPROC_WA]
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO

ALTER TABLE [dbo].[TPROC_PR_DETAIL] ADD  DEFAULT ((0)) FOR [EVALUATED_SUPPLIER]
GO


