USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PC_DT]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PC_SP_DT]'))
ALTER TABLE [dbo].[TPROC_PC_SP_DT] DROP CONSTRAINT [FK_PC_DT]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PC_SP_GR]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PC_SP_DT]'))
ALTER TABLE [dbo].[TPROC_PC_SP_DT] DROP CONSTRAINT [FK_TPROC_PC_SP_GR]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___CREAT__53A266AC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_SP_DT] DROP CONSTRAINT [DF__TPROC_PC___CREAT__53A266AC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___ROW_S__54968AE5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_SP_DT] DROP CONSTRAINT [DF__TPROC_PC___ROW_S__54968AE5]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_SP_DT]    Script Date: 01/03/2018 12:41:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PC_SP_DT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PC_SP_DT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_SP_DT]    Script Date: 01/03/2018 12:41:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PC_SP_DT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PC_SP_GR_ID] [int] NOT NULL,
	[PRICE_PER_PIECE] [int] NOT NULL,
	[PRICE_TOTAL] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[PC_DT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PC_SP_DT]  WITH CHECK ADD  CONSTRAINT [FK_PC_DT] FOREIGN KEY([PC_DT_ID])
REFERENCES [dbo].[TPROC_PC_DT] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PC_SP_DT] CHECK CONSTRAINT [FK_PC_DT]
GO

ALTER TABLE [dbo].[TPROC_PC_SP_DT]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PC_SP_GR] FOREIGN KEY([PC_SP_GR_ID])
REFERENCES [dbo].[TPROC_PC_SP_GR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PC_SP_DT] CHECK CONSTRAINT [FK_TPROC_PC_SP_GR]
GO

ALTER TABLE [dbo].[TPROC_PC_SP_DT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PC_SP_DT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


