USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_CUR__CREAT__5224328E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_CURRENCY] DROP CONSTRAINT [DF__TPROC_CUR__CREAT__5224328E]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_CUR__ROW_S__531856C7]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_CURRENCY] DROP CONSTRAINT [DF__TPROC_CUR__ROW_S__531856C7]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CURRENCY]    Script Date: 01/03/2018 12:34:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_CURRENCY]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_CURRENCY]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CURRENCY]    Script Date: 01/03/2018 12:34:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_CURRENCY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CURRENCY_NAME] [varchar](10) NOT NULL,
	[RATE] [int] NOT NULL,
	[START_DATE] [date] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[CONVERSION_RP] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_CURRENCY] UNIQUE NONCLUSTERED 
(
	[CURRENCY_NAME] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_CURRENCY] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_CURRENCY] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


