USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__IS_AC__39237A9A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE] DROP CONSTRAINT [DF__TPROC_ROL__IS_AC__39237A9A]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__CREAT__3A179ED3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE] DROP CONSTRAINT [DF__TPROC_ROL__CREAT__3A179ED3]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__ROW_S__3B0BC30C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE] DROP CONSTRAINT [DF__TPROC_ROL__ROW_S__3B0BC30C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__DEFAU__3BFFE745]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE] DROP CONSTRAINT [DF__TPROC_ROL__DEFAU__3BFFE745]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_ROLE]    Script Date: 01/03/2018 12:45:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_ROLE]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_ROLE]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_ROLE]    Script Date: 01/03/2018 12:45:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [varchar](50) NOT NULL,
	[ROLE_DESCRIPTION] [varchar](100) NOT NULL,
	[IS_ACTIVE] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[DEFAULT_SELECTED] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_ROLE] UNIQUE NONCLUSTERED 
(
	[ROLE_NAME] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_ROLE] ADD  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [dbo].[TPROC_ROLE] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_ROLE] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO

ALTER TABLE [dbo].[TPROC_ROLE] ADD  DEFAULT ((0)) FOR [DEFAULT_SELECTED]
GO


