USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_LOG__CREAT__11158940]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_LOG_TRANSACTIONS] DROP CONSTRAINT [DF__TPROC_LOG__CREAT__11158940]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_LOG__ROW_S__1209AD79]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_LOG_TRANSACTIONS] DROP CONSTRAINT [DF__TPROC_LOG__ROW_S__1209AD79]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_LOG_TRANSACTIONS]    Script Date: 01/03/2018 12:40:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_LOG_TRANSACTIONS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_LOG_TRANSACTIONS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_LOG_TRANSACTIONS]    Script Date: 01/03/2018 12:40:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_LOG_TRANSACTIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FORM] [varchar](50) NOT NULL,
	[TRANSACTION_DESCRIPTION] [varchar](4000) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_LOG_TRANSACTIONS] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_LOG_TRANSACTIONS] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


