USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_SUBTYPE_GR_FT]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_FORM_SUBTYPE_GR]'))
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] DROP CONSTRAINT [FK_TPROC_SUBTYPE_GR_FT]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_FOR__CREAT__26CFC035]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] DROP CONSTRAINT [DF__TPROC_FOR__CREAT__26CFC035]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_FOR__ROW_S__27C3E46E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] DROP CONSTRAINT [DF__TPROC_FOR__ROW_S__27C3E46E]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FORM_SUBTYPE_GR]    Script Date: 01/03/2018 12:36:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_FORM_SUBTYPE_GR]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_FORM_SUBTYPE_GR]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FORM_SUBTYPE_GR]    Script Date: 01/03/2018 12:36:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_FORM_SUBTYPE_GR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[FORM_TYPE_ID] [int] NULL,
	[SUB_FORM_TYPE_NAME] [varchar](50) NULL,
	[SUB_FORM_TYPE_DESCRIPTION] [varchar](100) NULL,
	[SLA] [int] NULL,
	[POPUP_ACCOUNT] [int] NULL,
	[BUDGET_CODE] [varchar](50) NULL,
	[ACCOUNT_CODE_START] [varchar](20) NULL,
	[ACCOUNT_CODE_END] [varchar](20) NULL,
	[REV_FST_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_SUBTYPE_GR_FT] FOREIGN KEY([FORM_TYPE_ID])
REFERENCES [dbo].[TPROC_FORM_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] CHECK CONSTRAINT [FK_TPROC_SUBTYPE_GR_FT]
GO

ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_FORM_SUBTYPE_GR] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


