USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_CHA__CREAT__4B7734FF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR] DROP CONSTRAINT [DF__TPROC_CHA__CREAT__4B7734FF]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_CHA__ROW_S__4C6B5938]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR] DROP CONSTRAINT [DF__TPROC_CHA__ROW_S__4C6B5938]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CHART_OF_ACCOUNT_GR]    Script Date: 01/03/2018 12:32:44 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_CHART_OF_ACCOUNT_GR]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CHART_OF_ACCOUNT_GR]    Script Date: 01/03/2018 12:32:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CRCY_CD] [varchar](2) NOT NULL,
	[ACCT_NUM] [varchar](8) NOT NULL,
	[ACCT_DESC] [varchar](100) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[REV_COA_ID] [int] NULL,
	[CONVERTED_ACCT_NUM] [varchar](8) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNT_GR] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


