USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_CURRENCY]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PO_HEADERS]'))
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_CURRENCY]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_DELIVERY_ADDRESS]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PO_HEADERS]'))
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_DELIVERY_ADDRESS]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PO_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PO_HEADERS]'))
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_PO_TYPE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_SUPPLIER]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PO_HEADERS]'))
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [FK_TPROC_SUPPLIER]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___CREAT__12C8C788]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___CREAT__12C8C788]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___CREAT__13BCEBC1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___CREAT__13BCEBC1]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___ROW_S__14B10FFA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___ROW_S__14B10FFA]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___FOR_S__15A53433]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___FOR_S__15A53433]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___IS_DI__1699586C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___IS_DI__1699586C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___IS_VA__178D7CA5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___IS_VA__178D7CA5]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___IS_PP__1881A0DE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___IS_PP__1881A0DE]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___DISCO__1975C517]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___DISCO__1975C517]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___VAT_T__1A69E950]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___VAT_T__1A69E950]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___PPH_T__1B5E0D89]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_HEADERS] DROP CONSTRAINT [DF__TPROC_PO___PPH_T__1B5E0D89]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PO_HEADERS]    Script Date: 01/03/2018 12:42:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PO_HEADERS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PO_HEADERS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PO_HEADERS]    Script Date: 01/03/2018 12:42:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PO_HEADERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_NUMBER] [varchar](20) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[PO_TYPE_ID] [int] NULL,
	[CURRENCY] [int] NULL,
	[PO_STATUS] [int] NULL,
	[PREPARED_BY] [varchar](8) NULL,
	[APPOROVED_BY] [varchar](8) NULL,
	[APPOROVED_DATE] [datetime] NULL,
	[NOTES] [varchar](200) NULL,
	[SUPPLIER_NAME] [varchar](100) NULL,
	[SUPPLIER_ID] [int] NULL,
	[CONTACT_PERSON] [varchar](50) NULL,
	[SUPPLIER_PHONE] [varchar](100) NULL,
	[SUPPLIER_FAX] [varchar](50) NULL,
	[SUPPLIER_ADDTRSS] [varchar](200) NULL,
	[DELIVERY_NAME] [varchar](50) NULL,
	[DELIVERY_ID] [int] NULL,
	[DELIVERY_DATE] [datetime] NULL,
	[DELIVERY_PHONE] [varchar](20) NULL,
	[DELIVERY_FAX] [varchar](20) NULL,
	[DELIVERY_ADDRESS] [varchar](100) NULL,
	[SUB_TOTAL] [int] NULL,
	[DSCNT_AMT] [int] NULL,
	[VAT] [int] NULL,
	[WTH_TAX] [int] NULL,
	[GRAND_TOTAL] [int] NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[REVIEWED_BY] [varchar](8) NULL,
	[REVIEWED_DATE] [datetime] NULL,
	[COMPLETED_BY] [varchar](8) NULL,
	[COMPLETED_DATE] [datetime] NULL,
	[PC_ID] [int] NULL,
	[FOR_STORAGE] [int] NULL,
	[IS_DISC_PERC] [int] NULL,
	[IS_VAT_PERC] [int] NULL,
	[IS_PPH_PERC] [int] NULL,
	[DISCOUNT_TEMP] [int] NULL,
	[VAT_TEMP] [int] NULL,
	[PPH_TEMP] [int] NULL,
	[FILE_NAME] [varchar](200) NULL,
	[VERIFIED_BY] [varchar](8) NULL,
	[VERIFIED_DATE] [datetime] NULL,
	[ADD_COST] [int] NULL,
	[FINAL_TOTAL] [int] NULL,
	[ADD_COST_DESC] [varchar](200) NULL,
	[REJECT_REASON] [varchar](200) NULL,
	[REJECT_BY] [varchar](8) NULL,
	[REJECT_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_CURRENCY] FOREIGN KEY([CURRENCY])
REFERENCES [dbo].[TPROC_CURRENCY] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] CHECK CONSTRAINT [FK_TPROC_CURRENCY]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_DELIVERY_ADDRESS] FOREIGN KEY([DELIVERY_ID])
REFERENCES [dbo].[TPROC_DELIVERY_ADDRESS] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] CHECK CONSTRAINT [FK_TPROC_DELIVERY_ADDRESS]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PO_TYPE] FOREIGN KEY([PO_TYPE_ID])
REFERENCES [dbo].[TPROC_PO_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] CHECK CONSTRAINT [FK_TPROC_PO_TYPE]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[TPROC_SUPPLIER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] CHECK CONSTRAINT [FK_TPROC_SUPPLIER]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT (sysdatetime()) FOR [CREATE_DATE]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [FOR_STORAGE]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [IS_DISC_PERC]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [IS_VAT_PERC]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [IS_PPH_PERC]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [DISCOUNT_TEMP]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [VAT_TEMP]
GO

ALTER TABLE [dbo].[TPROC_PO_HEADERS] ADD  DEFAULT ((0)) FOR [PPH_TEMP]
GO


