USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LEVEL_APPROVAL_ROLE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_APPROVAL_ROLE]'))
ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] DROP CONSTRAINT [FK_LEVEL_APPROVAL_ROLE]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_APP__CREAT__7EC1CEDB]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] DROP CONSTRAINT [DF__TPROC_APP__CREAT__7EC1CEDB]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_APP__ROW_S__7FB5F314]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] DROP CONSTRAINT [DF__TPROC_APP__ROW_S__7FB5F314]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_APPROVAL_ROLE]    Script Date: 01/03/2018 12:31:47 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_APPROVAL_ROLE]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_APPROVAL_ROLE]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_APPROVAL_ROLE]    Script Date: 01/03/2018 12:31:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_APPROVAL_ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[LEVEL_ID] [int] NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[USER_NAME] [varchar](50) NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
	[SIGNATURE_IMAGE] [varbinary](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_LEVEL_APPROVAL_ROLE] FOREIGN KEY([LEVEL_ID])
REFERENCES [dbo].[TPROC_LEVEL] ([ID])
GO

ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] CHECK CONSTRAINT [FK_LEVEL_APPROVAL_ROLE]
GO

ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_APPROVAL_ROLE] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


