USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_GM_TPROC_PO_HEADERS]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_GM_HEADERS]'))
ALTER TABLE [dbo].[TPROC_GM_HEADERS] DROP CONSTRAINT [FK_GM_TPROC_PO_HEADERS]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_GM___CREAT__4183B671]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_GM_HEADERS] DROP CONSTRAINT [DF__TPROC_GM___CREAT__4183B671]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_GM___CREAT__4277DAAA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_GM_HEADERS] DROP CONSTRAINT [DF__TPROC_GM___CREAT__4277DAAA]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_GM___ROW_S__436BFEE3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_GM_HEADERS] DROP CONSTRAINT [DF__TPROC_GM___ROW_S__436BFEE3]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_GM_HEADERS]    Script Date: 01/03/2018 12:37:56 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_GM_HEADERS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_GM_HEADERS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_GM_HEADERS]    Script Date: 01/03/2018 12:37:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_GM_HEADERS](
	[ID] [int] NOT NULL,
	[GM_INTEGER] [varchar](20) NOT NULL,
	[CREATE_DATETIME] [datetime] NOT NULL,
	[PO_ID] [int] NULL,
	[PREPARED_BY] [varchar](8) NULL,
	[APPOROVED_BY] [varchar](8) NULL,
	[NOTES] [varchar](200) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[COMPLETED_BY] [varchar](8) NULL,
	[COMPLETED_DATETIME] [datetime] NULL,
	[REJECTED_BY] [varchar](8) NULL,
	[REJECTED_TIME] [datetime] NULL,
	[REJECTNOTE] [varchar](200) NULL,
	[HANDLED_BY] [varchar](8) NULL,
	[HANDLED_DATETIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_TPROC_GM_HEADERS] UNIQUE NONCLUSTERED 
(
	[GM_INTEGER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_GM_HEADERS]  WITH CHECK ADD  CONSTRAINT [FK_GM_TPROC_PO_HEADERS] FOREIGN KEY([PO_ID])
REFERENCES [dbo].[TPROC_PO_HEADERS] ([ID])
GO

ALTER TABLE [dbo].[TPROC_GM_HEADERS] CHECK CONSTRAINT [FK_GM_TPROC_PO_HEADERS]
GO

ALTER TABLE [dbo].[TPROC_GM_HEADERS] ADD  DEFAULT (sysdatetime()) FOR [CREATE_DATETIME]
GO

ALTER TABLE [dbo].[TPROC_GM_HEADERS] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_GM_HEADERS] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


