USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PAR__CREAT__51EF2864]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PARAMETERS] DROP CONSTRAINT [DF__TPROC_PAR__CREAT__51EF2864]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PARAMETERS]    Script Date: 01/03/2018 12:40:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PARAMETERS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PARAMETERS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PARAMETERS]    Script Date: 01/03/2018 12:40:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PARAMETERS](
	[PARAMETER_CODE] [varchar](50) NOT NULL,
	[PARAMETER_NAME] [varchar](100) NOT NULL,
	[PARAMETER_DESCRIPTION] [varchar](200) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[PARAMETER_VALUE] [varchar](100) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_TPROC_PARAMETERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PARAMETERS] ADD  CONSTRAINT [DF__TPROC_PAR__CREAT__51EF2864]  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO


