USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_DOC__CREAT__6442E2C9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_DOCUMENTS] DROP CONSTRAINT [DF__TPROC_DOC__CREAT__6442E2C9]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_DOC__ROW_S__65370702]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_DOCUMENTS] DROP CONSTRAINT [DF__TPROC_DOC__ROW_S__65370702]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_DOCUMENTS]    Script Date: 01/03/2018 12:35:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_DOCUMENTS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_DOCUMENTS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_DOCUMENTS]    Script Date: 01/03/2018 12:35:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_DOCUMENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FILE_NAME] [varchar](50) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_DOCUMENTS] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_DOCUMENTS] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


