USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CONTROL_PARAMETERS]    Script Date: 01/03/2018 12:33:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_CONTROL_PARAMETERS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_CONTROL_PARAMETERS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CONTROL_PARAMETERS]    Script Date: 01/03/2018 12:33:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_CONTROL_PARAMETERS](
	[TERR_CD] [varchar](5) NOT NULL,
	[PARM_TYP] [varchar](30) NOT NULL,
	[STATE_CD] [varchar](2) NOT NULL,
	[PARM_VALU] [varchar](100) NULL,
	[PARM_DESC] [varchar](100) NOT NULL,
	[DATA_TYP] [varchar](1) NOT NULL,
	[CREATED_BY] [varchar](30) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_TPROC_CONTROL_PARAMETERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


