USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_SUPPLIER_QUAL]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_SUPP_QUAL]'))
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [FK_TPROC_SUPPLIER_QUAL]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__H_STK__70099B30]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__H_STK__70099B30]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__H_TK__70FDBF69]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__H_TK__70FDBF69]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP___H_K__71F1E3A2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP___H_K__71F1E3A2]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__H_SK__72E607DB]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__H_SK__72E607DB]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__A_TA__73DA2C14]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__A_TA__73DA2C14]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__A_TRK__74CE504D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__A_TRK__74CE504D]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__A_RK__75C27486]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__A_RK__75C27486]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__F_STM__76B698BF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__F_STM__76B698BF]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__F_KM__77AABCF8]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__F_KM__77AABCF8]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP___F_M__789EE131]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP___F_M__789EE131]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__F_SM__7993056A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__F_SM__7993056A]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__P_LP__7A8729A3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__P_LP__7A8729A3]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__P_LTA__7B7B4DDC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__P_LTA__7B7B4DDC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__P_CA__7C6F7215]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__P_CA__7C6F7215]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__Q_TA__7D63964E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__Q_TA__7D63964E]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP__Q_CS__7E57BA87]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUPP__Q_CS__7E57BA87]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__Q_HHA__7F4BDEC0]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__Q_HHA__7F4BDEC0]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__Q_SLP__004002F9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__Q_SLP__004002F9]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__TOTAL__01342732]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__TOTAL__01342732]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__CREAT__02284B6B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__CREAT__02284B6B]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__ROW_S__031C6FA4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_QUAL] DROP CONSTRAINT [DF__TPROC_SUP__ROW_S__031C6FA4]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_SUPP_QUAL]    Script Date: 01/03/2018 12:46:52 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_SUPP_QUAL]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_SUPP_QUAL]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_SUPP_QUAL]    Script Date: 01/03/2018 12:46:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_SUPP_QUAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [int] NOT NULL,
	[H_STK] [int] NULL,
	[H_TK] [int] NULL,
	[H_K] [int] NULL,
	[H_SK] [int] NULL,
	[H_KET] [varchar](200) NULL,
	[A_TA] [int] NULL,
	[A_TRK] [int] NULL,
	[A_RK] [int] NULL,
	[A_KET] [varchar](200) NULL,
	[F_STM] [int] NULL,
	[F_KM] [int] NULL,
	[F_M] [int] NULL,
	[F_SM] [int] NULL,
	[F_KET] [varchar](200) NULL,
	[P_LP] [int] NULL,
	[P_LTA] [int] NULL,
	[P_CA] [int] NULL,
	[P_KET] [varchar](200) NULL,
	[Q_TA] [int] NULL,
	[Q_CS] [int] NULL,
	[Q_HHA] [int] NULL,
	[Q_SLP] [int] NULL,
	[Q_KET] [varchar](200) NULL,
	[TOTAL_SCORE] [int] NULL,
	[DIBUAT_OLEH] [varchar](200) NULL,
	[DIPERIKSA_OLEH] [varchar](200) NULL,
	[DISETUJUI_OLEH] [varchar](200) NULL,
	[KOMENTAR_SARAN] [varchar](200) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_SUPPLIER_QUAL] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[TPROC_SUPPLIER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] CHECK CONSTRAINT [FK_TPROC_SUPPLIER_QUAL]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [H_STK]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [H_TK]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [H_K]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [H_SK]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [A_TA]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [A_TRK]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [A_RK]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [F_STM]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [F_KM]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [F_M]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [F_SM]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [P_LP]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [P_LTA]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [P_CA]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [Q_TA]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [Q_CS]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [Q_HHA]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [Q_SLP]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [TOTAL_SCORE]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_SUPP_QUAL] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


