USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_ACKNOW_APPR]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_ACKNOW_APPR_DT]'))
ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT] DROP CONSTRAINT [FK_TPROC_ACKNOW_APPR]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ACK__CREAT__54CB950F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT] DROP CONSTRAINT [DF__TPROC_ACK__CREAT__54CB950F]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ACK__ROW_S__55BFB948]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT] DROP CONSTRAINT [DF__TPROC_ACK__ROW_S__55BFB948]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_ACKNOW_APPR_DT]    Script Date: 01/03/2018 12:29:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_ACKNOW_APPR_DT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_ACKNOW_APPR_DT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_ACKNOW_APPR_DT]    Script Date: 01/03/2018 12:29:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_ACKNOW_APPR_DT](
	[ID] [int] NOT NULL,
	[ACKNOW_APPR_ID] [int] NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
	[USER_NAME] [varchar](50) NOT NULL,
	[USER_EMAIL] [varchar](50) NOT NULL,
	[STATUS] [varchar](50) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_ACKNOW_APPR] FOREIGN KEY([ACKNOW_APPR_ID])
REFERENCES [dbo].[TPROC_ACKNOW_APPR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT] CHECK CONSTRAINT [FK_TPROC_ACKNOW_APPR]
GO

ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_ACKNOW_APPR_DT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


