USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PC_SP_GR]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PC_SP_GR]'))
ALTER TABLE [dbo].[TPROC_PC_SP_GR] DROP CONSTRAINT [FK_PC_SP_GR]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___CREAT__4CF5691D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_SP_GR] DROP CONSTRAINT [DF__TPROC_PC___CREAT__4CF5691D]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___ROW_S__4DE98D56]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_SP_GR] DROP CONSTRAINT [DF__TPROC_PC___ROW_S__4DE98D56]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_SP_GR]    Script Date: 01/03/2018 12:41:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PC_SP_GR]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PC_SP_GR]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_SP_GR]    Script Date: 01/03/2018 12:41:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PC_SP_GR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PC_ID] [int] NOT NULL,
	[SUPP_ID] [int] NOT NULL,
	[SUPP_NM] [varchar](100) NULL,
	[URL_ATTACHMENT] [varchar](50) NULL,
	[IS_USED] [int] NULL,
	[COL_NUM] [int] NOT NULL,
	[GRAND_TOTAL] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[DISCOUNT] [int] NULL,
	[VAT] [int] NULL,
	[PPH] [int] NULL,
	[DISCOUNT_TEMP] [int] NULL,
	[VAT_TEMP] [int] NULL,
	[PPH_TEMP] [int] NULL,
	[SUB_TOTAL] [int] NULL,
	[DESCRIPTION] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PC_SP_GR]  WITH CHECK ADD  CONSTRAINT [FK_PC_SP_GR] FOREIGN KEY([PC_ID])
REFERENCES [dbo].[TPROC_PC] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PC_SP_GR] CHECK CONSTRAINT [FK_PC_SP_GR]
GO

ALTER TABLE [dbo].[TPROC_PC_SP_GR] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PC_SP_GR] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


