USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MENU_ROLE_EPROC]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_ROLE_MENU]'))
ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [FK_MENU_ROLE_EPROC]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ROLE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_ROLE_MENU]'))
ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [FK_ROLE]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__IS_AC__34E8D562]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [DF__TPROC_ROL__IS_AC__34E8D562]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__CREAT__35DCF99B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [DF__TPROC_ROL__CREAT__35DCF99B]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_ROL__ROW_S__36D11DD4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_ROLE_MENU] DROP CONSTRAINT [DF__TPROC_ROL__ROW_S__36D11DD4]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_ROLE_MENU]    Script Date: 01/03/2018 12:45:48 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_ROLE_MENU]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_ROLE_MENU]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_ROLE_MENU]    Script Date: 01/03/2018 12:45:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_ROLE_MENU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_ID] [int] NOT NULL,
	[MENU_ID] [int] NOT NULL,
	[IS_ACCESS] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU]  WITH CHECK ADD  CONSTRAINT [FK_MENU_ROLE_EPROC] FOREIGN KEY([MENU_ID])
REFERENCES [dbo].[TPROC_MENU] ([ID])
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU] CHECK CONSTRAINT [FK_MENU_ROLE_EPROC]
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU]  WITH CHECK ADD  CONSTRAINT [FK_ROLE] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[TPROC_ROLE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU] CHECK CONSTRAINT [FK_ROLE]
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU] ADD  DEFAULT ((0)) FOR [IS_ACCESS]
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_ROLE_MENU] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


