USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PR_DETAIL]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PR_APPR_WA]'))
ALTER TABLE [dbo].[TPROC_PR_APPR_WA] DROP CONSTRAINT [FK_TPROC_PR_DETAIL]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___CREAT__23BE4960]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_APPR_WA] DROP CONSTRAINT [DF__TPROC_PR___CREAT__23BE4960]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___ROW_S__24B26D99]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_APPR_WA] DROP CONSTRAINT [DF__TPROC_PR___ROW_S__24B26D99]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_APPR_WA]    Script Date: 01/03/2018 12:43:57 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PR_APPR_WA]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PR_APPR_WA]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_APPR_WA]    Script Date: 01/03/2018 12:43:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PR_APPR_WA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PR_DETAIL_ID] [int] NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
	[NAME] [varchar](50) NULL,
	[APPR_WA_STATUS] [varchar](50) NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_WA]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PR_DETAIL] FOREIGN KEY([PR_DETAIL_ID])
REFERENCES [dbo].[TPROC_PR_DETAIL] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_WA] CHECK CONSTRAINT [FK_TPROC_PR_DETAIL]
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_WA] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_WA] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


