USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER_ATTACHMENT]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PR_ATTACHMENT]'))
ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] DROP CONSTRAINT [FK_TPROC_PR_HEADER_ATTACHMENT]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___CREAT__2A6B46EF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] DROP CONSTRAINT [DF__TPROC_PR___CREAT__2A6B46EF]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___ROW_S__2B5F6B28]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] DROP CONSTRAINT [DF__TPROC_PR___ROW_S__2B5F6B28]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_ATTACHMENT]    Script Date: 01/03/2018 12:44:11 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PR_ATTACHMENT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PR_ATTACHMENT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_ATTACHMENT]    Script Date: 01/03/2018 12:44:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PR_ATTACHMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PR_HEADER_ID] [int] NOT NULL,
	[FILE_NAME] [varchar](50) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PR_HEADER_ATTACHMENT] FOREIGN KEY([PR_HEADER_ID])
REFERENCES [dbo].[TPROC_PR_HEADER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] CHECK CONSTRAINT [FK_TPROC_PR_HEADER_ATTACHMENT]
GO

ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PR_ATTACHMENT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


