USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_APPR_RELDEPT_GR_2]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_APPR_RELDEPT_DT]'))
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] DROP CONSTRAINT [FK_TPROC_APPR_RELDEPT_GR_2]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_LEVEL_RELDEPT]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_APPR_RELDEPT_DT]'))
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] DROP CONSTRAINT [FK_TPROC_LEVEL_RELDEPT]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_APP__CREAT__5E54FF49]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] DROP CONSTRAINT [DF__TPROC_APP__CREAT__5E54FF49]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_APP__ROW_S__5F492382]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] DROP CONSTRAINT [DF__TPROC_APP__ROW_S__5F492382]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_APPR_RELDEPT_DT]    Script Date: 01/03/2018 12:30:45 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_APPR_RELDEPT_DT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_APPR_RELDEPT_DT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_APPR_RELDEPT_DT]    Script Date: 01/03/2018 12:30:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_APPR_RELDEPT_DT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[APPROVAL_RELDEPT_GR_ID] [int] NOT NULL,
	[APPROVAL_NAME] [varchar](50) NOT NULL,
	[LEVEL_ID] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[EMAIL] [varchar](100) NULL,
	[USER_NAME] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_APPR_RELDEPT_GR_2] FOREIGN KEY([APPROVAL_RELDEPT_GR_ID])
REFERENCES [dbo].[TPROC_APPR_RELDEPT_GR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] CHECK CONSTRAINT [FK_TPROC_APPR_RELDEPT_GR_2]
GO

ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_LEVEL_RELDEPT] FOREIGN KEY([LEVEL_ID])
REFERENCES [dbo].[TPROC_LEVEL] ([ID])
GO

ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] CHECK CONSTRAINT [FK_TPROC_LEVEL_RELDEPT]
GO

ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_APPR_RELDEPT_DT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


