USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PC_HISTORY]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PC_HISTORICAL]'))
ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] DROP CONSTRAINT [FK_TPROC_PC_HISTORY]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___CREAT__2C1E8537]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] DROP CONSTRAINT [DF__TPROC_PC___CREAT__2C1E8537]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___ROW_S__2D12A970]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] DROP CONSTRAINT [DF__TPROC_PC___ROW_S__2D12A970]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_HISTORICAL]    Script Date: 01/03/2018 12:41:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PC_HISTORICAL]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PC_HISTORICAL]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_HISTORICAL]    Script Date: 01/03/2018 12:41:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PC_HISTORICAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PC_ID] [int] NOT NULL,
	[HISTORICAL_DT] [datetime] NOT NULL,
	[HISTORICAL_STATUS] [varchar](50) NOT NULL,
	[HISTORICAL_BY] [varchar](50) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[QUEUE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PC_HISTORICAL]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PC_HISTORY] FOREIGN KEY([PC_ID])
REFERENCES [dbo].[TPROC_PC] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] CHECK CONSTRAINT [FK_TPROC_PC_HISTORY]
GO

ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PC_HISTORICAL] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


