USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_FST_BUDGET_CD_ADD]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_FST_BUDGET_CD_ADD]'))
ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] DROP CONSTRAINT [FK_TPROC_FST_BUDGET_CD_ADD]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_FST__CREAT__47C69FAC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] DROP CONSTRAINT [DF__TPROC_FST__CREAT__47C69FAC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_FST__ROW_S__48BAC3E5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] DROP CONSTRAINT [DF__TPROC_FST__ROW_S__48BAC3E5]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FST_BUDGET_CD_ADD]    Script Date: 01/03/2018 12:37:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_FST_BUDGET_CD_ADD]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FST_BUDGET_CD_ADD]    Script Date: 01/03/2018 12:37:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FORM_SUBTYPE_GR_ID] [int] NOT NULL,
	[BUDGET_CODE] [varchar](50) NOT NULL,
	[ACCOUNT_CODE_START] [varchar](100) NOT NULL,
	[ACCOUNT_CODE_END] [varchar](50) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_FST_BUDGET_CD_ADD] FOREIGN KEY([FORM_SUBTYPE_GR_ID])
REFERENCES [dbo].[TPROC_FORM_SUBTYPE_GR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] CHECK CONSTRAINT [FK_TPROC_FST_BUDGET_CD_ADD]
GO

ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_FST_BUDGET_CD_ADD] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


