USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER_HISTORY]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PR_HISTORICAL]'))
ALTER TABLE [dbo].[TPROC_PR_HISTORICAL] DROP CONSTRAINT [FK_TPROC_PR_HEADER_HISTORY]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___CREAT__2E3BD7D3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_HISTORICAL] DROP CONSTRAINT [DF__TPROC_PR___CREAT__2E3BD7D3]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___ROW_S__2F2FFC0C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_HISTORICAL] DROP CONSTRAINT [DF__TPROC_PR___ROW_S__2F2FFC0C]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_HISTORICAL]    Script Date: 01/03/2018 12:44:53 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PR_HISTORICAL]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PR_HISTORICAL]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_HISTORICAL]    Script Date: 01/03/2018 12:44:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PR_HISTORICAL](
	[ID] [int] NOT NULL,
	[PR_HEADER_ID] [int] NOT NULL,
	[HISTORICAL_DT] [datetime] NOT NULL,
	[HISTORICAL_STATUS] [varchar](20) NOT NULL,
	[HISTORICAL_BY] [varchar](50) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[QUEUE] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PR_HISTORICAL]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PR_HEADER_HISTORY] FOREIGN KEY([PR_HEADER_ID])
REFERENCES [dbo].[TPROC_PR_HEADER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PR_HISTORICAL] CHECK CONSTRAINT [FK_TPROC_PR_HEADER_HISTORY]
GO

ALTER TABLE [dbo].[TPROC_PR_HISTORICAL] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PR_HISTORICAL] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


