USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PR_HEADER_RD_GR]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PR_APPR_RELDEPT_GR]'))
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] DROP CONSTRAINT [FK_TPROC_PR_HEADER_RD_GR]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___CREAT__062DE679]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] DROP CONSTRAINT [DF__TPROC_PR___CREAT__062DE679]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PR___ROW_S__07220AB2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] DROP CONSTRAINT [DF__TPROC_PR___ROW_S__07220AB2]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_APPR_RELDEPT_GR]    Script Date: 01/03/2018 12:43:40 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PR_APPR_RELDEPT_GR]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PR_APPR_RELDEPT_GR]    Script Date: 01/03/2018 12:43:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PR_HEADER_ID] [int] NOT NULL,
	[RELDEPT_NAME] [varchar](50) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[RELDEPT_GR_STATUS] [varchar](50) NULL,
	[REJECT_REASON] [varchar](400) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PR_HEADER_RD_GR] FOREIGN KEY([PR_HEADER_ID])
REFERENCES [dbo].[TPROC_PR_HEADER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] CHECK CONSTRAINT [FK_TPROC_PR_HEADER_RD_GR]
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PR_APPR_RELDEPT_GR] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


