USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USER_EPROC_PROFILE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_USER_PROFILE]'))
ALTER TABLE [dbo].[TPROC_USER_PROFILE] DROP CONSTRAINT [FK_USER_EPROC_PROFILE]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__CREAT__08D548FA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER_PROFILE] DROP CONSTRAINT [DF__TPROC_USE__CREAT__08D548FA]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__ROW_S__09C96D33]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER_PROFILE] DROP CONSTRAINT [DF__TPROC_USE__ROW_S__09C96D33]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_USER_PROFILE]    Script Date: 01/03/2018 12:47:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_USER_PROFILE]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_USER_PROFILE]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_USER_PROFILE]    Script Date: 01/03/2018 12:47:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_USER_PROFILE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID_ID] [int] NOT NULL,
	[PHOTO] [varbinary](1) NULL,
	[GENDER] [char](1) NULL,
	[BORN] [datetime] NULL,
	[ADDRESS] [varchar](100) NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[JOB] [varchar](100) NULL,
	[COMPANY] [varchar](100) NULL,
	[HOBBY] [varchar](100) NULL,
	[EMAIL] [varchar](100) NULL,
	[FACEBOOK] [varchar](100) NULL,
	[TWITTER] [varchar](100) NULL,
	[IG] [varchar](100) NULL,
	[PATH] [varchar](100) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_USER_EPROC_PROFILE] UNIQUE NONCLUSTERED 
(
	[USER_ID_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_USER_PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_USER_EPROC_PROFILE] FOREIGN KEY([USER_ID_ID])
REFERENCES [dbo].[TPROC_USER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_USER_PROFILE] CHECK CONSTRAINT [FK_USER_EPROC_PROFILE]
GO

ALTER TABLE [dbo].[TPROC_USER_PROFILE] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_USER_PROFILE] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


