USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_COA_GR_FST]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_CHART_OF_ACCOUNTS]'))
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] DROP CONSTRAINT [FK_TPROC_COA_GR_FST]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_CHA__CREAT__056ECC6A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] DROP CONSTRAINT [DF__TPROC_CHA__CREAT__056ECC6A]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_CHA__ROW_S__0662F0A3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] DROP CONSTRAINT [DF__TPROC_CHA__ROW_S__0662F0A3]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CHART_OF_ACCOUNTS]    Script Date: 01/03/2018 12:33:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_CHART_OF_ACCOUNTS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_CHART_OF_ACCOUNTS]    Script Date: 01/03/2018 12:33:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [date] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[SUB_COA_GR_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_COA_GR_FST] FOREIGN KEY([SUB_COA_GR_ID])
REFERENCES [dbo].[TPROC_CHART_OF_ACCOUNT_GR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] CHECK CONSTRAINT [FK_TPROC_COA_GR_FST]
GO

ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_CHART_OF_ACCOUNTS] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


