USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_MEN__CREAT__16CE6296]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_MENU] DROP CONSTRAINT [DF__TPROC_MEN__CREAT__16CE6296]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_MEN__ROW_S__17C286CF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_MENU] DROP CONSTRAINT [DF__TPROC_MEN__ROW_S__17C286CF]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_MENU]    Script Date: 01/03/2018 12:40:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_MENU]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_MENU]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_MENU]    Script Date: 01/03/2018 12:40:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_MENU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MENU_NAME] [varchar](50) NOT NULL,
	[MENU_PARENT_ID] [int] NULL,
	[MENU_DESCRIPTION] [varchar](100) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_MENU_EPROC] UNIQUE NONCLUSTERED 
(
	[MENU_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_MENU] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_MENU] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


