USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PPH__CREAT__2CBDA3B5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PPH] DROP CONSTRAINT [DF__TPROC_PPH__CREAT__2CBDA3B5]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PPH__ROW_S__2DB1C7EE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PPH] DROP CONSTRAINT [DF__TPROC_PPH__ROW_S__2DB1C7EE]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PPH]    Script Date: 01/03/2018 12:43:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PPH]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PPH]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PPH]    Script Date: 01/03/2018 12:43:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PPH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PPH_NAME] [int] NOT NULL,
	[START_DATE] [datetime] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_PPH] UNIQUE NONCLUSTERED 
(
	[PPH_NAME] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PPH] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PPH] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


