USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_PO_VRF]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_VRF_PO]'))
ALTER TABLE [dbo].[TPROC_VRF_PO] DROP CONSTRAINT [FK_TPROC_PO_VRF]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_VRF__CREAT__257187A8]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_VRF_PO] DROP CONSTRAINT [DF__TPROC_VRF__CREAT__257187A8]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_VRF__ROW_S__2665ABE1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_VRF_PO] DROP CONSTRAINT [DF__TPROC_VRF__ROW_S__2665ABE1]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_VRF_PO]    Script Date: 01/03/2018 12:48:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_VRF_PO]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_VRF_PO]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_VRF_PO]    Script Date: 01/03/2018 12:48:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_VRF_PO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_ID] [int] NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[AS_IS] [varchar](20) NULL,
	[STATUS] [varchar](50) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[REMARK] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_VRF_PO]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_PO_VRF] FOREIGN KEY([PO_ID])
REFERENCES [dbo].[TPROC_PO_HEADERS] ([ID])
GO

ALTER TABLE [dbo].[TPROC_VRF_PO] CHECK CONSTRAINT [FK_TPROC_PO_VRF]
GO

ALTER TABLE [dbo].[TPROC_VRF_PO] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_VRF_PO] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


