USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_GEN__CREAT__7755B73D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_GENERATOR] DROP CONSTRAINT [DF__TPROC_GEN__CREAT__7755B73D]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_GEN__ROW_S__7849DB76]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_GENERATOR] DROP CONSTRAINT [DF__TPROC_GEN__ROW_S__7849DB76]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_GENERATOR]    Script Date: 01/03/2018 12:37:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_GENERATOR]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_GENERATOR]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_GENERATOR]    Script Date: 01/03/2018 12:37:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_GENERATOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TABLE_CODE] [varchar](5) NOT NULL,
	[TABLE_NAME] [varchar](50) NOT NULL,
	[LAST_SEQ_NO] [int] NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_TEPROC_GENERATOR] UNIQUE NONCLUSTERED 
(
	[TABLE_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_GENERATOR] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_GENERATOR] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


