USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DIVISION_USER_DT]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_USER_DT]'))
ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [FK_DIVISION_USER_DT]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ROLE_USER_DETAIL]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_USER_DT]'))
ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [FK_ROLE_USER_DETAIL]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WA_GROUP_USER_DETAIL]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_USER_DT]'))
ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [FK_WA_GROUP_USER_DETAIL]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__CREAT__689D8392]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [DF__TPROC_USE__CREAT__689D8392]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__ROW_S__6991A7CB]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [DF__TPROC_USE__ROW_S__6991A7CB]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__COMP___6A85CC04]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER_DT] DROP CONSTRAINT [DF__TPROC_USE__COMP___6A85CC04]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_USER_DT]    Script Date: 01/03/2018 12:47:39 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_USER_DT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_USER_DT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_USER_DT]    Script Date: 01/03/2018 12:47:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_USER_DT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WA_ALLOWED_GR_ID] [int] NOT NULL,
	[ROLE_ID] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[DIVISION_ID] [int] NULL,
	[COMP_CD] [int] NULL,
	[REV_USER_ID] [int] NULL,
	[IS_EPROC_ADMIN] [int] NULL,
	[IS_SUPER_ADMIN] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_USER_DT]  WITH CHECK ADD  CONSTRAINT [FK_DIVISION_USER_DT] FOREIGN KEY([DIVISION_ID])
REFERENCES [dbo].[TPROC_DIVISION] ([ID])
GO

ALTER TABLE [dbo].[TPROC_USER_DT] CHECK CONSTRAINT [FK_DIVISION_USER_DT]
GO

ALTER TABLE [dbo].[TPROC_USER_DT]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_USER_DETAIL] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[TPROC_ROLE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_USER_DT] CHECK CONSTRAINT [FK_ROLE_USER_DETAIL]
GO

ALTER TABLE [dbo].[TPROC_USER_DT]  WITH CHECK ADD  CONSTRAINT [FK_WA_GROUP_USER_DETAIL] FOREIGN KEY([WA_ALLOWED_GR_ID])
REFERENCES [dbo].[TPROC_WA_ALLOWED_GR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_USER_DT] CHECK CONSTRAINT [FK_WA_GROUP_USER_DETAIL]
GO

ALTER TABLE [dbo].[TPROC_USER_DT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_USER_DT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO

ALTER TABLE [dbo].[TPROC_USER_DT] ADD  DEFAULT ((0)) FOR [COMP_CD]
GO


