USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FIELD_DESCRIPTIONS]    Script Date: 01/03/2018 12:35:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_FIELD_DESCRIPTIONS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_FIELD_DESCRIPTIONS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FIELD_DESCRIPTIONS]    Script Date: 01/03/2018 12:35:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_FIELD_DESCRIPTIONS](
	[APP_CD] [varchar](5) NOT NULL,
	[FLD_NM] [varchar](30) NOT NULL,
	[FLD_NM_DESC] [varchar](100) NOT NULL,
	[DATA_TYP] [varchar](1) NOT NULL,
	[DFLT_VALU] [varchar](30) NULL,
	[USER_MODIFY_IND] [varchar](1) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_TPROC_FIELD_DESCRIPTIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


