USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_APPROVAL_RELDEPT_GR]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_REL_DEPT]'))
ALTER TABLE [dbo].[TPROC_REL_DEPT] DROP CONSTRAINT [FK_APPROVAL_RELDEPT_GR]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_REL__CREAT__3429BB53]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_REL_DEPT] DROP CONSTRAINT [DF__TPROC_REL__CREAT__3429BB53]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_REL__ROW_S__351DDF8C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_REL_DEPT] DROP CONSTRAINT [DF__TPROC_REL__ROW_S__351DDF8C]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_REL_DEPT]    Script Date: 01/03/2018 12:45:13 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_REL_DEPT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_REL_DEPT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_REL_DEPT]    Script Date: 01/03/2018 12:45:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_REL_DEPT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RELATED_DEPARTMENT_NAME] [varchar](50) NOT NULL,
	[APPROVAL_RELDEPT_GR_ID] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_RELATED_DEPARTMENT] UNIQUE NONCLUSTERED 
(
	[RELATED_DEPARTMENT_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_REL_DEPT]  WITH CHECK ADD  CONSTRAINT [FK_APPROVAL_RELDEPT_GR] FOREIGN KEY([APPROVAL_RELDEPT_GR_ID])
REFERENCES [dbo].[TPROC_APPR_RELDEPT_GR] ([ID])
GO

ALTER TABLE [dbo].[TPROC_REL_DEPT] CHECK CONSTRAINT [FK_APPROVAL_RELDEPT_GR]
GO

ALTER TABLE [dbo].[TPROC_REL_DEPT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_REL_DEPT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


