USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_FORM_TYPE_STOCK]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_STOCK]'))
ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [FK_TPROC_FORM_TYPE_STOCK]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_GOOD_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_STOCK]'))
ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [FK_TPROC_GOOD_TYPE]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_STO__CREAT__3D7E1B63]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [DF__TPROC_STO__CREAT__3D7E1B63]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_STO__ROW_S__3E723F9C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [DF__TPROC_STO__ROW_S__3E723F9C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_STO__QUANT__3F6663D5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [DF__TPROC_STO__QUANT__3F6663D5]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_STO__QUANT__405A880E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_STOCK] DROP CONSTRAINT [DF__TPROC_STO__QUANT__405A880E]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_STOCK]    Script Date: 01/03/2018 12:46:03 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_STOCK]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_STOCK]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_STOCK]    Script Date: 01/03/2018 12:46:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_STOCK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_CODE] [varchar](10) NOT NULL,
	[ITEM_DESCRIPTION] [varchar](100) NOT NULL,
	[LOOKUP_CODE] [varchar](50) NULL,
	[UNIT_OF_STOCK] [varchar](10) NULL,
	[LATEST_COST] [int] NOT NULL,
	[AVERAGE_COST] [int] NOT NULL,
	[PURCHASE_ACCOUNT] [varchar](8) NOT NULL,
	[STOCK_EXPENSES] [varchar](8) NOT NULL,
	[GOOD_TYPE_ID] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[SUPPLIER_ID] [int] NULL,
	[QUANTITY] [int] NULL,
	[FORM_TYPE_ID] [int] NULL,
	[QUANTITY_MIN] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_TPROC_STOCK] UNIQUE NONCLUSTERED 
(
	[ITEM_CODE] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_FORM_TYPE_STOCK] FOREIGN KEY([FORM_TYPE_ID])
REFERENCES [dbo].[TPROC_FORM_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_STOCK] CHECK CONSTRAINT [FK_TPROC_FORM_TYPE_STOCK]
GO

ALTER TABLE [dbo].[TPROC_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_GOOD_TYPE] FOREIGN KEY([GOOD_TYPE_ID])
REFERENCES [dbo].[TPROC_GOOD_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_STOCK] CHECK CONSTRAINT [FK_TPROC_GOOD_TYPE]
GO

ALTER TABLE [dbo].[TPROC_STOCK] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_STOCK] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO

ALTER TABLE [dbo].[TPROC_STOCK] ADD  DEFAULT ((0)) FOR [QUANTITY]
GO

ALTER TABLE [dbo].[TPROC_STOCK] ADD  DEFAULT ((0)) FOR [QUANTITY_MIN]
GO


