USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_SUPP_DOC]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_SUPP_DOC]'))
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [FK_TPROC_SUPP_DOC]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__WEIGH__47FBA9D6]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__WEIGH__47FBA9D6]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__BRIDG__48EFCE0F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__BRIDG__48EFCE0F]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUPP___NDA__49E3F248]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUPP___NDA__49E3F248]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__CIDCI__4AD81681]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__CIDCI__4AD81681]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__LEGAL__4BCC3ABA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__LEGAL__4BCC3ABA]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__AGGRE__4CC05EF3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__AGGRE__4CC05EF3]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__VALID__4DB4832C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__VALID__4DB4832C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__CREAT__4EA8A765]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__CREAT__4EA8A765]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_SUP__ROW_S__4F9CCB9E]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_SUPP_DOC] DROP CONSTRAINT [DF__TPROC_SUP__ROW_S__4F9CCB9E]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_SUPP_DOC]    Script Date: 01/03/2018 12:46:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_SUPP_DOC]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_SUPP_DOC]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_SUPP_DOC]    Script Date: 01/03/2018 12:46:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_SUPP_DOC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [int] NOT NULL,
	[WEIGHT_FACTOR] [int] NULL,
	[BRIDGER_SCAN] [int] NULL,
	[NDA] [int] NULL,
	[CIDCI] [int] NULL,
	[LEGAL_DOC] [int] NULL,
	[AGGREEMENT] [int] NULL,
	[VALIDITY_CHECKING] [int] NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_SUPP_DOC] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[TPROC_SUPPLIER] ([ID])
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] CHECK CONSTRAINT [FK_TPROC_SUPP_DOC]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [WEIGHT_FACTOR]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [BRIDGER_SCAN]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [NDA]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [CIDCI]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [LEGAL_DOC]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [AGGREEMENT]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [VALIDITY_CHECKING]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_SUPP_DOC] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


