USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_REQ__REQUE__32767D0B]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_REQUEST] DROP CONSTRAINT [DF__TPROC_REQ__REQUE__32767D0B]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_REQ__CREAT__336AA144]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_REQUEST] DROP CONSTRAINT [DF__TPROC_REQ__CREAT__336AA144]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_REQ__ROW_S__345EC57D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_REQUEST] DROP CONSTRAINT [DF__TPROC_REQ__ROW_S__345EC57D]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_REQUEST]    Script Date: 01/03/2018 12:45:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_REQUEST]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_REQUEST]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_REQUEST]    Script Date: 01/03/2018 12:45:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_REQUEST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REQUEST_NO] [varchar](50) NOT NULL,
	[RELATION_FLAG] [varchar](50) NOT NULL,
	[REQUEST_BY] [varchar](50) NOT NULL,
	[REQUEST_DT] [datetime] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[STATUS] [int] NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[CONTROL] [varchar](50) NULL,
	[ACTION] [varchar](50) NULL,
	[REQUESTOR_EMAIL] [varchar](100) NULL,
	[APPROVAL_BY] [varchar](50) NULL,
	[APPROVAL_EMAIL] [varchar](100) NULL,
	[APPROVED_TIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UN_REQ_NUMB] UNIQUE NONCLUSTERED 
(
	[REQUEST_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_REQUEST] ADD  DEFAULT (sysdatetime()) FOR [REQUEST_DT]
GO

ALTER TABLE [dbo].[TPROC_REQUEST] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_REQUEST] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


