USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_HOL__CREAT__05A3D694]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_HOLIDAY] DROP CONSTRAINT [DF__TPROC_HOL__CREAT__05A3D694]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_HOL__ROW_S__0697FACD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_HOLIDAY] DROP CONSTRAINT [DF__TPROC_HOL__ROW_S__0697FACD]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_HOLIDAY]    Script Date: 01/03/2018 12:38:22 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_HOLIDAY]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_HOLIDAY]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_HOLIDAY]    Script Date: 01/03/2018 12:38:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_HOLIDAY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HOLIDAY_DATE] [datetime] NOT NULL,
	[HOLIDAY_DESCRIPTION] [varchar](100) NOT NULL,
	[CURR_YEAR] [int] NOT NULL,
	[CURR_MONTH] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_HOLIDAY] UNIQUE NONCLUSTERED 
(
	[HOLIDAY_DATE] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_HOLIDAY] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_HOLIDAY] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


