USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_BUD__IS_AC__44CA3770]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_BUDGET_CODE] DROP CONSTRAINT [DF__TPROC_BUD__IS_AC__44CA3770]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_BUD__CREAT__45BE5BA9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_BUDGET_CODE] DROP CONSTRAINT [DF__TPROC_BUD__CREAT__45BE5BA9]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_BUD__ROW_S__46B27FE2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_BUDGET_CODE] DROP CONSTRAINT [DF__TPROC_BUD__ROW_S__46B27FE2]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_BUDGET_CODE]    Script Date: 01/03/2018 12:32:24 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_BUDGET_CODE]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_BUDGET_CODE]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_BUDGET_CODE]    Script Date: 01/03/2018 12:32:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_BUDGET_CODE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TABLE_BUDGET] [varchar](20) NULL,
	[TABLE_BUDGET_USAGE] [varchar](20) NULL,
	[CD_PRINTING_USAGE] [varchar](20) NULL,
	[CD_PRINTING_START] [varchar](20) NULL,
	[CD_PRINTING_END] [varchar](20) NULL,
	[CD_OFFICE_SUPPLIE_USAGE] [varchar](20) NULL,
	[CD_OFFICE_SUPPLIE_START] [varchar](20) NULL,
	[CD_OFFICE_SUPPLIE_END] [varchar](20) NULL,
	[CD_ASSET_NONASSET_USAGE] [varchar](20) NULL,
	[CD_ASSET_NONASSET_START] [varchar](20) NULL,
	[CD_ASSET_NONASSET_END] [varchar](20) NULL,
	[CD_PROMOTIONAL_ITEM_USAGE] [varchar](20) NULL,
	[CD_PROMOTIONAL_ITEM_START] [varchar](20) NULL,
	[CD_PROMOTIONAL_ITEM_END] [varchar](20) NULL,
	[IS_ACTIVE] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[CD_ISSUED_USAGE] [varchar](20) NULL,
	[TABLE_T1] [varchar](20) NULL,
	[TABLE_T2] [varchar](20) NULL,
	[TABLE_T3] [varchar](20) NULL,
	[TABLE_T5] [varchar](20) NULL,
	[CD_OFFICE_SUPPLIE_MT] [varchar](20) NULL,
	[CD_PRINTING_MT] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_BUDGET_CODE] ADD  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [dbo].[TPROC_BUDGET_CODE] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_BUDGET_CODE] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


