USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___CREAT__2704CA5F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_DT] DROP CONSTRAINT [DF__TPROC_PC___CREAT__2704CA5F]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PC___ROW_S__27F8EE98]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PC_DT] DROP CONSTRAINT [DF__TPROC_PC___ROW_S__27F8EE98]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_DT]    Script Date: 01/03/2018 12:40:48 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PC_DT]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PC_DT]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PC_DT]    Script Date: 01/03/2018 12:40:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PC_DT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_NAME] [varchar](100) NOT NULL,
	[UNIT_MEASUREMENT] [varchar](50) NULL,
	[QUANTITY] [int] NOT NULL,
	[PRICE] [int] NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [date] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[TOTAL] [int] NULL,
	[ROW_NUM] [int] NULL,
	[PC_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PC_DT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PC_DT] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


