USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USER_DT]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_USER]'))
ALTER TABLE [dbo].[TPROC_USER] DROP CONSTRAINT [FK_USER_DT]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__CREAT__7226EDCC]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER] DROP CONSTRAINT [DF__TPROC_USE__CREAT__7226EDCC]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_USE__ROW_S__731B1205]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_USER] DROP CONSTRAINT [DF__TPROC_USE__ROW_S__731B1205]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_USER]    Script Date: 01/03/2018 12:47:29 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_USER]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_USER]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_USER]    Script Date: 01/03/2018 12:47:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
	[USER_MAIL] [varchar](100) NOT NULL,
	[USER_NAME] [varchar](50) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[USER_DT_ID] [int] NOT NULL,
	[LAST_LOGIN] [datetime] NULL,
	[PASSWORD] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_USER_EPROC] UNIQUE NONCLUSTERED 
(
	[USER_ID] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_DT] FOREIGN KEY([USER_DT_ID])
REFERENCES [dbo].[TPROC_USER_DT] ([ID])
GO

ALTER TABLE [dbo].[TPROC_USER] CHECK CONSTRAINT [FK_USER_DT]
GO

ALTER TABLE [dbo].[TPROC_USER] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_USER] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


