USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPROC_FORM_TYPE_PO]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PO_TYPE]'))
ALTER TABLE [dbo].[TPROC_PO_TYPE] DROP CONSTRAINT [FK_TPROC_FORM_TYPE_PO]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___CREAT__0C1BC9F9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_TYPE] DROP CONSTRAINT [DF__TPROC_PO___CREAT__0C1BC9F9]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___ROW_S__0D0FEE32]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_TYPE] DROP CONSTRAINT [DF__TPROC_PO___ROW_S__0D0FEE32]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PO_TYPE]    Script Date: 01/03/2018 12:42:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PO_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PO_TYPE]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PO_TYPE]    Script Date: 01/03/2018 12:42:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PO_TYPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_TYPE_NAME] [varchar](5) NOT NULL,
	[PO_TYPE_DESCRIPTION] [varchar](100) NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[FORM_TYPE_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_PO_TYPE] UNIQUE NONCLUSTERED 
(
	[PO_TYPE_NAME] ASC,
	[ROW_STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PO_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_TPROC_FORM_TYPE_PO] FOREIGN KEY([FORM_TYPE_ID])
REFERENCES [dbo].[TPROC_FORM_TYPE] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PO_TYPE] CHECK CONSTRAINT [FK_TPROC_FORM_TYPE_PO]
GO

ALTER TABLE [dbo].[TPROC_PO_TYPE] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PO_TYPE] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


