USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_FIE__CREAT__6AEFE058]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_FIELD_VALUES] DROP CONSTRAINT [DF__TPROC_FIE__CREAT__6AEFE058]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_FIE__ROW_S__6BE40491]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_FIELD_VALUES] DROP CONSTRAINT [DF__TPROC_FIE__ROW_S__6BE40491]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FIELD_VALUES]    Script Date: 01/03/2018 12:35:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_FIELD_VALUES]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_FIELD_VALUES]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_FIELD_VALUES]    Script Date: 01/03/2018 12:35:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_FIELD_VALUES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[APP_CD] [varchar](5) NOT NULL,
	[FLD_NM] [varchar](30) NOT NULL,
	[FLD_VALU] [varchar](20) NOT NULL,
	[FLD_VALU_DESC] [varchar](120) NULL,
	[FLD_VALU_DESC_ENG] [varchar](120) NULL,
	[SEQ_NUM] [int] NULL,
	[FLD_VALU_MNE_CD] [varchar](30) NULL,
	[STAT_CD] [varchar](1) NOT NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_FIELD_VALUES] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_FIELD_VALUES] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


