USE [eProcurement]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PO_HEADER_ID]') AND parent_object_id = OBJECT_ID(N'[dbo].[TPROC_PO_DETAILS]'))
ALTER TABLE [dbo].[TPROC_PO_DETAILS] DROP CONSTRAINT [FK_PO_HEADER_ID]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___CREAT__61F08603]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_DETAILS] DROP CONSTRAINT [DF__TPROC_PO___CREAT__61F08603]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__TPROC_PO___ROW_S__62E4AA3C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TPROC_PO_DETAILS] DROP CONSTRAINT [DF__TPROC_PO___ROW_S__62E4AA3C]
END

GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PO_DETAILS]    Script Date: 01/03/2018 12:41:46 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TPROC_PO_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[TPROC_PO_DETAILS]
GO

USE [eProcurement]
GO

/****** Object:  Table [dbo].[TPROC_PO_DETAILS]    Script Date: 01/03/2018 12:41:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPROC_PO_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_DTLS_ITEM_ID] [int] NOT NULL,
	[ITEM_NAME] [varchar](50) NULL,
	[USERMEASUREMENT] [varchar](5) NULL,
	[QUANTITY] [int] NULL,
	[PRICE] [int] NULL,
	[TOTAL] [int] NULL,
	[CREATED_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[LAST_MODIFIED_TIME] [datetime] NULL,
	[LAST_MODIFIED_BY] [varchar](50) NULL,
	[ROW_STATUS] [int] NOT NULL,
	[FUND_T1] [varchar](10) NULL,
	[LOB1_T2] [varchar](10) NULL,
	[PLAN_T3] [varchar](10) NULL,
	[WA_T4] [varchar](10) NULL,
	[LOB2_T5] [varchar](10) NULL,
	[PR_HEADER_NO] [varchar](50) NOT NULL,
	[ITEM_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TPROC_PO_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_PO_HEADER_ID] FOREIGN KEY([PO_DTLS_ITEM_ID])
REFERENCES [dbo].[TPROC_PO_DETAILS_ITEM] ([ID])
GO

ALTER TABLE [dbo].[TPROC_PO_DETAILS] CHECK CONSTRAINT [FK_PO_HEADER_ID]
GO

ALTER TABLE [dbo].[TPROC_PO_DETAILS] ADD  DEFAULT (sysdatetime()) FOR [CREATED_TIME]
GO

ALTER TABLE [dbo].[TPROC_PO_DETAILS] ADD  DEFAULT ((0)) FOR [ROW_STATUS]
GO


